### PR TITLE
Fix/apple silicon performance

### PR DESCRIPTION
**Pull request by jackryanservia**
Explain your changes:
* Added detect-gpu dependency for SnarkyJS
* Fixed Apple silicon performance issue.
* SnarkyJS will now detect when running on Apple silicon and use the most efficient number of workers. Required because of the issue outlined [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1228686).

Explain how you tested your changes:
* Built version that console logged all relevant information.
* Ran on all environment/machine combinations (Except M1 Ultra and M2 (but it's obviouse they will work)).

Caveats:
* If the page is rendered serverside, we can't detect the platform. So we default the number of workers to a conservative guess. There is probably a way to enforce that the detect-gpu code runs client-side (in most cases), but I don't have a ton of experience with front-end frameworks and didn't think this was a high priority.
* Mobile devices aren't accounted for yet (many of them (even if they don't run Apple silicon) will suffer from the same problem (but it's easy to add support any time)).
* Values for the number of workers are hard-coded and based on limited testing.

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

After merge: o1-labs/snarkyjs#683

* Closes o1-labs/snarkyjs#491

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by ymekuria — APPROVED** [review]
Thanks for adding this!

**Comment by jackryanservia** [comment]
!ci-build-me

**Comment by Trivo25** [comment]
!ci-build-me

**Pull request merged**
