### PR TITLE
Add last VRF output and subwindow densities to blocks in archive

### PR DESCRIPTION
**Pull request by psteckler**
These fields will be useful for chain selection by the archive API . See #12690.

### CODE REVIEW

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by MartinMinkov** [comment]
Just want to confirm incase I'm missing something. Is there any other data that's missing from the schema that is being used by https://github.com/MinaProtocol/mina/blob/8f1e7bc678657360be16d18186b54228a9fb526f/src/lib/consensus/proof_of_stake.ml#L2948 or should this be the everything that the algorithm needs? I'm pretty sure it's everything but I just want to be sure incase I'm missing something :grimacing:

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Pull request merged**
