### PR TITLE
Master nightly CI fix 

### PR DESCRIPTION
**Pull request by dkijania**
Another fix in build debian script. Added suggested deps for mina-devnet

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
Hello, @dkijania 1 new  created to help you port this change to master. Please follow steps to resolve conflict for each mainline branch. PRs will be created automatically after you push merge to porting branches

  
## compatible 

```
git fetch && git checkout port/_master_nightly_test_to_compatible && git merge master_nightly_test
```

Resolve conflict and then 

```
git push
```

**Comment by dkijania** [comment]
Porting branch #15772 to resolve conflict with compatible created. Please merge it in order to solve conflict between head of this PR and compatible

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Review by nholland94 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
