### PR TITLE
Build instrumented mina in CI

### PR DESCRIPTION
**Pull request by dkijania**
Add another build for mina bullseye with instrumentation flags. This will help in various debugging activities as well as measuring coverage. test-suite docker is also by default fetching instrumented daemon and archive

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-buile-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
