### PR TITLE
Add `delete_account` field to  `Account_update.Body.Stable.t`type definition

### LINKED ISSUE #15829: Add `delete_account`field to `Account_update.Body.Stable.t`type definition
See  [this description in the RFC](https://github.com/o1-labs/rfcs/blob/6851b42c7ed0462b8f89ceb43f851374f13223d0/00xx-account-deletion.md#L388-L389)

### PR DESCRIPTION
**Pull request by rbonichon**
Fixes #15829

### CODE REVIEW

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by psteckler** [comment]
The type containment facility in my pending PR #15361 might be useful to know which other versioned types are affected by the change to the versioned type.

**Pull request closed without merging**
