### PR TITLE
Removed Test executive dockers and buster debian

### PR DESCRIPTION
**Pull request by dkijania**
Looks like terraform package for buster is no longer available. As a result we need to  remove test-executive debian for buster

This is also a good time to revise test-executive docker existence. After Martin added docker mode for TE it is impossible to run TE in this mode from docker (we would need some docker In Docker solution). Also, in CI we are not using docker at all but debian (not to wait for docker build)
I think there is a point of keeping TE debian as maybe some our partners can use docker mode to run out integration tests. Internally we can stay with binary (if nix can help us build quickly test_executive binary)

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by svv232 — APPROVED** [review]

**Comment by georgeee** [comment]
@dkijania could you confirm that we're still going to build test-executive debian package?

Only docker is removed because it isn't used.

**Review by georgeee — APPROVED** [review]

**Comment by dkijania** [comment]
Yes, we build only debians for test executive

**Review by amc-ie — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
