### PR TITLE
Remove Transaction_snark.system compilation message

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR stops us from printing the log message for `Transaction_snark.system` compilation time on stdout. This gives us a more consistent output format for the unit tests.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by psteckler — APPROVED** [review]
Yay!

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by georgeee** [comment]
In a separate PR I introduced a change from `printf` to `eprintf`, but don't mind removing it altogether

**Review by georgeee — APPROVED** [review]

**Pull request merged**
