### PR TITLE
Merge Compatible into Develop

### PR DESCRIPTION
**Pull request by martyall**

### CODE REVIEW

**Comment by martyall** [comment]
!ci-nightly-me

**Comment by martyall** [comment]
!ci-nightly-me

**Comment by martyall** [comment]
[Nightly results here](https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2681)

**Review by georgeee — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Comment by martyall** [comment]
@MinaProtocol/mina-foundation-eng @joaosreis

**Review by joaosreis — APPROVED** [review]

**Pull request merged**
