### PR TITLE
Fix rosetta block query

### PR DESCRIPTION
**Pull request by Sventimir**
Explain your changes:
* Once again changes to the archive DB schema invalidated some queries in Rosetta server. This PR is to update these queries to much current schema.

Explain how you tested your changes:
* Run rosetta-cli test suite against an ITN node.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Review by bkase — APPROVED** [review]

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!approved-for-mainnet

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
