### PR TITLE
Use first pass ledger for snarked ledger everywhere

### PR DESCRIPTION
**Pull request by deepthiskumar**
Explain your changes:
* Block validation to use first pass ledger for snarked ledger
* Lift snarked ledger hash to the protocol state/blockchain state lib and refactored the code a bit to make it clearer
* Fixed a bug in breadcrumb generation for tests

Explain how you tested your changes:
* Existing unit tests covered the changes

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by deepthiskumar** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1186#_

**Comment by georgeee** [comment]
@deepthiskumar could you add to description the following details:

1. If this a non-backwards-compatible change or merely a refactor?
2. What was the problem with the previous code
3. Why is this change targeted against `berkeley` and not `develop` (or next hardfork branch)?

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
