### PR TITLE
[CI] Add teardown job instrumentation

### PR DESCRIPTION
**Pull request by dkijania**
Explain your changes:
Added new coverage tear down job which should be run after all PR jobs. 

Important:
CI pipeline setting need to be alter in order to fully benefit from this change. Example pipeline settings:

```
steps:
  - commands:
      - .....
    label: ":pipeline: Test"
    plugins:
      "docker#v3.5.0":
        environment:
          - "BUILDKITE_PIPELINE_STAGE=Test"
          ....
  - wait
  - commands:
       - ....
    label: ":pipeline: Tear Down"
    plugins:
      "docker#v3.5.0":
        environment:
          - "BUILDKITE_PIPELINE_STAGE=TearDown"
        .....
```

Explain how you tested your changes:
Tested in CI

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
