### PR TITLE
Fix snark pool long async cycles (merge into berkeley)

### PR DESCRIPTION
**Pull request by nholland94**
Merges https://github.com/MinaProtocol/mina/pull/13409 into berkeley.

### CODE REVIEW

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by nholland94** [comment]
!ci-build-me

**Pull request merged**
