### PR TITLE
[Port][Dev] limiting correctly publishing deb attempts 

### PR DESCRIPTION
**Pull request by dkijania**
porting https://github.com/MinaProtocol/mina/pull/16189 to develop branch

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-nightly-me

**Pull request merged**
