### PR TITLE
Fix zero vesting period test

### PR DESCRIPTION
**Pull request by psteckler**
The zero vesting period tests in `Mina_base.Test` were bit-rotted, and not being run.

Fixed:
- the JSON for the zkApp was updated with the current syntax for account preconditions
- the tests were converted from `ppx_test` inline tests to Alcotest format, added to `main.ml`

Tested by running:
```
dune exec src/lib/mina_base/test/main.exe -- test '^zero vesting period$'
```

Output:
```
...
[OK]                zero vesting period          0   Zero vesting period is error.
[OK]                zero vesting period          1   Nonzero vesting period is OK.
...
```
Also, I temporarily changed the successful branches in the test to run `assert false`, and Alcotest reported the failures.

### CODE REVIEW

**Review by georgeee — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
Discovered that `dev` and `devnet` profiles have different account creation fees, need to adjust test for that.

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
