### PR TITLE
unify json config loading

### PR DESCRIPTION
**Pull request by martyall**
This PR stacks on #16163

# The Problem
There should only be one way to load json files to construct a value of type `Runtime_config.t`, we have several:

 - `Mina_cli_entrypoint` checks system directories for an installed config file, other places do not
 - `Mina_cli_entrypoint` logs verbosely where it finds certain values that belong the `daemon` object. This requires special handling to load these values only to gain a `debug` log -- we don't do this for any other fields or in any other CLI context, and would require more complicated handling. The fact that the `~keyname` arguments for the logger are not derived from the value means they can drift.
 - `Mina_cli_entrypoint` will also attempt to _write_ configuration as it is reading it. This addition was made something like 4 years ago. Rather than attempting to modify configuration on a users file system, at this point it seems wiser to just throw a parse exception.
 
 ## The solution
 - Introduce a module `Runtime_config.Json_loader` to handle all `Runtime_config` loading logic, use this in all executables.
 - Use the same standard for loading `daemon` field values as we do for everything else
 - Remove the old `update_config` function that writes a json  as it is loading.

### CODE REVIEW

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-nightly-me

**Comment by martyall** [comment]
Nightly tests here https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/35530#_

Passes everything except for merge cleanly checks, which will wait to review and supporting PRs are merged

**Review by georgeee — APPROVED** [review]
To confirm: there won't be a `trace` log for each value in `daemon` showing which config file originated it. I'm fine with that.

**Comment by martyall** [comment]
> To confirm: there won't be a trace log for each value in daemon showing which config file originated it. I'm fine with that.

Yes that is the only concrete difference. I dont think there was a real reason to do it there before, likely more of a consequence of having a separate loader for those undeclared values removed in the prior pr.

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-nightly-me

**Comment by martyall** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2695

**Pull request merged**
