### PR TITLE
adding network id field to the daemon

### PR DESCRIPTION
**Pull request by svv232**
This is a pr that adds the network id field to the daemon. It's purpose is to ensure the correct output result from a fork config, such that the networkId graphql endpoint is correct.

### CODE REVIEW

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by svv232** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by dkijania** [comment]
Please run nightly before merging

**Comment by svv232** [comment]
!ci-nightly-me

**Pull request merged**
