### PR TITLE
[Develop][Nightly][CI] Making nightly tests green

### PR DESCRIPTION
**Pull request by dkijania**
Introduced two changes which should make develop nightly green again:

- soft fail to hf test (while fixing is in progress)
- moving all integration tests to docker

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]
[Nightly](https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2277)

**Pull request merged**
