### PR TITLE
Merge 13654 to berkeley

### PR DESCRIPTION
**Pull request by psteckler**
Allow clean merge of #13654 to `berkeley`.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by nholland94** [comment]
This PR is merging not just https://github.com/MinaProtocol/mina/pull/13654 into `berkeley`, but also other changes from `compatible` into `berkeley`. Can we start with a PR that just merges the latest `compatible` into `berkeley` first?

**Comment by mrmr1993** [comment]
https://github.com/MinaProtocol/mina/pull/14145

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by psteckler** [comment]
No changes, so closing ...

**Pull request closed without merging**
