### PR TITLE
Merge berkeley into develop

### PR DESCRIPTION
**Pull request by rbonichon**
Mostly in order to get back https://github.com/MinaProtocol/mina/pull/14606 for develop

### CODE REVIEW

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Review by dannywillems — APPROVED** [review]
Approving for the linter fix.

**Review by mrmr1993 — APPROVED** [review]

**Review by dkijania — APPROVED** [review]

**Review by ymekuria — APPROVED** [review]

**Pull request merged**
