### PR TITLE
Merge rampup into berkeley

### PR DESCRIPTION
**Pull request by mitschabaude**

### CODE REVIEW

**Review by psteckler — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Comment by stevenplatt** [comment]
@mitschabaude this branch can be merged into your PR to resolve the CI fails relating to Docker images:
https://github.com/MinaProtocol/mina/pull/13110

It is pending a merge into `rampup`, but has not landed yet.

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Review by rbonichon — APPROVED** [review]

**Review by nholland94 — APPROVED** [review]

**Comment by stevenplatt** [comment]
!ci-build-me

**Pull request merged**
