### PR TITLE
Fix pickles compilation errors

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR fixes the compilation error in `src/lib/pickles`, caused by a restrictive interface added to the `Kimchi_backend` library.

This is a no-op, besides fixing `dune build src/lib/pickles`.

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Review by mimoo — APPROVED** [review]
awesome thanks a lot!

**Review by fabrizio-m — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
