### PR TITLE
Nit: follow-up on random offset PR

### PR DESCRIPTION
**Pull request by anne-laure-s**
This PR addresses @mrmr1993 comments on the random offset work selection PR (https://github.com/MinaProtocol/mina/pull/15981#discussion_r1757608130 & https://github.com/MinaProtocol/mina/pull/15981#discussion_r1757610675)

### CODE REVIEW

**Comment by anne-laure-s** [comment]
!ci-build-me

**Review by mrmr1993 — DISMISSED** [review]

**Comment by mrmr1993** [comment]
@anne-laure-s can you redirect this PR to be against `compatible` please?

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by anne-laure-s** [comment]
!ci-build-me

**Pull request merged**
