### PR TITLE
merge compatible to develop 1709

### PR DESCRIPTION
**Pull request by dkijania**

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by SanabriaRusso — APPROVED** [review]
lgtm for infra.

**Review by dannywillems — APPROVED** [review]
LGTM for crypto. It is some PR simplifying the Pickles types + bump up to arkworks 0.4.2.

**Review by georgeee — APPROVED** [review]

**Review by Trivo25 — APPROVED** [review]

**Review by joaosreis — APPROVED** [review]

**Pull request merged**
