### PR TITLE
remove berkeley related jobs

### PR DESCRIPTION
**Pull request by dkijania**
After Berkeley release is out devnet equals berkeley in term of naming convention and content. We can freely remove berkeley reference from CI

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by mrmr1993 — COMMENTED** [review]
Please split this PR up. The changes to each of the files is unrelated. Grouping them together in this PR is a recipe for a bad review and another potential broken release or CI breakage.

**Comment by dkijania** [comment]
Closing in favor of split PRS:

https://github.com/MinaProtocol/mina/pull/16311 - remove berkeley from docs
https://github.com/MinaProtocol/mina/pull/16312 - remove berkeley from promotion jobs
https://github.com/MinaProtocol/mina/pull/16313 - lightnet package (berkeley -> devnet)
https://github.com/MinaProtocol/mina/pull/16314 - integration tests
https://github.com/MinaProtocol/mina/pull/16315 - connectivity tests
https://github.com/MinaProtocol/mina/pull/16316 - compatibility tests

**Pull request closed without merging**
