### PR TITLE
[o1js-main] Fix Boolean constraint

### PR DESCRIPTION
**Pull request by mitschabaude**
This fixes snarky's `Boolean` constraint - it ignored the scaling factor, so that for example the following unsatisfiable o1js circuit could be proven:
```ts
let b = Provable.witness(Field, () => Field(1));
b.assertEquals(1);
b.mul(2).assertBool(); // snarky treated this as `b.assertBool()`
```

### CODE REVIEW

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]
:scream: Can you point this PR at Berkeley instead?

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by tizoc** [comment]
@mitschabaude @mrmr1993 I see that proof-systems the old version is still used, shouldn't it be updated too?

https://github.com/o1-labs/proof-systems/blob/5ab7ded5f06db43ca60cf43fb4c67cf5dabc7fe1/kimchi/src/snarky/constraint_system.rs#L1183-L1203

**Pull request merged**
