### PR TITLE
remove unused mlh config files

### PR DESCRIPTION
**Pull request by martyall**
This PR is to remove all of the `.mlh` compile time configuration files that are not currently being used. The files that are deleted here did not appear to be referenced anywhere in the code base (unless I made a mistake, hopefully someone can double check this). I have tested to make sure the following build profiles still build

- `mainnet`
- `dev`
- `devnet`
- `lightnet`

The following build profiles do not currently build, *but they also fail on*  `develop:HEAD` when i try to invoke them naively:
- `testnet_postake_medium_curves`
- `integration_tests`

with the same error

```
File "src/lib/genesis_constants/genesis_constants.ml", line 369, characters 32-50:
369 | [%%inject "grace_period_slots", grace_period_slots]
```

I have double checked with @dkijania and I think it's safe to just delete these profiles

### CODE REVIEW

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-nightly-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Comment by martyall** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Pull request merged**
