### PR TITLE
Update bindings for chunking fix

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR is the counterpart to https://github.com/o1-labs/proof-systems/pull/1032, building on #13275.

The only notable change is that the 'evaluation' at the challenge point for the public input polynomial is now available from the rust bindings. We don't accept this in berkeley-compatible proofs over the network, but this will become important for performant recursion over chunked proofs.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Review by rbonichon — APPROVED** [review]
LGTM

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by mitschabaude — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
