### PR TITLE
Build rosetta mainnet/devnet docker

### PR DESCRIPTION
**Pull request by dkijania**
Porting PR: https://github.com/MinaProtocol/mina/pull/16156  from compatible allowing to build rosetta mainnet

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
Nightly: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2712#0192778c-42ff-4575-b4ec-497d682e05e1

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
