### PR TITLE
Steven merge itn infra berkeley

### PR DESCRIPTION
**Pull request by stevenplatt**
Explain your changes:

This PR merges is to port the following changes from the `develop` branch, to `berkeley`:
* PR [14576](https://github.com/MinaProtocol/mina/pull/14576): Repair terraform module compatibility
* PR [14647](https://github.com/MinaProtocol/mina/pull/14647): Updated `berkeley` deployment terraform
* PR [14652](https://github.com/MinaProtocol/mina/pull/14652): ITN3 testnet and logging configurations

Additionally, this PR ports over CI test repairs from `rampup`:
* Commit [6a5b112](https://github.com/MinaProtocol/mina/commit/6a5b1123740c72328f4842c71c9c176318b89dfd): Increase test timeout time to accommodate for node needing more time to boot with larger ledger files.  

Finally, a single CI test has been disabled that was failing and blocking this PR from merging into `berkeley`:
* The test named `Terraform: Test` has been set to softfail. This test was added only to `berkeley` branch roughly a month ago. To my knowledge, it has never been function. Setting it to "softfail" prevent it from blocking infra PRs until it can be fixed.

Explain how you tested your changes:
* Each of the above PRs which are porting changes, have each been testing in itolsation as part of those original PRs. 
* The final edit of setting `Terraform: Test` to softfail has been tested by running the `mina` nightly CI pipeline: 
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/894

Checklist:

- [X] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [NA] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [X] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [NA] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [NA] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by stevenplatt** [comment]
!ci-build-me

**Comment by stevenplatt** [comment]
!ci-build-me

**Comment by stevenplatt** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by stevenplatt** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
