### PR TITLE
Port local lucy to ci

### LINKED ISSUE #14790: [CI] Enable local Lucy run in CI
After https://github.com/MinaProtocol/mina/pull/14648 is done we can implement local lucy runs.

We can take an example from experimental minimina in CI work: https://github.com/MinaProtocol/mina/pull/14251

@MartinMinkov also gave us some hints and requirements for running lucy locally:

example script:

```
#!/bin/bash
set -e

# Set up a local docker swarm
docker swarm init --advertise-addr 127.0.0.1

# Set up images to use for testing
MINA_IMAGE=gcr.io/o1labs-192920/mina-daemon:2.0.0rampup5-develop-1e360f7-bullseye-berkeley
MINA_ARCHIVE=gcr.io/o1labs-192920/mina-archive:2.0.0rampup5-develop-1e360f7-bullseye

# Specify a test to run
TEST=zkapps

# Run the test
./_build/default/src/app/test_executive/test_executive.exe local $TEST --mina-image=$MINA_IMAGE --archive-image=$MINA_ARCHIVE --debug 
```

Agent Requirements:

docker swarm in version  1.12 and later

### PR DESCRIPTION
**Pull request by dkijania**
Porting @MartinMinkov great job in implementing local test executive engine to CI

Closes #14790

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by MartinMinkov** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
Test passed: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1881#018f0b80-1dd9-453e-adc3-e87580583728

**Comment by dkijania** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]
mina_docker.ml rubberstamp

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
