### PR TITLE
Attach instrumentation for unit tests

### PR DESCRIPTION
**Pull request by dkijania**
Explain your changes:
Enhanced  unit jobs in buildkite  with mina instrumentation. Currently entire infrastructure to upload coverage files to coveralls is not enabled as we need to do it on buildkite level. It's better to first merge this PR and then enable uploading to coveralls

Explain how you tested your changes:

Tested by adding new pipeline which generates and uploads partial data to coveralls but without final tear down job. 

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by QuiteStochastic — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
