### PR TITLE
Always fetch tags before running git describe

### PR DESCRIPTION
**Pull request by dkijania**
Similar to issue described here https://github.com/buildkite/agent/issues/338 we are suffering from non deterministic behavior of `git describe command`. Issue manifests itself when building debian and dockers artifacts. We are adding latest tag to the version of artifact based on `git describe` command output. If tags are not fetched correctly (for example when buildkite agent is not performing full repo checkout) it might cause that debian will have different version and as a result docker won't be able to install when building docker. This PR is an attempt to fix it by always manually fetch tags

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
