### PR TITLE
Blocking SnarkyJS CI tests (berkeley)

### PR DESCRIPTION
**Pull request by mitschabaude**
berkeley version of https://github.com/MinaProtocol/mina/pull/13430

snarkyjs: https://github.com/o1-labs/snarkyjs/pull/996
bindings: https://github.com/o1-labs/snarkyjs-bindings/pull/49

### CODE REVIEW

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by bkase — APPROVED** [review]

**Comment by bkase** [comment]
!approved-for-mainnet

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!approved-for-mainnet

**Pull request merged**
