### PR TITLE
Finish snark test berk

### PR DESCRIPTION
**Pull request by QuiteStochastic**
berk version of this https://github.com/MinaProtocol/mina/pull/13085

### CODE REVIEW

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by stevenplatt — APPROVED** [review]

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]
Approving with the agreement of reducing # workers for payments_test.ml to 4. I think we should reduce in block_production_priority.ml as well, from 25 to 4 and reduce the scan state size (from 128 to 4)
Please keep the same for others (they are lower already and nonce test (with a different scan state size) is working well with 5 workers).

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]
CODEOWNERS stamp, otherwise unreviewed

**Pull request merged**
