### PR TITLE
Remove useless print during tests

### PR DESCRIPTION
**Pull request by dannywillems**
Explain your changes:
* Two lines are always printed while running tests, and it seems useless
```
Done: 98% (10496/10613, 117 left) (jobs: 16)
                                            
Done: 98% (10497/10613, 116 left) (jobs: 16)
                                            
Done: 98% (10498/10613, 115 left) (jobs: 16)
                                            
Done: 98% (10499/10613, 114 left) (jobs: 16)
                                            
1

12418654782883325593414442427049395787963493412651469444558597405572177144507

Done: 98% (10499/10613, 114 left) (jobs: 16)
                                            
Done: 98% (10500/10613, 113 left) (jobs: 16)
                                            
Done: 98% (10501/10613, 112 left) (jobs: 16)
                                            
Done: 98% (10502/10613, 111 left) (jobs: 16)
```
Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Review by rbonichon — APPROVED** [review]

**Comment by dannywillems** [comment]
!ci-build-me

**Pull request merged**
