### PR TITLE
Another interaction mode for delegation_verify

### PR DESCRIPTION
**Pull request by Sventimir**
Explain your changes:
* Uptime service has recently changed the way it wants to communicate with the stateless verifier. The new way is to start the verifier as a subprocess as a subprocess of a wrapper, feed all the input through stdin and read output from stdout. This PR provides the new mode of operation for the stateless verifier which does just that.

Explain how you tested your changes:
* Ran the stateless verifier in different modes against different inputs.
* These changes will also be tested extensively during end-to-end tests of the uptime service.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Review by ejMina226 — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by Sventimir** [comment]
!ci-buiild-me

**Review by emberian — APPROVED** [review]

**Comment by emberian** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
