### PR TITLE
Fix/replayer use global slot from previous state

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR changes the `replayer --migration-mode` so that it's using previous consensus slot to match the behavior we have on mainnet.

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-nightly-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-nightly-me

**Comment by ghost-not-in-the-shell** [comment]
rosetta-integration test pass on this: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1266#018d6544-49c8-4618-9c31-603528460fa4

**Comment by joaosreis** [comment]
I added time-vesting accounts to the Rosetta integration test in #15017 to verify such accounts' behavior after the PR changes.

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-nightly-me

**Review by ejMina226 — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
