### PR TITLE
Revert "Merge pull request #15427 from MinaProtocol/develop-prealfalfa"

### PR DESCRIPTION
**Pull request by emberian**
This reverts commit 585a6763d1b2c56a9adfd2cb53a31304fe14bdb2, reversing changes made to 05a953c31331b89678ddd6cdf0d245c363694fea.

I failed to mark that PR as a draft and I absentmindedly merged it when CI was green despite having abandoned this patchset against berkeley.

Undo that damage.

### CODE REVIEW

**Comment by emberian** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Review by dkijania — APPROVED** [review]

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
