### PR TITLE
Update proof-systems to use single cargo lock dependencies

### PR DESCRIPTION
**Pull request by volhovm**
This PR corresponds to proof-system's PR: https://github.com/o1-labs/proof-systems/pull/2561 (which hopefully does not change much).

### CODE REVIEW

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
come on CI wake up

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Review by fabrizio-m — APPROVED** [review]

**Pull request merged**
