### PR TITLE
Add Mina_stdlib

### PR DESCRIPTION
**Pull request by mrmr1993**
These functions keep being recreated in PRs against compatible. Lets just import the stdlib.

### CODE REVIEW

**Review by nholland94 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by georgeee** [comment]
@mrmr1993 what about replacing usages of recreated functions introduced by other PRs with this new set, if you have certain PRs ready available in your memory?

**Comment by mrmr1993** [comment]
> what about replacing usages of recreated functions introduced by other PRs with this new set

The one I have in mind hasn't landed yet: https://github.com/MinaProtocol/mina/pull/14889. Nathan tells me that there have been others, but I don't care to find them atm.

**Comment by georgeee** [comment]
Sure, ok

**Pull request merged**
