### PR TITLE
[CI] hardfail on rosetta int tests

### PR DESCRIPTION
**Pull request by dkijania**
After successful maintenance of rosetta integration tests it is time to hard fail on this job

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by Sventimir — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by shimkiv — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
