### PR TITLE
Fix verification key update in develop

### PR DESCRIPTION
**Pull request by dkijania**
Fix nightly for verification key update in nightly for develop. After last commit nightly is happy:

https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2144

Fix was to partially revert incorrect merge from o1js-main: 

https://github.com/MinaProtocol/mina/pull/15594/commits/adf934d28f491d850c9d8e83e35a5857a74f59f6

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
