### PR TITLE
Move the Call_forest module from Zkapp_command to it's own file

### LINKED ISSUE #12576: Isolate the Call_forest module from Zkapp_command

### PR DESCRIPTION
**Pull request by joaosreis**
The `Call_forest` module was moved from `src/lib/mina_base/zkapp_command.ml` to `src/lib/mina_base/zkapp_command_call_forest.ml`. An alias was created in `zkapp_command.ml` with the same name in order to not break any existing code mentioning that module.

The code builds, so it should not have any issues.

Closes #12576

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
PR merge postponed for when the refactors are less disruptive for the ongoing work

**Review by Sventimir — APPROVED** [review]

**Comment by mrmr1993** [comment]
This is both simple enough that it's easy to redo, and stale enough that it isn't worth keeping. Closing.

**Pull request closed without merging**
