### PR TITLE
Fix "Rosetta integration tests" CI job.

### LINKED ISSUE #14028: Fix and improve Rosetta integration test CI script
To test the Rosetta implementation using `rosetta-cli` we need to deploy a network and issue both regular and zkApp transactions. The existing script works by deploying a sandbox network, deploying a zkApp using `zkapp-cli` that generates payments upon interaction, and regularly issuing transactions and interacting with the deployed zkApp, while running the `rosetta-cli` test suite.
Currently, there are some issues with the script, namely:

1. The `snarkyjs` version used by the node and `zkapp-cli` should be the same. Different branches may use different `snarkyjs` versions. It's possible to install `zkapp-cli` with `snarkyjs` pinned to the one present in the repo submodule.
2. If different `snarkyjs` versions are used across branches, the zkApp used to generate zkApp payments possibly needs to have multiple implementations, as there are breaking changes between `snarkyjs` versions.
3. There are some issues on the script and the CI definition currently, but fixes for it are already in [this branch](https://github.com/MinaProtocol/mina/commits/joaosreis/fix-rosetta-int-tests).

### PR DESCRIPTION
**Pull request by Sventimir**
Explain your changes:
* Make the job work again.

Explain how you tested your changes:
* Run the CI.

The intent is to make this job blocking the CI shortly after this is merged.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes #14028

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
