### PR TITLE
Migrate mina_base tests to alcotest

### PR DESCRIPTION
**Pull request by Sventimir**
This is the second of a series of PRs aiming to migrate `mina_base` test to Alcotest.

Explain your changes:
* Migrate remaining inline tests in `mina_base` to Alcotest.
* There are a couple of leftover tests, asserting versions of some types, which are best left as close to the asserted types as possible.
* For this reason, unfortunately, `mina_base` still depends on inline tests PPX.
* Tests are reviewed and migrated to Quickcheck where applicable.
* Some new tests were added as well.

Explain how you tested your changes:
* Run the CI

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- n/a Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* A step towars closing: #13034

### CODE REVIEW

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by Sventimir** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
