### PR TITLE
Handle inability to contact metrics server on forwarding

### LINKED ISSUE #14432: Daemon crash on http request failure
In ITN, we have observed crashes due to http request failures. The current backtrace information does not tell us where this request is made from in the code, but we should not be allowing http errors like this to bubble up as a toplevel exception.

### Originating Backtrace
```
Raised at Cohttp_async__Client.request.(fun) in file "cohttp-async/src/client.ml", line 83, characters 6-13,
Called from Async_kernel__Deferred0.bind.(fun) in file "src/deferred0.ml", line 54, characters 64-69,
Called from Async_kernel__Job_queue.run_job in file "src/job_queue.ml" (inlined), line 128, characters 2-5,
Called from Async_kernel__Job_queue.run_jobs in file "src/job_queue.ml", line 169, characters 6-47
```

### Top Level Exception
```
monitor.ml.Error, Failure, Connection closed by remote host,
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33,
Called from Async_kernel__Deferred1.M.map.(fun) in file "src/deferred1.ml", line 17, characters 40-45,
Called from Async_kernel__Job_queue.run_job in file "src/job_queue.ml" (inlined), line 128, characters 2-5,
Called from Async_kernel__Job_queue.run_jobs in file "src/job_queue.ml", line 169, characters 6-47
```

### PR DESCRIPTION
**Pull request by georgeee**
Explain your changes:
* Handle an error of contacting a metrics server requested by forward URI

Explain how you tested your changes:
* Testing to be done

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes #14432

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Review by rbonichon — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Comment by nholland94** [comment]
@approved-for-mainnet

**Comment by nholland94** [comment]
!approved-for-mainnet

**Pull request merged**
