### PR TITLE
[crypto][snarky][tests] add more tests for pure functions

### PR DESCRIPTION
**Pull request by mimoo**
tests that trigger fixes in https://github.com/o1-labs/snarky/pull/786

Screenshot 2023-02-08 at 2 35 02 PM

### CODE REVIEW

**Comment by mimoo** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
!ci-build-me

**Pull request merged**
