### PR TITLE
Implement generator of private testing experiments

### PR DESCRIPTION
**Pull request by georgeee**
Explain your changes:
* Implement a generator of long-running experiments to be consumed by ITN orchestrator
* Update Orchestrator to support some new commands
* Change behavior of some existing Orchestrator commands
* Update `fund-keys` command of Mina node to use shorter time pauses, to enable better responsiveness on clusters with smaller slot duration

Explain how you tested your changes:
* Ran experiments on a private cluster

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Pull request merged**
