### PR TITLE
Lk86/remove bionic stretch berkeley conflicts

### PR DESCRIPTION
**Pull request by lk86**
Attempt to resolve conflicts between the current compatible changes (+ removal of bionic/stretch support) into berkeley

This also includes merging all of `rampup` back up into berkeley as part of the chain of merges, hence the large diff (I hope 🤞 )

### CODE REVIEW

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Review by stevenplatt — APPROVED** [review]

**Review by mitschabaude — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Comment by stevenplatt** [comment]
!ci-build-me

**Pull request merged**
