### PR TITLE
add delegation verification tool

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
This PR implements the stateless verification tool that would be used to verify that data collected by the uptime service.
It inlines the verifier to optimize computation. It is intended to be run in docker with `gcr.io/o1labs-192920/delegation-verify:1.2.1-mainnet` image. To run it in docker use:
```
docker run --mount type=bind,source=</path/to/submissions/and/blocks/>,target=</a/path/you/choose> 
  gcr.io/o1labs-192920/delegation-verify:1.2.0-mainnet 
  --block-dir </a/path/you/choose>/blocks/ 
  <a/path/you/choose>/submissions/<submission-file-1>
  ...
  <a/path/you/choose>/submissions/<submission-file-n>
```

Update on 2023/11/8, to run this tool, build it with the same profile as your network and then if your network is using `runtime-config` then you also need to pass the same config file to `delegation-verify` program:
```
delegation-verify.exe --block-dir <path/to/blocks/> --config-file <path/to/config-file>
  <path/to/submissions/submission-1>
  ...
  <path/to/submissions/submission-n>
```

### CODE REVIEW

**Review by georgeee — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
@ghost-not-in-the-shell I tested this tool on some submissions from Mina node of `berkeley` branch built with `devnet` profile. Delegation verification tool was also built with `devnet` after (local) merge to `berkeley` branch.

I've got the following log/error:

```
Transaction_snark.system: 47.723s
{"error":"fail to verify the protocol state proof inside the block"}
```

Please try to reproduce it yourself using files from [directory](https://drive.google.com/drive/folders/1D1-APy5fhkWVE7eaQCmkGkXUhmK9X5nM?usp=sharing) and CLI `./delegation_verify.exe --block-dir ./ 2023-09-08T17:35:30Z-B62qqqfipbgvf44sLvxxuLBbC9RQdPQP3cJp4PdisDME1kkTXBjFa7Q.json`.

Tool works well with `--no-checks` flag.

**Comment by georgeee** [comment]
^ _TODO_ @georgeee to confirm version compatibility, maybe it was trouble on my side

**Comment by georgeee** [comment]
Pushed a commit that resolves the issue I brought up in the last comment, now verification of the submission went well

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
We have a version of this in the code. Closing.

**Pull request closed without merging**
