### PR TITLE
update `bs-css` to latest and added peer `bs-css-emotion`

### PR DESCRIPTION
**Pull request by idkjs**
Thank you for contributing to Coda! Please see `CONTRIBUTING.md` if you haven't
yet.

## Explain your changes here.

I updated `bs-css` as it has some breaking )mostly) syntax changes. This way we wont have to run into any issues using this library in the future.

## Explain how you tested your changes here.

I made the required syntax changes then ran the code. I am not sure what the proper way to test this is. Ideas?

### CODE REVIEW

**Comment by idkjs** [comment]
> Thanks for tackling this, looks great. Can you remove the footer changes from this PR?

Done.

**Comment by Schmavery** [comment]
Hmm, for some reason the tests are failing, definitely some problem on our end (your PR should be fine). Will try to resolve it.

**Comment by Schmavery** [comment]
Hey @idkjs, looks like your diff is merge conflicting with an update to one of our packages. Do you mind resolving this, and then we'll bypass the CI bug for now and merge it when you're done :)
Thanks

**Comment by idkjs** [comment]
Not sure hot to do that, boss. Should i reinstall? Or pull the `yarn.lock` from here. New territory. Not even sure how the changes go there.

**Comment by Schmavery** [comment]
If you merge/rebase (with the develop branch) locally and then rerun yarn, it should fix up the merge conflict automatically, I think.

**Comment by idkjs** [comment]
rebase/merge doesnt seem to do anything.

```
~/G/c/f/website ❯❯❯ git rebase origin/develop                                                                       ✘ 128 
Current branch develop is up to date.
~/G/c/f/website ❯❯❯ git merge origin/develop
Already up to date.
~/G/c/f/website ❯❯❯ 
```

I ran `git checkout origin/develop -- frontend/website/yarn.lock`&& `yarn install`. There are still conflicts. Ideas?

**Comment by idkjs** [comment]
I did a fresh branch with the updates here https://github.com/idkjs/coda/tree/update-bs-css. Should I try to pull it?

**Comment by bkase** [comment]
@idkjs is `origin` your clone of your fork? You may need to add another remote for this version of the repo:

`git remote add upstream https://github.com/CodaProtocol/coda.git`

Then `git fetch upstream && git merge upstream/develop`

**Comment by mrmr1993** [comment]
Closing, stale.

**Pull request closed without merging**
