### PR TITLE
Removal of snarky js test from mina

### PR DESCRIPTION
**Pull request by dkijania**
This is one of the step required to fully split snarkyjs and mina repos to preserve healthy dependency relations for both. Test is already implemented in snarkyjs repo where we execute e2e test against real network per push/PR basis, it takes ~10-15 minutes
CI job:  https://github.com/o1-labs/o1js/blob/main/.github/workflows/live-tests.yml
Uses shared actions:  https://github.com/o1-labs/o1js/blob/main/.github/actions/live-tests-shared/action.yml
Sets TEST_TYPE: 'Live integration tests' and USE_CUSTOM_LOCAL_NETWORK: 'true'
And triggers sh run-ci-tests.sh
That in turn executes this test https://github.com/o1-labs/o1js/blob/main/src/examples/zkapps/hello_world/run_live.ts against https://hub.docker.com/r/o1labs/mina-local-network

Quting Serhii, an expert for o1js test architecture:

> Having it and more checks after submodule revert I think it is safe to remove snarkyjs test from test_executive since it anyway does similar (or even the same) thing just from mina repo

https://github.com/MinaProtocol/mina/blob/2d427357911c9896cfe6a2e3ce0b5de827bf6363/src/app/test_executive/snarkyjs.ml#L59
https://github.com/o1-labs/o1js/blob/main/tests/integration/simple-zkapp.js

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by mitschabaude — COMMENTED** [review]
Thanks for doing this, but shouldn't we wait with deleting the old tests until we have new equivalent ones?
In my mind, removing o1js and its test would have been the _last_ task of the submodule refactor

**Comment by mitschabaude** [comment]
Another problem that I have with this PR is that it's only to develop. But `rampup`, `snarkyjs-main` and `berkeley` will need the same changes so starting it here means you can't just merge those upwards

**Comment by dkijania** [comment]
> But rampup, snarkyjs-main and berkeley will need the same changes

I don't think we should do it for berkeley or rampup. Those branches are after code freeze and such change can disrupt further RC

**Comment by dkijania** [comment]
> In my mind, removing o1js and its test would have been the last task of the submodule refactor

Is i understand from Serhii, this test duplicates o1js tests anyhow so we can get rid of it event now

**Comment by mitschabaude** [comment]
> I don't think we should do it for berkeley or rampup. Those branches are after code freeze and such change can disrupt further RC

Moving o1js out of the Mina repo was in large part motivated by making it easier for other teams, in particular protocol, to land changes. So the change _definitely_ has to go into `rampup` and `berkeley`.

> > In my mind, removing o1js and its test would have been the last task of the submodule refactor
> 
> Is i understand from Serhii, this test duplicates o1js tests anyhow so we can get rid of it event now

No, there's no exact equivalent of this test elsewhere currently. o1js tests against a Mina node compiled from either `main`, `berkeley` or `develop` branches. This tests against a Mina node compiled directly from the same branch. So this test here is able to test a change that affects both the Mina node and o1js at the same time, and this aspect is not replicated in any other test.

There are cases where this behaviour is helpful. But they are rare to be honest. So I'm OK with removing the o1js integration test, as long as we don't remove the o1js unit tests yet.

**Comment by dkijania** [comment]
!ci-build-me

**Review by mitschabaude — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
