### PR TITLE
Pickles: more efficient version of challenge_polynomial

### PR DESCRIPTION
**Pull request by rbonichon**
This PR:
- Implements a more efficient version of function `Wrap_verifier.challenge_polynomial`.
   The newly implemented function uses only a single iteration does not allocate an intermediate "square series" array, and make do one fewer closure --- all smallish gains taken independently.
- Add a single unit test to check that the new implementation gives the same result as the old one.

### CODE REVIEW

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
Closing for now; we can revisit for a later hard fork.

**Pull request closed without merging**
