### PR TITLE
snarkyjs assertion long forms

### PR DESCRIPTION
**Pull request by Trivo25**
companion of https://github.com/o1-labs/snarkyjs/pull/681

### CODE REVIEW

**Comment by Trivo25** [comment]
!ci-build-me

**Comment by Trivo25** [comment]
!ci-build-me

**Comment by Trivo25** [comment]
!ci-build-me

**Review by MartinMinkov — APPROVED** [review]

**Review by mitschabaude — CHANGES_REQUESTED** [review]
This is missing the assertBool change

**Comment by Trivo25** [comment]
> This is missing the assertBool change

Ohhh very good catch!

**Review by mitschabaude — APPROVED** [review]

**Review by mrmr1993 — APPROVED** [review]

**Comment by Trivo25** [comment]
!ci-build-me

**Pull request merged**
