### PR TITLE
Export legacy poseidon params for mina-signer

### PR DESCRIPTION
**Pull request by mitschabaude**
Companion of https://github.com/o1-labs/snarkyjs/pull/660

Supports legacy signatures by generating legacy Poseidon parameters from OCaml

### CODE REVIEW

**Review by Trivo25 — APPROVED** [review]

**Review by deepthiskumar — APPROVED** [review]

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Pull request merged**
