### PR TITLE
Reset feature flags before assertion

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR changes the handling of `feature_flags` in Pickles for wrap circuits. Previously, we were propagating the flags from the step circuit, which could cause a sanity-check assertion to fail when we convert the 'full' set of values back to the 'wrap only' set of values. This PR fixes that by always resetting the flags before entering that conversion.

This PR does not change any circuits, protocol constants, etc.; the behavior is only changed when those offending flags are set. As such, this can be deployed to snark workers as a compatible bugfix version.

Tests to follow.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by rbonichon — APPROVED** [review]
LGTM

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
Merging through `versioned-type-linter`; it's broken whenever the tip of `rampup` is a PR that didn't change the daemon code :(

**Pull request merged**
