### PR TITLE
[rampup] Fixup compilation error

### PR DESCRIPTION
**Pull request by mrmr1993**

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1143#_
Rosetta builds have been failing. #14920 to port changes from berkeley

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Review by deepthiskumar — APPROVED** [review]

**Pull request merged**
