### PR TITLE
Lints for system proofs commit ancestor

### PR DESCRIPTION
**Pull request by dkijania**
Explain your changes:
Added new job to CI for checking if current commit in `src/lib/crypto/proof-system` submodule is ancestor of particular branch. As already discussed, we need that kind of verification for all major mina branches (compatible/berkeley/develop/izmir). Due to the problems with merging back changes between mentioned branches ,@mrmr1993 have this idea that it's better to commit the same script everywhere and control it by base branch variable from buildkite. Thanks to than we don't need to have painful merging back changes between develop/berkeley/compatible.

Explain how you tested your changes:

By running CI

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
