### PR TITLE
porting more multi jobs dev

### PR DESCRIPTION
**Pull request by dkijania**
porting https://github.com/MinaProtocol/mina/pull/16296 to develop

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-nightly-me

**Pull request merged**
