### PR TITLE
Merge berkeley into rampup

### PR DESCRIPTION
**Pull request by psteckler**
There was one conflict, the timestamp on the berkeley genesis ledger. The later timestamp from the `rampup` branch was chosen.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
@deepthiskumar did you want to also approve the PR (or just merge it)?

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/595

**Pull request merged**
