### PR TITLE
prevent more restarts when is_seed

### PR DESCRIPTION
**Pull request by emberian**
Port of https://github.com/MinaProtocol/mina/pull/15060 to compatible

https://github.com/MinaProtocol/mina/pull/15131
https://github.com/MinaProtocol/mina/pull/15130

### CODE REVIEW

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
