### PR TITLE
Add generic gate gadgets and generic sub

### LINKED ISSUE #13001: Make generic snarky gadgets helpers instead of examples and add generic sub gadget
During subsequent work we found these would be very useful for simplifying code, making it less error prone, cleaner and easier to read.

### PR DESCRIPTION
**Pull request by jspada**
Closes #13001

### CODE REVIEW

**Comment by jspada** [comment]
!ci-build-me

**Comment by jspada** [comment]
!ci-build-me

**Comment by jspada** [comment]
!ci-build-me

**Review by querolita — APPROVED** [review]
Oh nice, let's remember to add the one that allows to set a different output coefficient for the future.

**Comment by jspada** [comment]
merged to `feature/snarky-foreign-field-add-gadget` branch

**Pull request closed without merging**
