### PR TITLE
12068 - Add libjemalloc libprocps libprocps dependencies for Bullseye and Bionic

### PR DESCRIPTION
**Pull request by kaozenn**

### CODE REVIEW

**Comment by kaozenn** [comment]
!ci-build-me

**Review by simisimis — APPROVED** [review]
Lgtm

**Comment by kaozenn** [comment]
!ci-build-me

**Review by lk86 — APPROVED** [review]

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by kaozenn** [comment]
!ci-build-me

**Pull request merged**
