### PR TITLE
Fixup lookup gate with range-check table

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR is part of the fix for https://github.com/o1-labs/o1js/issues/1374, against the `o1js-main` branch, via https://github.com/o1-labs/proof-systems/pull/2054. The added test exercises this behaviour, and only passes after the fix to proof-systems is applied.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
A unit test which seems to compare a hard-coded circuit digest is failing

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by querolita — APPROVED** [review]

**Review by emberian — APPROVED** [review]

**Pull request merged**
