### PR TITLE
Populate ledger with `set_batch_accounts`

### LINKED ISSUE #13072: Loading the genesis ledger from daemon config

### PR DESCRIPTION
**Pull request by psteckler**
Use `set_batch_accounts` instead of `create_new_account` when populating the ledger from a config file.

Using a ledger derived from the current mainnet staking ledger, with about 160k accounts, the time to populate the ledger is reduced from 336 seconds to 84 seconds, a 75% reduction.

Verified that the ledger Merkle root is the same as when using the existing implementation.

Closes #13072.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
