### PR TITLE
Retire 'medium curves' configuration now that there are no other options

### PR DESCRIPTION
**Pull request by mrmr1993**

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by SanabriaRusso — COMMENTED** [review]
I wonder why infra-code-reviewer is called for this PR 🤔

**Review by SanabriaRusso — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request closed without merging**
