### PR TITLE
Increase coverage for masks

### LINKED ISSUE #14669: Unit test coverage for masks
1. Analyze the coverage
2. Determine the missing tests

### PR DESCRIPTION
**Pull request by rbonichon**
Fix #14669.

The initial coverage for the branch is:
| % | Lines covered | File 
| ---      | ---       |---
 | 35.83      | 67/187    | `src/lib/merkle_mask/maskable_merkle_tree.ml`
 | 51.55     | 266/516    | `src/lib/merkle_mask/masking_merkle_tree.ml`

Current state is:

| %  | Lines covered   | File                                        |
|------------|---------|---------------------------------------------|
|      83.81 | 88/105  | `src/lib/merkle_mask/maskable_merkle_tree.ml` |
|      78.87 | 377/478 | `src/lib/merkle_mask/masking_merkle_tree.ml`  |

The increase in coverage is thus partly due to marking large portion of the code with `[@coverage off]` tags. I tried to do that rationally. 

What remains to be done
- [x] Cleaning up the branch history
- [x] Cleaner more principled extra tests

### CODE REVIEW

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]
Looks good! The coverage offs look reasonable to me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Pull request closed without merging**
