### PR TITLE
Bump `core_bench` to 0.17.0

### PR DESCRIPTION
**Pull request by georgeee**
Motivation: `core_bench `supports machine-readable csv output starting from version 0.17.0. This is a useful feature for the effort to (re-)organize our benchmarks.

This branch also includes a number of small fixes required for toolchain CI pipeline (which is now broken in `compatible`).

Explain how you tested your changes:
* [ ] Toolchain dockers compile
* [x] `nix develop .?submodules=1` succeeds

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
This was a failed attempt, closing

**Pull request closed without merging**
