### PR TITLE
Remove aws

### PR DESCRIPTION
**Pull request by QuiteStochastic**

### CODE REVIEW

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]
LGTM. Can we just remove the old code instead of commenting it? It will be easy enough to pull this back out of history, and I doubt we will need it again in the future.

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by lk86 — APPROVED** [review]

**Pull request merged**
