### PR TITLE
Add support for 2-pass ledgers in the application logic

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR injects the second-pass ledger at the end of the fee-payer's segment, to ensure that it's ready and waiting for the remaining account updates in a zkApp command.

This ensures that the relationship between the initial `global_state.second_pass_ledger` and the `local_state.ledger` is asserted in the snark.

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Pull request merged**
