### PR TITLE
Stop generating dummy_values.ml

### PR DESCRIPTION
**Pull request by martyall**
current `gen_values.exe` benchmark: `0.44584274291992188ms`

### CODE REVIEW

**Comment by martyall** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Review by georgeee — APPROVED** [review]

**Comment by martyall** [comment]
@mrmr1993 Do you know why the unit tests are failing here?

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Pull request merged**
