### PR TITLE
[Rosetta] Refactor indexer SQL queries

### PR DESCRIPTION
**Pull request by joaosreis**
This pull request refactors SQL queries to improve the efficiency and readability of the indexer queries and provide logging for debugging purposes.

This was tested using the Rosetta indexer test against current mainnet archive database.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
Fixes #15782

**Comment by joaosreis** [comment]
!ci-build-me

**Review by ejMina226 — APPROVED** [review]

**Comment by joaosreis** [comment]
!ci-build-me

**Pull request merged**
