### PR TITLE
Nix: rework documentation

### LINKED ISSUE #10003: Work on improving the documentation for building and deploying Mina

### PR DESCRIPTION
**Pull request by balsoft**
(hopefully) Improve the Nix documentation for both beginners and advanced Nix users. Feedback welcome.

Rendered doc: https://github.com/MinaProtocol/mina/blob/update-nix-readme/nix/README.md

Closes #10003

### CODE REVIEW

**Review by bryanhonof — COMMENTED** [review]
Overall I think it's okay. Do you think we should try and make it more concise? Currently I find it a pretty long read, but perhaps that's the way it should be.

**Comment by balsoft** [comment]
If you have any ideas on how to make it more concise without removing useful things, you can commit it straight to this branch :)

**Comment by balsoft** [comment]
@kaozenn Why?

**Comment by kaozenn** [comment]
My bad 
[@balsoft](https://minafoundation.slack.com/team/U02K3DKF09M)
. I created a branch with the exact same name to [update the nix documentation](https://github.com/MinaProtocol/mina/pull/12016) without realising there was already one existing.

I recreated the branch and this PR

https://github.com/MinaProtocol/mina/pull/12018

**Pull request closed without merging**
