### PR TITLE
replacing berkeley usage in CI with devnet in compatible

### PR DESCRIPTION
**Pull request by svv232**
mirrors #15928

### CODE REVIEW

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by georgeee** [comment]
Single node tests are failing because the `snark-keys.o1test.net` is used:

```
https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/epoch_ledger_3e2c138e3e014dcb66f5dcfbfd42e1c8cbbac7aeb5bbf90ed62907b91075a9f5.tar.gz
```

**Comment by georgeee** [comment]
I don't think it's related to this PR

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
I don't see where @MinaProtocol/crypto-eng-reviewers approval is required. @svv232?

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by Trivo25 — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Pull request merged**
