### PR TITLE
[compatible] Add network_id to the devnet and mainnet config files

### PR DESCRIPTION
**Pull request by mrmr1993**
This is #15954 against compatible.

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Review by georgeee — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by dkijania** [comment]
I think this PR is not needed anymore since we merged release/3.0.1 already to compatible

**Pull request closed without merging**
