### PR TITLE
Merge 13620 to develop (again)

### PR DESCRIPTION
**Pull request by psteckler**
There were some changes to 13620 after the original merge PR, so there's still a merge conflict reported.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Pull request merged**
