### PR TITLE
Fix/fuzzy zkapp tests timeout

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR adds timeout to zkapp fuzzy tests. This intends to reduce the probability of certain tests to timeout.

Explain how you tested your changes:
I ran with the same config in CI on my laptop, overall duration of the test is 1h and timeout for individual tests is 150s

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by psteckler — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
Approving since the changes are in tests and made to fix CI test flakes

**Pull request merged**
