### PR TITLE
Add  dedicated module for `Opt` type

### LINKED ISSUE #13947: Isolate the `Opt` module inside its own file

### PR DESCRIPTION
**Pull request by rbonichon**
This adds an isolated dedicated module to develop the `Opt` type used in circuits.

Fix #13947

### CODE REVIEW

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Review by dannywillems — APPROVED** [review]
Very good documentation! I love it.

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Pull request merged**
