### PR TITLE
use random_oracle.legacy.salt for receipt_chain_hash.empty

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR change `Receipt.Chain_hash.empty` to use the legacy salt function to match the behavior on mainnet;
This PR also adds a script that compares the ledgers from the replayer's checkpoint file with the ledger inside the fork_config.

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
