### PR TITLE
Arkworks 0.4.2: fix test vectors serialization issue

### PR DESCRIPTION
**Pull request by volhovm**
A pair PR for https://github.com/o1-labs/proof-systems/pull/2594.

This merely bumps the version of `proof-systems` to the last `develop` containing the PR above.

### CODE REVIEW

**Comment by volhovm** [comment]
!ci-build-me

**Review by dannywillems — APPROVED** [review]
LGTM

**Comment by dannywillems** [comment]
!ci-build-;e

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-nightly-me

**Pull request merged**
