### PR TITLE
Consider timed balance in the transaction pool

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR uses the timed balance instead of the maximum balance when considering whether transactions are valid to include in the pool.

This likely would have prevented the issue that stalled the current testnet.

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Review by lk86 — APPROVED** [review]

**Review by bkase — APPROVED** [review]
🥳

**Comment by es92** [comment]
Is this missing some code being pushed? Getting
```
File "src/lib/network_pool/transaction_pool.ml", line 329, characters 13-39:
Error: Unbound value Currency.Amount.of_balance
```

**Comment by mrmr1993** [comment]
@es92 yea, sorry. Can you try again now?

**Comment by es92** [comment]
Fast! That ones working now, still getting a 
```
File "src/lib/network_pool/transaction_pool.ml", line 328, characters 10-242:
Error: This expression has type Currency.Balance.t option
       but an expression was expected of type Currency.Balance.t
```

**Comment by es92** [comment]
Ah I think you just pushed that, trying now..

**Comment by es92** [comment]
Success! Thanks so much!

**Pull request merged**
