### PR TITLE
[develop] expose lookup verifier index

### PR DESCRIPTION
**Pull request by dannywillems**
Proof-systems: https://github.com/o1-labs/proof-systems/pull/1182
snarkyjs-bindings: https://github.com/o1-labs/snarkyjs-bindings/pull/114
snarkyjs: https://github.com/o1-labs/snarkyjs/pull/1076

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
Squashed commits for a cleaner history.

**Pull request merged**
