### PR TITLE
Remove old version linter (develop)

### PR DESCRIPTION
**Pull request by psteckler**
Same changes as in #14203 (cherry-picked commits from there), against `develop`. When this is merged, should allow the merge-to-develop CI task to succeed there.

### CODE REVIEW

**Review by dkijania — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]
I'm not sure that cherry-picking was what we need to satisfy CI. I'd rather consider merging the other branch onto `origin/develop`.

**Comment by psteckler** [comment]
> I'm not sure that cherry-picking was what we need to satisfy CI. 

The reported conflict is in `version-linter.py`, which was modified in the other PR branch.

**Comment by psteckler** [comment]
!ci-build-me

**Pull request merged**
