### PR TITLE
Mainnet Infra

### PR DESCRIPTION
**Pull request by es92**

### CODE REVIEW

**Comment by lk86** [comment]
also update the archive schema to https://raw.githubusercontent.com/MinaProtocol/mina/06691e343be1ddad036c1fc4a6c94afc12afc4ee/src/app/archive/create_scheama.sql to be safe and consistent

**Comment by lk86** [comment]
can you move it to coda-infra-east instead of east4? I don't want it on the same cluster as devnet2 and coda-infra-east has more nodes availible

**Review by lk86 — APPROVED** [review]

**Review by bkase — APPROVED** [review]

**Comment by es92** [comment]
!approved-for-mainnet

**Comment by es92** [comment]
!approved-for-mainnet

**Comment by es92** [comment]
!approved-for-mainnet

**Pull request merged**
