### PR TITLE
Fix/archive client decouple

### PR DESCRIPTION
**Pull request by emberian**
A different approach as mentioned in #14728

### CODE REVIEW

**Comment by emberian** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Review by deepthiskumar — DISMISSED** [review]
Waiting for rampup8 release to land this

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!approved-for-mainnet

**Comment by georgeee** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!approved-for-mainnet

**Pull request merged**
