### PR TITLE
Fix premature stops of Orchestrator

### LINKED ISSUE #13957: Experiment fails if discovery found no nodes
```
2023-08-24T14:34:10.453Z        INFO    itn orchestrator        itn_orchestrator/main.go:233    Performing step wait (47)
Starting round 4, 240 min since start
2023-08-24T15:03:59.455Z        INFO    itn orchestrator        itn_orchestrator/main.go:233    Performing step discovery (48)
2023-08-24T15:03:59.704Z        INFO    itn orchestrator        itn_orchestrator/main.go:233    Performing step load-keys (49)
2023-08-24T15:06:34.383Z        ERROR   itn orchestrator        itn_orchestrator/main.go:215    Error resolving params for step 50: couldn't find output participant (step 48, file "") needed for step 50
```

### PR DESCRIPTION
**Pull request by georgeee**
Problem: Orchestrator gets stopped if it can't reach a node for executing stop-daemon command or if it can't find any participants.

Solution: don't treat no-reply on stop-daemon as an error and repeat discovery in the loop to prevent stopping an experiment because of glitches.

Explain how you tested your changes:

* Orchestrator/generator were tested as part of a cluster experiment
* To be tested on cluster by repeatedly running experiments and seeing Orchestrator is not stopped prematurely (over the following weeks, condition that caused the issue #13957 was infrequent)

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes #13957

### CODE REVIEW

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by georgeee** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
