### PR TITLE
Fix Lagrange basis performance regression

### PR DESCRIPTION
**Pull request by mitschabaude**
closes https://github.com/o1-labs/o1js/issues/1869

see also https://github.com/MinaProtocol/mina/pull/16207/files/2216f1e9624a5b60ef542d6ef288d779db7ad42e#r1806171481

### CODE REVIEW

**Comment by 45930** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Review by volhovm — APPROVED** [review]
Looks good. To summarise my understanding: the `_maybe_` functions now properly return `None` when there are no LB in them, which is desirable because on o1js side this code is called in a single-threaded mode, so computing the bases would be undesirably expensive.

**Review by querolita — APPROVED** [review]

**Pull request merged**
