### PR TITLE
Use posix-style flags by default

### PR DESCRIPTION
**Pull request by mrmr1993**
This converts all our non-POSIX-compliant flags to POSIX-compliant ones. The original forms are preserved as aliases, so all our scripts etc. should still work.

This also fixes a flag where the default argument was part of the name 🤦‍♂️ 

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Review by lk86 — CHANGES_REQUESTED** [review]
Can you also update the flags we use in helm? it won't cover 100% of our use cases in infra but it covers enough that its worth doing now: https://github.com/MinaProtocol/mina/blob/develop/helm/block-producer/templates/block-producer.yaml#L174
Check for "args" in the templates in each chart, then get @AryehAlexander or @0x0I  to assist on properly versioning and releasing the charts.

**Comment by mrmr1993** [comment]
> Can you also update the flags we use in helm?

Someone else will need to pick that up, I'm working on other things. This was just easy to automate.

The current flags will still work, so I propose doing it as separate PRs anyway.

**Comment by deepthiskumar** [comment]
Change `-help` and `-version`? 
Also, another task similar to the infra task mentioned above would be to update flags in the tests ( command_line_test.ml, for example)

**Review by lk86 — APPROVED** [review]

**Comment by aneesharaines** [comment]
!approved-for-mainnet

**Review by deepthiskumar — APPROVED** [review]

**Pull request merged**
