### PR TITLE
Monomorphise `Account.t`

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR is an experiment in monomorphising the `Account.t` type without creating a new `bin_prot` version.

This branch was able to successfully sync to devnet, which means that this monomorphisation is indeed safe. This lays the groundwork for doing the same in the pickles library, to remove a lot of the complexity there.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by psteckler** [comment]
Have you manually checked the shapes of the changed types (I don't see the call to the CI linter)?

**Comment by mrmr1993** [comment]
> Have you manually checked the shapes of the changed types

I checked that bootstrap works, which means that the old and new versions of the types are compatible.

**Comment by psteckler** [comment]
> I checked that bootstrap works, which means that the old and new versions of the types are compatible.

I saw that, but it would be nice to have the assurance that the serializations are the same. Maybe I'll look at that. IIRC, the `Poly` doesn't introduce any extra bits, once we got rid of the version bytes (except for the all-tagged or top-tagged types).

**Comment by psteckler** [comment]
I built from `compatible` and this PR branch, and the type shapes and their hashes are the same. Probably it's just me, but I find that direct evidence a bit more reassuring.

Incidentally, to build on Linux Mint 22, which is based on Ubuntu 24.04, and which uses gcc 13.2, I had to sprinkle `#include <cstdint>` in a few places in the rocksdb sources.

**Review by georgeee — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
