### PR TITLE
New CI jobs for dhall (format,syntax,lint)

### PR DESCRIPTION
**Pull request by dkijania**
Added new jobs for lint/format/syntax for Dhall. I used Makefile approach so one can locally run CI jobs. I ran format and lint through all *.dhall files

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
