### PR TITLE
[PLACEHOLDER] Build for internal hard-fork testing (SOFT FORK FOR STOP SLOT)

### PR DESCRIPTION
**Pull request by mrmr1993**

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
Nightly- https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1358

**Comment by deepthiskumar** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1387

**Comment by mrmr1993** [comment]
Internal testing has finished, closing.

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Pull request closed without merging**
