### PR TITLE
feat: fix scripts to use different paths if mina is a submodule of o1js

### PR DESCRIPTION
**Pull request by MartinMinkov**
Explain your changes:
Fixes some of the scripts called by dune to use different absolute paths if we are building mina in the context of the o1js as mina being a submodule.

The issue occurs when we build o1js from the root directory with mina as a submodule. Dune will try to resolve some absolute paths from build scripts that will fail and not build o1js properly. To fix this, we conditionally check for submodule locations and change the paths if we have a mina submodule present, otherwise, we use the same build process. This lets us build mina the same way but also build o1js dependencies properly.

Explain how you tested your changes:
Built mina from the root directory to test normal building and built o1js using mina as a submodule successfully.

Addresses https://github.com/o1-labs/o1js/issues/1096

### CODE REVIEW

**Comment by MartinMinkov** [comment]
!ci-build-me

**Review by querolita — APPROVED** [review]

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by MartinMinkov** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
