### PR TITLE
Enable Rosetta to connect to custom networks

### LINKED ISSUE #14931: Mina Rosetta Docker image can only connect to Mainnet / Berkeley or DevNet
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

This is an improvement to the current Mina Rosetta Docker Start script.
Currently the Mina Rosetta docker image can only connect to Miannet, Berkeley or DevNet
As we need Rosetta to get tested against Testworld 2-0, QANet, we need the ability to update some variables as we run the docker image. Some of the variables are currently hardcoded and it is not possible to overwrite them at runtime.

### Steps to Reproduce

1. Try to connect Rosetta to Testworld 2-0 or any other custom Network
...

### Expected Result

By passing environment variables we should be able to connect Rosetta Docker image to any Network, not only Mainnet, DevNet or Berkeley

### Actual Result

The docker image would fail because some of the variables such as `MINA_CONFIG_FILE` expect mainnet, devnet, or berkeley only

### Daemon version

56fa1dbcc36aa638c84cdc624adc407075a088a2

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
This is not relevant as there are no issue with the daemon
I am testing the changes against Rampup8
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kaozenn**
---

Explain your changes:
* This changes add te possibility to pull the SQL Dump, Genesis ledger and precomputed blocks from custom URLs
* As a consequence, it allows Rosetta to connect to custom network other that Mainnet, Berkeley or DevNet.
* There are no breaking changes

Explain how you tested your changes:
* I have built the images an managed to connect Rosetta to Testworld 2-0 minafoundation/mina-rosetta:2.0.0rampup8-56fa1db-focal

Checklist:

- [x] Dependency versions are unchanged
- [x] Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
- [x] Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
- [x] Document test purpose, significance of failures
- [x] Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes #14931

### CODE REVIEW

**Comment by kaozenn** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Review by simisimis — APPROVED** [review]
looks good!

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1168#_

**Comment by deepthiskumar** [comment]
Rosetta build are failing due to the following
```
[ERROR] The sources of the following couldn't be obtained, aborting:
--
  | - ocamlgraph.1.8.8: curl error code 404

```
and so the tests are not triggered. @stevenplatt is working on fixing it

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
