### PR TITLE
[Berk] Port Replayer: convert global slots to avoid to hashes in order to support devnet

### PR DESCRIPTION
**Pull request by dkijania**
Porting to berkeley https://github.com/MinaProtocol/mina/pull/15302

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by mrmr1993 — APPROVED** [review]

**Comment by nholland94** [comment]
!approved-for-mainnet

**Pull request merged**
