### PR TITLE
Rename sequence_state to action_state

### LINKED ISSUE #12633: Remove "sequenceEvents" from GraphQL's "account"/"accounts" query schema
Internal Slack discussion is [here](https://o1-labs.slack.com/archives/C02ASV6BZCY/p1675953416808679)

### LINKED ISSUE #12693: Rename sequence_state to action_state
Old name was derived from `sequence_events`, which is now `actions`

### PR DESCRIPTION
**Pull request by psteckler**
Rename `sequence_state` to `action_state`. The old name was derived from `sequence_events`, which was changed to `actions`.  Also rename `last_sequence_slot` to `last_action_slot`.

The salt phrases for `Zkapp_account.Actions` are also renamed.

@mitschabaude made the corresponding changes to SnarkyJS.

Closes #12693.
Fixes #12633

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by mitschabaude — APPROVED** [review]

**Review by deepthiskumar — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Pull request merged**
