### PR TITLE
Add suffix to docker version if we are building instrumented dockers

### PR DESCRIPTION
**Pull request by dkijania**
We are not distinguishing instrumented docker in CI. This PR is adding `-instrumented` suffix to a daemon and archive docker

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by georgeee** [comment]
@dkijania could you add info on how was this change tested? In particular, I'm interested in confirmations:

* [ ] No suffix is added for non-instrumented builds (like before)
* [ ] Suffix is correctly added for instrumented builds

**Comment by dkijania** [comment]
@georgeee Apologies for not providing this information earlier. I tested instrumented dockers manually by:

1. pulling instrumented image:
 `docker pull gcr.io/o1labs-192920/mina-daemon:785dbcf-bullseye-berkeley-instrumented`
2. executing bash interactively: 
`docker run -it --entrypoint bash gcr.io/o1labs-192920/mina-daemon:785dbcf-bullseye-berkeley-instrumented`
3. executing some command to trigger coverage files dump:
`mina internal `
4. examining working dir:
`ls *.coverage`

The same test for non-instrumented dockers but effect should be no coverage files. I performed such test for all combination of dockers for daemon and archive node

**Comment by dkijania** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
