### PR TITLE
Remove duplicated build for Lucy in CI

### PR DESCRIPTION
**Pull request by dkijania**
In our CI pipeline we are building test executive twice. First time in build-artifacts.sh script which is launched per every codename (Bullseye/Focal/Buster) and publishing to our debian repo. Second, in separate job for test executive build which puts exe on s3 storage which then is taken by execute tests jobs. My change was to rely in test execute job on deb package rather than cached binary from s3

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
Nightly pipeline result : https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/572

**Review by shimkiv — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
