### PR TITLE
Accurate heap usage bytes

### PR DESCRIPTION
**Pull request by psteckler**
The heap usage app was reporting the number of bits used by data structure as the number of bytes. 

Also, unbox a couple of types.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
