### PR TITLE
Refactor zkapp generators

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR cleans up zkapp_command_generators a little bit. Instead of using a bunch of optional argument, I created a record that collects those and make it an argument to the generator function.

Explain how you tested your changes:
*

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Review by psteckler — APPROVED** [review]

**Review by mrmr1993 — CHANGES_REQUESTED** [review]
LGTM, but please revert the changes to the crypto submodules

**Comment by ghost-not-in-the-shell** [comment]
> LGTM, but please revert the changes to the crypto submodules

Sure.

**Review by mrmr1993 — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by MartinMinkov — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Pull request closed without merging**
