### PR TITLE
[CI] Limit fuzzy and unit jobs retry [berk]

### PR DESCRIPTION
**Pull request by dkijania**
Explain your changes:
~~Expose parameter for setting retry limit for flaky test (exit code = +1). Then use this parameter in fuzzy zkapp tests. This will help us limit duration of nightly tests from 10h to 2h. I didn't touch other exit codes, so it should allow to retry for other reasons of build failure~~

After discussion with @stevenplatt i changed PR to remove retry within a job. Reason behind it, is that buildkite should be the only controlling mechanism of test retry 

Explain how you tested your changes:
run nightly job and observed failing zkapp unit tests are not rerun if tests fails

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by Trivo25 — APPROVED** [review]

**Review by shimkiv — APPROVED** [review]
LGTM

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
This was based on discussion with Steven. Buildkite infrastructure should be the only mechanism that can retry jobs as this will lead to unified approach in retry strategy across  all CI job. This way we can show/prove reliability of particular jobs and provide metrics.

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
> why do we not want retries for dev unit tests anymore? This was added to retry any flaking test without a rebuild.

To Deepthi's point: I believe the `mina_net2` test is still flaky. I would prefer that we spend a small amount of time (in)validating that before landing this. If this is going to result in e.g. > 5% of unit test runs flaking, we're effectively blocking a developer for 1h a day (assuming 20 PRs / day) for purely ideological reasons.

**Pull request closed without merging**
