### PR TITLE
Libp2pbitswap ci timeout

### PR DESCRIPTION
**Pull request by QuiteStochastic**
minor change, just changing to a slightly sooner timeout

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by stevenplatt — APPROVED** [review]

**Pull request merged**
