### PR TITLE
Fix `to_input` for protocol constants so that all fields are included

### LINKED ISSUE #15085: Fix protocol constants
https://github.com/MinaProtocol/mina/pull/14776#issuecomment-1939536688 pointed out that the protocol constants `to_input` function is missing the `grace_period_slots` field that was added in that PR. We should fix this. Luckily, this issue doesn't introduce a vulnerability in the snark from my understanding, but would cause the circuit to fail to compile if we were ever requesting the protocol constants as a private input.

### PR DESCRIPTION
**Pull request by mrmr1993**
Fixes #15085.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by nholland94** [comment]
@mrmr1993 Can you do me a favor and make the other functions in the file use destructuring as well? I was applying that change locally but had to switch off onto the hardfork stuff.

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
