### PR TITLE
[Merge Conflict Fix] port 'Remove migration apps and jobs from master' to compatible

### PR DESCRIPTION
**Pull request by dkijania**
This is autogenerated Pull Request for porting #15793 to compatible

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Review by svv232 — APPROVED** [review]

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
