### PR TITLE
Constructors for global slot types (develop)

### PR DESCRIPTION
**Pull request by psteckler**
Same as #13143 for `develop`.

Also: removed client SDK, which was already removed in Berkeley.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Review by mitschabaude — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by lk86 — APPROVED** [review]

**Comment by jdsteinhauser** [comment]
I'm seeing a couple of comments akin to:
```
(* we're in the genesis "hard fork", so consider current slot as since-genesis *)
```
Is this choice documented somewhere other than in comments?

**Comment by psteckler** [comment]
> Is this choice documented somewhere other than in comments?

A good place to describe the choice would be near the field `Genesis_constants.Constraint_constants.fork`, to indicate that `None` means we're on the original chain, and `Some` means we're in a subsequent hard fork.

Can you create an issue for that?

**Review by jdsteinhauser — APPROVED** [review]
Opening an issue to document the genesis slot pre-/post-hard fork slot #. Otherwise, looks good to me! :shipit:

**Review by fabrizio-m — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
#13143 no longer has a merge-to-develop failure, so this PR is unneeded

**Pull request closed without merging**
