### PR TITLE
Privileged GraphQL removal

### PR DESCRIPTION
**Pull request by ejMina226**
Remove the authenticated GraphQL endpoints. I started at the graphql and then had to work out removing other types so the code would compile.

### CODE REVIEW

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
!ci-build-me

**Review by deepthiskumar — CHANGES_REQUESTED** [review]
Why are we removing the feature itself? i believe the intention was to make sure they are removed from mainnet builds. I believe it already does that since it is behind a flag that's defined at compile time. And it is set to false in mainnet.mlh. Could you maybe just confirm that they are disabled?

This is an important feature that we want to continue having for future testnets and also private qa-nets for regression testing

**Comment by ejMina226** [comment]
This PR is no longer needed.

**Pull request closed without merging**
