### PR TITLE
Use mina toolchain instead of ci-toolchain-base

### PR DESCRIPTION
**Pull request by dkijania**
We are experiencing issues on merges jobs in CI. This PR is an attempt to fix this situation. We will use toolchain with git-lfs

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
Hello, @dkijania 2 new  created to help you port this change to master. Please follow steps to resolve conflict for each mainline branch. PRs will be created automatically after you push merge to porting branches

  
## compatible 

```
git fetch && git checkout port/_ci/use_mina_toolchain_for_merge_jobs_to_compatible && git merge ci/use_mina_toolchain_for_merge_jobs
```

Resolve conflict and then 

```
git push
```  
    
  
## develop 

```
git fetch && git checkout port/_ci/use_mina_toolchain_for_merge_jobs_to_develop && git merge ci/use_mina_toolchain_for_merge_jobs
```

Resolve conflict and then 

```
git push
```

**Comment by dkijania** [comment]
Porting branch #15795 to resolve conflict with compatible created. Please merge it in order to solve conflict between head of this PR and compatible

**Comment by dkijania** [comment]
Porting branch #15796 to resolve conflict with develop created. Please merge it in order to solve conflict between head of this PR and develop

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
I will hold with merging this one as looks like disable smugding in CI solves issue

**Pull request closed without merging**
