### PR TITLE
[CI] add default branch for references and more desc for version linter

### PR DESCRIPTION
**Pull request by dkijania**
Version linter is one of the most fragile test in our CI suite. It often fails is run directly from buildkite or if there is a missing reference file. This PR solves first issue by having a default branch to check if BUILDKITE_BASE_BRANCH is missing. For another problem I've added a description how to upload particular reference file. This is temporary fix until we will implement generating it in a fly

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by svv232 — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
