### PR TITLE
Rosetta: fix transaction_exists sql query

### PR DESCRIPTION
**Pull request by ylecornec**
This PR fixes the SQL query used in the `/construction/submit/` query.

### CODE REVIEW

**Comment by ylecornec** [comment]
!ci-build-me

**Comment by ylecornec** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
Does this code work? It seems wrong, because the SQL onlyn fetches 1 column, but in the record you've got 5 fields…

BTW: I don't really like the fact that we store Mina as strings. Could we perhaps migrate the database to have them encoded as integers? That would be something to do in a separate PR of course.

**Comment by ylecornec** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
Thank you for the type name change. It was confusing indeed.

As for storage,  the [PostgreSQL documentation](https://www.postgresql.org/docs/current/datatype-numeric.html) says there are `numeric` and `decimal` types with arbitrary precision, which I think could be used, no?

**Review by Sventimir — APPROVED** [review]

**Pull request merged**
