### PR TITLE
allow to run connect to mainnet on release branches

### LINKED ISSUE #13366: Connect to mainnet check in compatible PRs

### PR DESCRIPTION
**Pull request by dkijania**
Explain your changes:

Add or maintain connect to mainnet test on compatible branch

Explain how you tested your changes:

Running CI and observing results

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #13366

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!-ci-build-me

**Review by deepthiskumar — APPROVED** [review]
Nice!

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
> !-ci-build-me

no hyphen after `!` and before `ci`

**Review by shimkiv — APPROVED** [review]

**Pull request merged**
