### PR TITLE
Downgrade bisect_ppx

### PR DESCRIPTION
**Pull request by joaosreis**
Version 2.8.1 of `bisect_ppx` has an [issue](https://github.com/aantron/bisect_ppx/issues/409) that results in a HTML report with missing coverages. This PR downgrades its version to 2.7.1.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by nholland94** [comment]
The issue has been closed and a new patch version was released https://github.com/aantron/bisect_ppx/issues/409. Can we upgrade to the `2.8.2` instead?

**Comment by joaosreis** [comment]
I will test if the problem is fixed in this new version and change the PR to update it if that's the case.

**Comment by joaosreis** [comment]
Unfortunately, upgrading `bisect_ppx` requires a series of package version bumps that break the code (it boils down to upgrading janestreet libs, which have breaking changes), so it's a rather intrusive change.

**Comment by mrmr1993** [comment]
The underlying issue here seems to have been resolved. Closing.

**Pull request closed without merging**
