### PR TITLE
merge master into release/3.0.2

### PR DESCRIPTION
**Pull request by dkijania**
merge master into release/3.0.2 in order to fix merges cleanly

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
Nightly: 

https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2759

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
