### PR TITLE
Lk86/resolve conflicts with develop

### PR DESCRIPTION
**Pull request by lk86**
Companion PR to https://github.com/MinaProtocol/mina/pull/12072

### CODE REVIEW

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by QuiteStochastic — APPROVED** [review]

**Pull request merged**
