### PR TITLE
Replayer, check entire account; checkpointing

### LINKED ISSUE #11457: Verify entire account in replayer
We already check the balance and nonce for each account after each block.

Instead, compare the entire account in the ledger against the account in `accounts_accessed`, log which fields differ.

### LINKED ISSUE #13459: Replayer checkpointing for berkeley
The replayer on `berkeley` does not fully implement the checkpointing that was added to `compatible`. 

Some of the checkpointing code is there, but it's not used.

### PR DESCRIPTION
**Pull request by psteckler**
Add the checkpointing already in place for the `mainnet` replayer to the `berkeley` replayer.

Instead of checking just the balances and nonces, check that the entire accounts in `accounts_accessed` are identical to the ledger accounts.

Closes #13459. Closes #11457.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
