### PR TITLE
port rosetta docker-start fix and test to dev

### PR DESCRIPTION
**Pull request by dkijania**
porting https://github.com/MinaProtocol/mina/pull/16346 to dev

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
