### PR TITLE
Add interface files to `lib/pickles_base`

### PR DESCRIPTION
**Pull request by rbonichon**
This PR is a refactoring PR that adds interface files to all modules inside `lib/pickles_base`.
Whenever possible, this also adds some lightweight documentation inside these files.

# Dependencies

Merge after #11858

### CODE REVIEW

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
