### PR TITLE
Fix fork_config graphql logic

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR builds upon https://github.com/MinaProtocol/mina/pull/15107, allowing us to update compatible without unnecessary changes to the rampup branch.

This PR is a combination of #15077 and a backport of #15094. This PR will be merged into #15094 in due course.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by mrmr1993 — COMMENTED** [review]
Additional change from @georgeee LGTM

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
