### PR TITLE
Don't check ledger hash at start; restore final checkpoint

### PR DESCRIPTION
**Pull request by psteckler**
After loading the blocks it's going to replay, the replayer builds a table from global slots to ledger and state hashes. If the start slot did not contain a block, it would search backwards and never find the most recent hashes, because only the blocks to be replayed are loaded, no blocks before the start slot. So don't look for the ledger hash at the start slot -- we haven't yet replayed anything. We didn't see this issue until we started using checkpoint files.

Also, restore the checkpoint file dumped at the finish, but only write a checkpoint file if the block at a slot is canonical.

Updated the cron job to use image from this PR.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
The fix for payment test hasn't been merged for compatible. There's some merge conflict hasn't been resolved with the berkeley and develop branch (the test executive module has been changed). Helena is picking up the work this week. My suggestion for now would be just retry the test manually.

**Comment by psteckler** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Pull request merged**
