### PR TITLE
Optimize the non-present zkapp uri hashing

### PR DESCRIPTION
**Pull request by georgeee**
When no zkapp uri is specified, use a precomputed hash of a dummy stub.

Previous behavior involved hashing the dummy stub each time no zkapp uri was specified which is wasteful.

PR also removes some dead code, which just happened to be discovered dead during work on the PR.

Explain how you tested your changes:
* Saw improvement with `mina ledger test apply` benchmark

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-nix-me

**Comment by georgeee** [comment]
!ci-nix-me

**Comment by georgeee** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
