### PR TITLE
Remove build Libp2p job from CI

### PR DESCRIPTION
**Pull request by dkijania**
Matthew gave up with removing libp2p job from CI. This PR is porting his work:

https://github.com/MinaProtocol/mina/pull/16227

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
