### PR TITLE
Enable step proofs with chunking from OCaml

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR builds upon #14314, adding support for generating chunked step proofs in pickles.

This does not yet support verifying those proofs in the wrap circuit; this will come in a future PR.

This PR includes a fix to proof-systems via https://github.com/o1-labs/proof-systems/pull/1277, as well as some tweaks to the errors returned by the bindings to improve debugging.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by rbonichon — APPROVED** [review]
I'm not a super fan of the `proof.proof` elements since it makes it hard to get what we're talking about - at least for me. Could we think about better names either for the parameter or the field (or both!) ?

**Comment by mrmr1993** [comment]
> Could we think about better names either for the parameter or the field (or both!) ?

The whole representation of proofs for pickles could do with rethinking; this is merely a hack to get the data in the correct location. Feel free to suggest an alternative.

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by dannywillems — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
