### PR TITLE
Lk86/use avx2 optimizations

### LINKED ISSUE #11982: Separate build with rust target feature optimizations

### PR DESCRIPTION
**Pull request by lk86**
- Remove zexe standardize hack and always build with avx2 optimizations enabled in rust
- Add git diff check to CI as now there should be 0 changes after compiling
- Closes #11648 
- Fixes #11982

### CODE REVIEW

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approve-for-mainnet

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
