### PR TITLE
[develop] Reset feature flags before assertion + tests

### PR DESCRIPTION
**Pull request by mrmr1993**
This is #14402, with some additional tests using infrastructure that isn't available in that branch, as well as a temporary hack around a bug in proof-systems to make the test work. This also carries some changes from the merge with it.

From #14402:
> This PR changes the handling of feature_flags in Pickles for wrap circuits. Previously, we were propagating the flags from the step circuit, which could cause a sanity-check assertion to fail when we convert the 'full' set of values back to the 'wrap only' set of values. This PR fixes that by always resetting the flags before entering that conversion.
> 
> This PR does not change any circuits, protocol constants, etc.; the behavior is only changed when those offending flags are set. As such, this can be deployed to snark workers as a compatible bugfix version.
> 
> Tests to follow.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by jspada — APPROVED** [review]
Approved with one minor thing caught with sign coefficient.  Other than that a couple questions and suggestions.

**Review by deepthiskumar — APPROVED** [review]
Changes in `app/zkapps_examples/test` look good

**Comment by mrmr1993** [comment]
This now includes https://github.com/o1-labs/proof-systems/pull/1334

**Review by dannywillems — APPROVED** [review]
Bumping others approval (did not review). Only a comment: was there not a decision to go with `Alcotest` instead of `ppx_inline_tests`?

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
