### PR TITLE
Port mina maintenance docker berk

### PR DESCRIPTION
**Pull request by dkijania**
Porting #15418 to berkeley. Basically this is only for compatible. So commiting only empty merge

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1703

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
