### PR TITLE
fix version linter failure

### PR DESCRIPTION
**Pull request by dkijania**
Fixes version linter script. Currently we are suffering from read version linter job as it download sexpdata 1.0.1 . It introduce issue similar to :
https://stackoverflow.com/questions/77523055/missingdynamic-license-defined-outside-of-pyproject-toml-is-ignored

Reverting sexpdata to 1.0.0 should solve our problem

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
