### PR TITLE
Delete old, stale frontend code

### PR DESCRIPTION
**Pull request by mrmr1993**
:)

### CODE REVIEW

**Review by mitschabaude — APPROVED** [review]
🥳

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]
🪦

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
