### PR TITLE
add integration test for updating verification keys

### LINKED ISSUE #12433: Integration test for zkapps with changing VKs
1. zkApp transaction that updates VK and refers to it in subsequent account updates (should be accepted into the pool and included in a block with `Applied` status)
2. zkApp transaction that updates Vk but refers to older VK in subsequent account updates (should be accepted into the pool and included in a block but with `Failed` status, the failure being invalid-proof)
3. Enqueue another zkApp transaction that has a proof against the new VK immediately after (2) is enqueued. The transaction should be accepted (VK looked up from the refcounted table) and included in a block with `Applied status)

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR adds an integration tests that check the updates of verification keys.

Explain how you tested your changes:
*

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #12433

### CODE REVIEW

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by QuiteStochastic — APPROVED** [review]

**Review by lk86 — APPROVED** [review]

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Pull request merged**
