### PR TITLE
Remove token_id from local state

### PR DESCRIPTION
**Pull request by psteckler**
The `token_id` field of local state was always the default token, and never updated to a different token in the zkApps transaction logic.  Remove that field.

Software engineering: rename the inner `is_start'` in the zkApp transaction logic to `is_empty_call_forest`, to avoid confusion with the outer one.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
