### PR TITLE
Introduce new Command in Dhall to run job along with postgres docker

### PR DESCRIPTION
**Pull request by dkijania**
Added new dhall Command definition which can simplify running tests which requires postgres database running along with some initial script. 

Usage:

in Dhall test definition

```
 RunWithPostgres.runInDockerWithPostgresConn
          ([] : List Text)
           "./src/test/archive/sample_db/archive_db.sql"
           Artifacts.Type.Archive 
           "./buildkite/scripts/replayer-test.sh"
```

where 

- first argument extends environment variables passed to docker
- second argument defines init script which will be run against schema before script
- third defines which debians will be installed 
- fourth argument defines which script will be run against database

There are 4 env variables passed to the docker, so script can use them for connection:

```
"PG_PORT","POSTGRES_USER,"POSTGRES_PASSWORD","POSTGRES_DB","PG_CONN"
```

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
