### PR TITLE
[develop] Evaluate selectors for non-optional gates

### PR DESCRIPTION
**Pull request by mrmr1993**
This is https://github.com/MinaProtocol/mina/pull/13529 merged into develop. This uses
* https://github.com/o1-labs/proof-systems/pull/1143
* https://github.com/o1-labs/snarkyjs-bindings/pull/89
* https://github.com/o1-labs/snarkyjs/pull/1042

This also drags along some stuff from the berkeley branch. This is rooted on https://github.com/MinaProtocol/mina/pull/13653, because that already deals with some merge conflicts; accordingly, that needs to merge first.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by dannywillems — APPROVED** [review]

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
The commits 9aad074acb15b92802ec40b84e18906216f703e8, e818db587392b0c48236481aeeed887b32079699 and bd436acd212d537c73657f51deee325300645194 are the minimal changes to make `./buildkite/scripts/merges-cleanly.sh berkeley` happy

**Comment by dannywillems** [comment]
!ci-build-me

**Pull request merged**
