### PR TITLE
Lightweight Network configuration and documentation (develop).

### PR DESCRIPTION
**Pull request by shimkiv**
- Same as https://github.com/MinaProtocol/mina/pull/13287

### CODE REVIEW

**Comment by shimkiv** [comment]
!ci-build-me

**Comment by shimkiv** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]
Looks good, same suggestion as https://github.com/MinaProtocol/mina/pull/13287#discussion_r1213482926

**Comment by deepthiskumar** [comment]
!ci-build-me

**Pull request merged**
