### PR TITLE
Pass runtime tables information to the prover and lookup tables to bindings when creating cs

### PR DESCRIPTION
**Pull request by dannywillems**
Explain your changes:
* Depends on [this PR (commenting pickles)](https://github.com/MinaProtocol/mina/pull/13386).
* Depends on [this PR (proof-systems: runtime tables)](https://github.com/o1-labs/proof-systems/pull/1070)
* Depends on [This PR (snarky-js-bindings)](https://github.com/o1-labs/snarkyjs-bindings/pull/55).
* Part of [Exposing runtime tables to SnarkyJS](https://github.com/MinaProtocol/mina/issues/13086)

Explain how you tested your changes:

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes [#13089](https://github.com/MinaProtocol/mina/issues/13089)
* Closes [#13090](https://github.com/MinaProtocol/mina/issues/13090)

### CODE REVIEW

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by fabrizio-m** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
Closing in favor of the PR train described in #13086

**Pull request closed without merging**
