### PR TITLE
reverse condition in mainnet check and remove toolchain stretch docker

### PR DESCRIPTION
**Pull request by dkijania**
Another portion of fixes for compatible nightly. Reverse condition on connect to testnet, so actually connection attempt will be executed on compatible. Remove leftover docker for stretch

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by shimkiv — APPROVED** [review]
LGTM

**Pull request merged**
