### PR TITLE
Fix genesis block treatment

### PR DESCRIPTION
**Pull request by joaosreis**
This pull request fixes the treatment of the genesis block. Previous implementation assumed the genesis block was the first block of the chain, which is not the case anymore after hard-fork. The issue was related to the handling of the parent block and the validation of the block's identifier. This implementation now handles the genesis block the same way as any other block and sets the parent block of a block with not `parent_block_id` as itself.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-nightly-me

**Review by Sventimir — COMMENTED** [review]
If I remember correctly, the treatment of the genesis block was different before because this block was never inserted into the archiver's database. Has this been fixed? It seems like the hard-fork migration of the archive would be a nice time to simply insert that block and forget about the issue…

**Comment by joaosreis** [comment]
@Sventimir that is also related to the second issue I found. We can't rely on GraphQL for **original** genesis block info because now the genesis block is a different one, thus, making persistence on the DB of the original genesis block mandatory for historical queries. I tested against the migrated UMT network and the genesis block info is there, so we are good.

**Review by Sventimir — APPROVED** [review]
Perfect :)

**Pull request merged**
