### PR TITLE
Fix issues with the Rosetta API block queries

### PR DESCRIPTION
**Pull request by joaosreis**
There was an issue with Rosetta API when querying operations from accounts with multiple tokens where the operations would show multiplicated. This PR fixes it by constraining the queries to the default token.

Another issue was found where the API would present the same zkapp account update multiplicated when the same zkapp account updates existed in different blocks. This is fixed by constraining the zkapp account updates queries by block.

This was tested by running `rosetta-cli check:data` against ITN and verifying that the previously observed issue was fixed.

This PR also updates `rosetta-cli` in our nix flake to our fork that has the necessary signature modules.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
