### PR TITLE
[develop] Install mina binary before calling it in the version linter

### PR DESCRIPTION
**Pull request by mrmr1993**
This is #14983 against `develop`.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Pull request merged**
