### PR TITLE
End the suffering, turn back on `implicit_transitive_deps`

### PR DESCRIPTION
**Pull request by mrmr1993**
This was a mistake, and we have now learned from it :)

**Context:**

We had hoped that this option would get dune to warn us when we were underspecifying our dependencies. In particular, since dune is able to infer the transitive dependencies, it has all the information that we need. However, in practice this is implemented in a way that's very inconvenient to use:
* dune doesn't emit any warnings;
* dune doesn't resolve upstream transitive dependencies (e.g. `core -> core_kernel -> base -> base.caml`), which makes our external dependencies unnecessarily and unhelpfully verbose;
* the OCaml compiler is the only thing 'checking' the dependencies, and missing types are treated as 'abstract'
  - this causes unpleasant and confusing error messages,
  - the OCaml compiler uses head-normalising type path expansion, so if we have `A.t = B.t = C.t = int * bool`, the error will report that `A.t` is abstract even when `B` or `C` are the missing libraries.

The correct approach is to add a mode for dune to check the (local/workspace) dependency enumeration, using its internal tracking; this is explicitly not done here.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by emberian** [comment]
Our dune deps could be so pretty...

**Review by emberian — APPROVED** [review]

**Comment by bkase** [comment]
I get it ended up being too much pain, and not worth the benefit, but could you include a few bullet points at the top about why it ended up being a mistake so we have a record of it?

Here's the original issue on it:
https://github.com/MinaProtocol/mina/issues/2451

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by emberian** [comment]
As a quick example of the pain, a recent change I introduced to wire types required changing exactly `100` of our packages to add a trivial line, otherwise getting annoying errors about the types being opaque.

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by MartinMinkov — APPROVED** [review]

**Review by ejMina226 — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Review by dkijania — APPROVED** [review]

**Pull request merged**
