### PR TITLE
update timing info

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
In the protocol, after the vested accounts are fully vested, sometimes we would turn the timing_info of the account from `Timed` into `Untimed`. This means that we could have different `timing_info` for the same account depending on where we are at in history of the chain. 

Here's the command to patch the database after phase 1 of the migration

```
alter table timing_info drop constraint timing_info_account_identifier_id_key ;
```

Explain how you tested your changes:
*

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by georgeee** [comment]
@ghost-not-in-the-shell please add description to the PR

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by georgeee** [comment]
@ghost-not-in-the-shell please describe how the testing was performed in the PR description

**Review by georgeee — APPROVED** [review]

**Review by Sventimir — COMMENTED** [review]
Looks okay, but please run the rosetta-cli tests to make sure you don't break Rosetta with this change. I believe these tests are a part of a nightly build, right?

**Comment by joaosreis** [comment]
Seconding what @Sventimir said, when this is merged into `berkeley`/`develop` check if Rosetta tests in nightly build are green.

**Review by joaosreis — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-nightly-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-nightly-me

**Pull request merged**
