### PR TITLE
Hard fork protocol version is 2.0

### PR DESCRIPTION
**Pull request by psteckler**
After getting clarification from the protocol team, set the berkeley hard fork protocol version to `transaction = 2, network = 0, patch = 0`.

Update `Protocol_version.is_valid` to accept 0 as the network version.

### CODE REVIEW

**Review by nholland94 — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Pull request merged**
