### PR TITLE
Chunk Base58Check for long inputs

### PR DESCRIPTION
**Pull request by psteckler**
For long inputs, chunk strings for Base58Check encoding.

Break the input into chunks, Base58Check-encode each chunk. Prefix each encoding with its length, a 4-byte hex string. Concatenate the encodings, and prefix the result with `@`. That character does not appear in the Base58 alphabet we're using. On Linux, strings containing it remain double-click mouse-selectable.

Tested that the chunked encoding and decoding are inverses, using a very long string. Added a unit test with a string of about 35K. Note: encoding that string takes about 2 seconds on my desktop. I could probably reduce the chunk size a bit to gain a bit more speed, if desired.

Part of #9563.

### CODE REVIEW

**Comment by psteckler** [comment]
For the string in the new unit test, the chunking provides dramatic speedup:
```
TM CHUNKED: 2.1766
TM UNCHUNKED: 9.8297
```

**Comment by psteckler** [comment]
Note: the Base58 encoder (without the check bits) exhibits superlinear behavior:
```
SMALL: 0.0034
MEDIUM: 0.0134
BIG: 0.0534
HUGE: 0.2119
SIZE RATIO HUGE/SMALL: 8.0000
TM RATIO HUGE/SMALL: 62.7854
```
The author of an IETF draft for the algorithm claims it should be linear-time.

If that's true, we should re-implement the algorithm.

**Comment by georgeee** [comment]
@psteckler where in the mina node do we use base58check for large data blobs?

**Comment by bkase** [comment]
Can you use `0` instead of `@` as the separator? This also doesn't appear in base58, but is urlencodable without needing a transformation. cc @jasongitmail to comment

**Comment by psteckler** [comment]
> Can you use `0` instead of `@` as the separator? This also doesn't appear in base58, but is urlencodable without needing a transformation. cc @jasongitmail to comment

Done.

**Pull request merged**
