### PR TITLE
Fix compilation of kimchi against develop

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR builds upon PR #9790, adding the remaining required changes to compile mina using the kimchi proof system.

The majority of the diff is updates to and removal of versioned types, as appropriate. The other small changes are
* updating the `dummy_constraints` function in `transaction_snark`
* updating the `Side_loaded_verification_key.dummy` function in the client SDK library
* moving `Pickles_types.Scalar_challenge` to `Kimchi_backend_common`, to remove an unsatisfiable dependency of the client SDK on the rust binary

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Review by bkase — APPROVED** [review]
Product stamp 💯

**Comment by bkase** [comment]
Delegating to @deepthiskumar for the Protocol Review

**Review by deepthiskumar — COMMENTED** [review]
Could you elaborate a bit more on why most of the `V1`s are not required? The ones not used externally makes sense. I'm not sure of account, ledger etc.  
Should we keep some of those V1s for backwards compatibility  of replayer (maybe other tools too)?  cc @psteckler 
I guess we need to have a discussion on versioning for the hard fork. We could probably eliminate all the previous versions for values exchanged only between daemon nodes

**Comment by mrmr1993** [comment]
> Could you elaborate a bit more on why most of the `V1`s are not required?

Cross copying from our DMs:
> The versioning only ever actually got implemented for RPCs, which already have their own versioning. I'm happy to discuss the versioning, but really our best course at the moment is copying the types from old and new releases and writing the adapters for the conversions we actually need.

**Comment by mrmr1993** [comment]
> Could you elaborate a bit more on why most of the `V1`s are not required?

Cross copying from our DMs:
> The versioning only ever actually got implemented for RPCs, which already have their own versioning. I'm happy to discuss the versioning, but really our best course at the moment is copying the types from old and new releases and writing the adapters for the conversions we actually need.

**Review by mimoo — APPROVED** [review]
LGTM

**Review by deepthiskumar — APPROVED** [review]

**Comment by mrmr1993** [comment]
Smuggled in a change to fix CI (move a test from the proof-systems repo that depends on nightly rust out of the mina tests). proof-systems PR to follow.

**Pull request merged**
