### PR TITLE
replace xrefcheck docker with awesome_bot

### PR DESCRIPTION
**Pull request by dkijania**
Fixing xref checks in md files job. It was unstable and always failing. Additionally from time to time it took several hours to finish it. I tried updating xrefcheck docker image however there is some internal issue on newest image so i decided after couple of hours to abandon this tool and introduce awesome_bot app. Luckily it works ok and even showed some new issues with docs. 

This PR contains only job fix without fixing checks which are failing as we have still unresolved issues in our md files

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
