### PR TITLE
add coverage gather for archive related tests

### PR DESCRIPTION
**Pull request by dkijania**
Added sub steps for patch archive and replayer tests which sends coverage data to coveralls

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
nightly run: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2838#0192e6b5-b7a4-44c8-bb6e-875e8e32727a

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
