### PR TITLE
Rename previous_global_slot to genesis_slot in compatible

### PR DESCRIPTION
**Pull request by Sventimir**
Explain your changes:
* For the genesis ledger export (as described in #14213) to succeed, we need runtime configs of the Mainnet and berkeley to be as compatible as possible. Thus porting 2be03bf57fc73fc0bcc58db7a24f349f06d99364 to `compatible` to avoid conflicts.

Explain how you tested your changes:
* Run the node, exported the fork ledger.
* Run the CI.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* This is a step towards closing https://github.com/MinaFoundation/mina/issues/95

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
Make it a draft until https://github.com/MinaProtocol/mina/pull/14271 lands and solves the conflicts with `berkeley`.

**Review by bkase — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
This PR is now stale, and the issue was handled a different way. The test runs with the other method have been successful, and `compatible` will be retired soon, so I'm going to close this.

**Pull request closed without merging**
