### PR TITLE
Back-merging: Add branching policy (berkeley)

### PR DESCRIPTION
**Pull request by volhovm**
Back-merges https://github.com/MinaProtocol/mina/pull/14684 into `berkeley`.

The conflict was that `berkeley` (same as `develop`: https://github.com/MinaProtocol/mina/pull/14914) contained an older version of the branching policy that was on notion. That older policy was fully incorporated into the new one.

### CODE REVIEW

**Review by dannywillems — APPROVED** [review]

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
