### PR TITLE
Libp2p upgrade

### PR DESCRIPTION
**Pull request by nholland94**

### CODE REVIEW

**Review by dkijania — COMMENTED** [review]
Can you also make sure that watchdog is compatible with this change:

`/automation/services/watchdog`

**Review by georgeee — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by nholland94** [comment]
@dkijania I don't think this upgrade should have any effect on the watchdog, but let me know if you believe otherwise.

**Comment by nholland94** [comment]
!ci-build-me

**Review by QuiteStochastic — APPROVED** [review]

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Pull request merged**
