### PR TITLE
Lk86/remove bionic stretch rampup conflicts

### PR DESCRIPTION
**Pull request by lk86**
Attempt to resolve conflicts between the current compatible changes (+ removal of bionic/stretch support) into rampup

### CODE REVIEW

**Comment by lk86** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Review by stevenplatt — APPROVED** [review]

**Review by nholland94 — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Pull request merged**
