### PR TITLE
Refactor transaction_logic

### PR DESCRIPTION
**Pull request by Sventimir**
Refactor `transaction_logic` library to facilitate writing tests:
* extract as much code as possible from functors to make it more testable
* split large modules into smaller parts to make it easier to navigate

Explain how you tested your changes:
* these changes are not expoected to change the semantics of the code, so we rely on the CI to catch possible mistakes.

This is a step towars closing #12530 and #12544.

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci_build_me

**Comment by Sventimir** [comment]
!ci_build_me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Review by ejMina226 — APPROVED** [review]

**Comment by kantp** [comment]
This is blocked right now, as it is interfering with active work on the module.

**Comment by Sventimir** [comment]
Our plans regarding this library changed significantly in the last weeks, which makes this PR obsolete. Closing.

**Pull request closed without merging**
