### PR TITLE
[compatible] OPAM: update dune to 3.16.0

### PR DESCRIPTION
**Pull request by dannywillems**
Following commands:
```
opam install dune.3.16.0 -y
opam switch export opam.export
```

Version of OPAM used: 2.2.1

OCaml is now moving fast, and dependencies are upgrading quickly.
We might want to update the dependencies gradually. Starting with dune.

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by dannywillems** [comment]
!ci-bulid-me

**Comment by dannywillems** [comment]
!ci-bulid-me

**Review by mrmr1993 — CHANGES_REQUESTED** [review]
This appears to need a rebase to remove unrelated changes

**Comment by L-as** [comment]
This would be nice to have.

**Pull request closed without merging**
