### PR TITLE
Bump up proof-systems to include fix nb chunks

### PR DESCRIPTION
**Pull request by dannywillems**
Explain your changes:
* testing https://github.com/o1-labs/proof-systems/pull/2012 on develop to see if any impact on Mina. LGTM locally,

Explain how you tested your changes:
* run `dune buid src/lib/pickles`

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by dannywillems** [comment]
!ci-build-me

**Review by volhovm — APPROVED** [review]

**Review by volhovm — CHANGES_REQUESTED** [review]
Give me 5min to check, but I'm suspecting this might introduce a flaky test. Will reapprove if there's no issue...

Edit: here's what `proof-systems/master` has flaky now, suspecting https://github.com/o1-labs/proof-systems/pull/2010 since it's the same file and recent, but haven't investigated this.
```
test tests::commitment::test_commit ... FAILED
test tests::commitment::test_commit_deterministic ... ok

failures:

---- tests::commitment::test_commit stdout ----
Seed: [55, 42, 12, 184, 248, 108, 210, 47, 173, 124, 185, 107, 82, 15, 186, 229, 208, 93, 223, 0, 242, 165, 255, 60, 161, 6, 23, 123, 220, 224, 120, 144]
total commitment time: 523.804275ms
total evaluation proof creation time: 474.32619ms
thread 'tests::commitment::test_commit' panicked at 'assertion failed: srs.verify::<DefaultFqSponge<VestaParameters, SC>,\n    _>(&group_map, &mut batch, &mut rng)', poly-commitment/src/tests/commitment.rs:229:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::commitment::test_commit

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 6 filtered out; finished in 1.13s

error: test failed, to rerun pass `-p poly-commitment --lib`
```

**Comment by dannywillems** [comment]
I confirm the flakyness.

**Comment by dannywillems** [comment]
> I confirm the flakiness.

It is fixed now. It was a missing case (when we have the zero polynomial) that was failing.

**Comment by volhovm** [comment]
For posterity: fixed in https://github.com/o1-labs/proof-systems/pull/2020

**Comment by volhovm** [comment]
@dannywillems Updated `proof-systems` to `6682dfdd4599c3ba7a6ec60d9b14f667ef33f449` which is a new head in your PR https://github.com/o1-labs/proof-systems/pull/2012 after cherry-picking the zero-case fix. Please tell me if this looks good, I'll run the CI + approve.

**Review by volhovm — APPROVED** [review]

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Pull request merged**
