### PR TITLE
[TESTING][HARD FORK TEST RUN] Generate package to deploy hard fork

### PR DESCRIPTION
**Pull request by mrmr1993**

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by georgeee** [comment]
!ci-nightly-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-nightly-me

**Comment by georgeee** [comment]
!ci-nightly-me

**Comment by georgeee** [comment]
!ci-nightly-me

**Comment by georgeee** [comment]
!ci-nightly-me

**Pull request closed without merging**
