### PR TITLE
snapps and tokens behind flags

### PR DESCRIPTION
**Pull request by imeckler**
This PR puts snapps and tokens behind config flags. It does this through the bin_io instance, throwing an error if

- a `Signed_command` is anything other than `Payment` or `Delegate_stake`
- a `Token_id` is anything other than `default`
- an `Account` has a `Some` snapp field
- error on any `Snapp_command`

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]
Approving, but it would be nice to handle this more gracefully when we can.

At present, I think this will surface an error in the response to the sender, but the daemon will have no record that it happened, and won't be able to involve the trust system. I think this is a subset of a more general problem with our RPC handling though.

**Comment by es92** [comment]
Including this PR in a QA net leads to the error:
```
{"timestamp":"2020-10-24 22:45:38.928650Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 575, characters 2-26"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error (Failure \"Non-default tokens are disabled\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/utils.ml\\\", line 101, characters 38-54\"\n    \"Called from file \\\"src/lib/coda_base/token_id.ml\\\", line 52, characters 4-98\"\n    \"Called from file \\\"src/lib/coda_state/blockchain_state.ml\\\", line 9, characters 6-323\"\n    \"Called from file \\\"src/lib/coda_state/blockchain_state.ml\\\" (inlined), line 9, characters 6-323\"\n    \"Called from file \\\"src/lib/coda_state/blockchain_state.ml\\\", line 9, characters 6-323\"\n    \"Called from file \\\"src/lib/coda_state/blockchain_state.ml\\\", line 32, characters 6-238\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\", line 37, characters 8-325\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\" (inlined), line 37, characters 8-325\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\", line 37, characters 8-325\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\", line 51, characters 8-314\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\", line 18, characters 6-148\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\" (inlined), line 18, characters 6-148\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\", line 18, characters 6-148\"\n    \"Called from file \\\"src/lib/coda_state/protocol_state.ml\\\", line 169, characters 6-142\"\n    \"Called from file \\\"src/lib/coda_transition/external_transition.ml\\\", line 29, characters 4-520\"\n    \"Called from file \\\"src/lib/coda_transition/external_transition.ml\\\", line 29, characters 4-520\"\n    \"Called from file \\\"src/utils.ml\\\", line 14, characters 16-29\"\n    \"Called from file \\\"src/lib/rocksdb/serializable.ml\\\", line 115, characters 29-53\"\n    \"Called from file \\\"src/lib/transition_frontier/persistent_frontier/database.ml\\\", line 279, characters 6-77\"\n    \"Called from file \\\"src/lib/rocksdb/database.ml\\\", line 49, characters 17-24\"\n    \"Called from file \\\"src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml\\\", line 344, characters 6-48\"\n    \"Called from file \\\"src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml\\\", line 328, characters 10-20\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))","host":"35.231.48.182","peer_id":"12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr","pid":10,"port":10001}}
```

**Comment by mrmr1993** [comment]
@es92 I've pushed a fix, there was an oversight with `next_available_token` in the protocol state.

**Comment by es92** [comment]
Thanks @mrmr1993, will try again

**Comment by es92** [comment]
Seeing new failure with this now, https://buildkite.com/o-1-labs-2/mina/builds/5010#653627d9-df47-4d2b-915c-14cbd2e3f083
```File "src/lib/coda_base/token_id.ml", line 47, characters 42-49:
Error: This expression has type T.t but an expression was expected of type
         int
Makefile:252: recipe for target 'build_or_download_pv_keys' failed
```

**Comment by mrmr1993** [comment]
Should be fixed now, I tested a compile but didn't think to switch the flags before doing it 🤦‍♂️

**Pull request merged**
