### PR TITLE
Add `send_payment` and `send_zkapp` mutations to limited GraphQL server

### PR DESCRIPTION
**Pull request by psteckler**
This is the only mutations offered by that server.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by shimkiv** [comment]
- [Internal discussion #1](https://o1-labs.slack.com/archives/C05PFKHE2S0/p1698829799995139).
- [Internal discussion #2](https://o1-labs.slack.com/archives/C05PFKHE2S0/p1699269853115299).

**Comment by shimkiv** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
Rampup is retired, this PR is now orphaned. Closing.

**Pull request closed without merging**
