### PR TITLE
Speed up CI: Use the proof cache for another txn snark test

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR builds upon https://github.com/MinaProtocol/mina/pull/15091, since it modifies the constraint system.

This PR:
* makes the `access_permission` txn snark test deterministic
* uses the proof cache for that test to speed it up.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by emberian** [comment]
nice

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
