### PR TITLE
Remove src/external/ocaml-rocksdb from repo

### PR DESCRIPTION
**Pull request by georgeee**
Explain your changes:
* Extract `ocaml-rocksdb` to a separate repository https://github.com/o1-labs/orocksdb
* Modify build of the package to depend on rocksdb stub to be provided by some other opam package
* Introduce an opam package `rocksdb_stubs` to build the stub lib directly from source
   * This way hack of fetching git source in dune is removed

Explain how you tested your changes:
* [x] Re-build opam switch on Linux (with no library pre-provided)
* [ ] Re-build opam switch on MacOS

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
Review of this PR should be accompanied by review of commit https://github.com/o1-labs/orocksdb/commit/2ea8c0ee7483b9fff54c761a035fd085727b367b which is the changeset applied to extracted `ocaml-rocsdb` code (and yep, git history was fully preserved :blush:)

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by emberian** [comment]
Taking up the macOS testing of this before I leave my r+, but this looks fine so far.

**Comment by georgeee** [comment]
Decided to merge the PR into its predecessor for easier bookeeping

**Pull request merged**
