### PR TITLE
[develop] Add indexer feature to Rosetta

### PR DESCRIPTION
**Pull request by joaosreis**
See #15564

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-toolchain-me

**Comment by joaosreis** [comment]
!ci-toolchain-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Review by Sventimir — APPROVED** [review]

**Comment by joaosreis** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Pull request merged**
