### PR TITLE
Merge develop into o1js main

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR merges back develop into o1js-main. Note that this uses #15038 as the merge commit, to include latent commits from berkeley which are not yet merged into develop.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mitschabaude** [comment]
o1js built from this is not compatible with `berkeley`: https://github.com/o1-labs/o1js/pull/1410

this prevents merging this for now, sadly

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
we did this somewhere else

**Pull request closed without merging**
