### PR TITLE
merge master to compatible 15 11 24

### PR DESCRIPTION
**Pull request by dkijania**
merge master to compatible

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by georgeee — APPROVED** [review]

**Comment by dkijania** [comment]
nightly: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2905#_

**Pull request merged**
