### PR TITLE
Add more of `Pickles_types` to `Mina_wire_types`

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR expands the number of serialised types tracked in `Mina_wire_types` to cover proofs from `Pickles_types`.

### CODE REVIEW

**Review by dannywillems — APPROVED** [review]

**Comment by dannywillems** [comment]
Taking care of merging compatible into the branch.

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-nightly-me

**Review by dkijania — APPROVED** [review]

**Comment by dannywillems** [comment]
It seems that the integration tests were failing: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2580#_

**Pull request merged**
