### PR TITLE
[Draft] Patch build-hardfork-package.sh against a bug in 1.4

### PR DESCRIPTION
**Pull request by georgeee**
Which is fixed by PR #15462

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Review by nholland94 — APPROVED** [review]

**Comment by nholland94** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
fork package successful https://buildkite.com/o-1-labs-2/hardfork-package-generation/builds/217

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
