### PR TITLE
200k ledger for ITN

### LINKED ISSUE #14236: ITN ledger generation

### PR DESCRIPTION
**Pull request by psteckler**
In the `berkeley` ledger, include all the accounts from #13099, plus enough new accounts to get 200,000 total accounts.

Closes #14236.

### CODE REVIEW

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
nit: can we change the ledger name to `berkeley-ITN`?

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
