### PR TITLE
Don't check zkApp proofs in the snark if application will fail anyway

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR proposes an alternative approach to #12397. This allows us to skip verification of failed zkApp commands' proofs in both the snark and the block verification logic.

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
@deepthiskumar your new changes here seem to have broken the CI, and this change is safe as a standalone -- it weakens the snark constraints, but leaves the current verification alone. I've reverted them and merged develop; your changes are in `feature/early-fail-with-stuff`.

I'm going to open a follow-up PR that skips the verification of those proofs.

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
