### PR TITLE
Bring back DEB_REPO argument for docker image build

### PR DESCRIPTION
**Pull request by dkijania**
I accidently removed DEB_REPO argument when building docker images in the last merge. Bringing it back. Inverted logic for choosing debian repo (local vs aws)

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-toolchain-me

**Review by rbonichon — APPROVED** [review]

**Review by amc-ie — APPROVED** [review]
Danke!

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
