### PR TITLE
[Port to compatible] Remove Buster support 

### PR DESCRIPTION
**Pull request by dkijania**
We didn't apply buster removal from master on a occasion when we dropped support for this codename in develop and compatible. 

Port: https://github.com/MinaProtocol/mina/pull/16161

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
since we merged release/3.0.2 to mater this porting branch is not needed

**Pull request closed without merging**
