### PR TITLE
[CI][Nightly] Control which job is run on CI vs Nightly by individual job type

### LINKED ISSUE #8821: Improved buildkite nightly/stable pipeline configuration
Improve the nightly/stable pipeline configuration in buildkite. Right now, we just run all jobs for nightly/stable pipelines, but what we would like to do is have more control over which jobs to run. Eventually, we want special jobs that will run only on nightly pipelines, so this work is in direct service of that.

### PR DESCRIPTION
**Pull request by dkijania**
Explain your changes:
Current Buildkite CI does not distinguish on dhall level if we are running nightly or PullRequest tests. However, from deep dive into logic, there is some work done, which can be extended to control which job should run on nightly. By  providing `export BUILDKITE_PIPELINE_MODE=Stable` we can signal Ci that we want to run nightly jobs so Monorepo triage is disabled and all known jobs will be run. 

However, it's not satisfactory, as we also want to exclude some jobs from PullRequest stage and run only on Stable. Therefore I introduced new attribute of `JobSpec` struct : `mode` which by default is set to PullRequest, but in some occasion can be override to `Stable`. Then code in monorepo traige job analyze it and prevents this jobs from running.

Stable (a.k.a Nightly ) logic is unchanged.

Explain how you tested your changes:

I tested it on fuzzy zkapp tests job example, which is using $NIGHTLY parameter which on script level control if jobs is empty but evergreen on PullRequest or have actual test run on Stable. I removed that logic from script and put Stable as job mode in dhall. Then verified job is not run.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #8821

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by QuiteStochastic — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by bkase — APPROVED** [review]

**Comment by bkase** [comment]
!approved-for-mainnet

**Comment by dkijania** [comment]
Closes #13969

**Pull request merged**
