### PR TITLE
demote some critical alerts to warnings

### PR DESCRIPTION
**Pull request by emberian**
Until after the HF, these are just how it is.

### CODE REVIEW

**Comment by emberian** [comment]
(do I run a job manually with DEPLOY_ALERTS=true? is there a !ci-alert-me? cc @dkijania)

**Comment by mrmr1993** [comment]
> do I run a job manually

@emberian yes :(

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
