### PR TITLE
K8s preemption change berk3

### PR DESCRIPTION
**Pull request by QuiteStochastic**

### CODE REVIEW

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Review by deepthiskumar — APPROVED** [review]
Replayer changes from compatible look fine

**Pull request merged**
