### PR TITLE
[berkeley] Pickles soundness fix: correlate evaluations and feature flags

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR updates pickles to fix a soundness issue where the Fiat-Shamir transcript is equivalent for e.g. `None, Some(x), None` and `None, None, Some(x)`. This fix constrains the `Some`s and `None`s according to the existing feature flags, ensuring that a malicious prover cannot disable gate checks by abusing this reordering.

Without this change, custom gates cannot safely be used unless they are all used in a circuit. Accordingly, this should be included in the berkeley HF.

This PR changes the zkApp transaction snark circuit, and thus also the blockchain snark.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by rbonichon — APPROVED** [review]
LGTM

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
