### PR TITLE
[berkeley] Tiny updates to nix

### PR DESCRIPTION
**Pull request by georgeee**
Clone of #15209 against `berkeley`

Explain your changes:
* Add another signing key for nix substituter (generated by @georgeee)
* Bump `opam-repository` (package `ocamlgraph` had broken URL in the previous version)

Explain how you tested your changes:
* Built with `#devnet` profile, observed cache is used successfully

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by SanabriaRusso** [comment]
This PR leverages envs injected into Buildkite `generic` and `small` agents: https://github.com/MinaProtocol/mina-deployments/pull/22

The referenced PR has already been applied to enable this one.

**Review by SanabriaRusso — APPROVED** [review]

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
