### PR TITLE
[CI][Berk] migrate nix to bk berk

### PR DESCRIPTION
**Pull request by dkijania**
Current nix build job is based on github action as It was an easiest setup. However, we bump into issues like insufficient disc space when nix required full rebuild and was not using cache. This pr migrate github workflow job to buildkite one. Currently the only problem is, that we cannot fully benefit from cache and each time we need to fully rebuild mina which takes ~ 40 minutes.

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by shimkiv — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
