### PR TITLE
Add debug logs for Mina_lib_tests

### PR DESCRIPTION
**Pull request by psteckler**
Add some debug logs to `Mina_lib_tests`.

The `Sync current, next staking ledgers to empty ledgers` test frequently times out. The greatest uses of time:
- starting verifier (locally, ~8 to ~24 secs)
- starting transition router (locally, ~61 secs)
- syncing ledgers (locally, ~12 secs)

Not increasing the timeout, so if the test continues to fail, we can compare the times in CI to these local  times.

Update: the time sink appeared to have been creating the first verifier. Fix: create the verifier in the test module, use that for all tests. Allow the first test to use the default timeout, which should be fine now.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]

**Comment by nholland94** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
