### PR TITLE
[CI][UMT] build focal berkeley migration deb

### PR DESCRIPTION
**Pull request by dkijania**
I learned from our AN ops that they would like to use focal debian for berkeley migration. This PR introduces such job

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
