### PR TITLE
more multi jobs in CI

### PR DESCRIPTION
**Pull request by dkijania**
Added another pack of Multi jobs:

- xref checks
- rust linter
- merges cleanly

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by SanabriaRusso — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Pull request merged**
