### PR TITLE
Add a -stop-staking option to set-staking CLI

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR adds a `-stop-staking` option to the `client set-staking` command. This allows users to turn off staking from the CLI.

I have been using this to control when block production happens when testing snapp commands, so that I don't need to wait for an empty block between executing commands.

Sample output of `-help` and invalid combinations:

```
$ _build/default/src/app/cli/src/coda.exe client set-staking -help
Start producing blocks

  coda.exe client set-staking

=== flags ===

  [-public-key PUBLICKEY]            Public key of account with which to produce
                                     blocks
  [-rest-server URI/LOCALHOST-PORT]  graphql rest server for daemon interaction
                                     (examples: 3085 or
                                     http://localhost:3085/graphql,
                                     /dns4/peer1-rising-phoenix.o1test.net:3085/graphql)
                                     (default: 3085 or
                                     http://localhost:3085/graphql)
  [-stop-staking]                    Stop producing blocks
  [-help]                            print this help text and exit
                                     (alias: -?)

$ _build/default/src/app/cli/src/coda.exe client set-staking
Error parsing command line.  Run with -help for usage information.
Must pass one of these: -public-key; -stop-staking
$ _build/default/src/app/cli/src/coda.exe client set-staking -public-key B62qrPN5Y5yq8kGE3FbVKbGTdTAJNdtNtB5sNVpxyRwWGcDEhpMzc8g -stop-staking
Error parsing command line.  Run with -help for usage information.
Cannot pass both -stop-staking and -public-key
```

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Review by deepthiskumar — APPROVED** [review]
Suggestion: The `set-snark-worker` command disables snark working when no public key is passed to it. We probably should change that command or this to make the stopping feature consistent.

Also think this should be reviewed by product

**Review by lk86 — CHANGES_REQUESTED** [review]
I agree with @deepthiskumar that the UX should be the same across set-snark-worker and set-staking, but to me they should really be distinct commands `stop-snark-worker` and `stop-staking` vs. a flag. The idea that -public-key and -stop-staking flags are "opposites" of eachother is not intuitive.

**Comment by michellewong793** [comment]
this sounds good to me, as long as we make it clear how to do so in the docs!

**Comment by psteckler** [comment]
`unset-staking` ?

**Comment by mrmr1993** [comment]
> Suggestion: The `set-snark-worker` command disables snark working when no public key is passed to it. We probably should change that command or this to make the stopping feature consistent. (create an issue?)

I've updated this to implement Deepthi's proposal, for consistency with `set-snark-worker`; this now accepts 0, 1, or many `--public-key` flags, and running the command replaces the set of staking pks with exactly those passed to the command.

@lk86 does this seem okay to you, or should we still have a separate command?

**Comment by mrmr1993** [comment]
There's clearly no demand for this, closing.

**Pull request closed without merging**
