### PR TITLE
Fix block producer long async cycle (merge into berkeley)

### PR DESCRIPTION
**Pull request by nholland94**
Merges #13654 into berkeley.

### CODE REVIEW

**Review by psteckler — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
