### PR TITLE
develop merges last-berkeley-edits

### PR DESCRIPTION
**Pull request by emberian**
Merges last-berkeley-edits, resolves conflicts all at once

TODO: address https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/33394#018e884e-b5d3-4f22-ba11-49073884e4de, known patch staleness.

### CODE REVIEW

**Comment by emberian** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Review by deepthiskumar — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Pull request merged**
