### PR TITLE
Remove more stale apps

### PR DESCRIPTION
**Pull request by psteckler**
Remove these stale apps:

- `genesis_ledger_from_tsv` : was used to generate the original mainnet ledger
- `swap_bad_balances` : swapped balances in the mainnet archive db due to an error fixed long ago
- `delegation_compliance`: checked delegation obligation compliance; that task was taken over long ago

### CODE REVIEW

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
