### PR TITLE
Update Rosetta README Coda references to Mina

### PR DESCRIPTION
**Pull request by omerzach**
Update Rosetta README Coda references to Mina

Text changes don't require testing. Tested updated links in browser.

Checklist:
- [x] Document code purpose, how to use it
- [x] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them: -

### CODE REVIEW

**Review by bkase — APPROVED** [review]

**Comment by bkase** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by bkase** [comment]
Only the rosetta-docker step is failing, which we'll address with a later PR

**Pull request merged**
