### PR TITLE
12318 - Refactor rosetta docker-start.sh to support Release 2.0

### PR DESCRIPTION
**Pull request by kaozenn**

### CODE REVIEW

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by ylecornec** [comment]
!ci-build-me

**Review by ylecornec — APPROVED** [review]

**Review by lk86 — CHANGES_REQUESTED** [review]
I'm worried about changing the README in a way that does not reference mainnet at all. Given that `develop` is still the default branch on github, this is the canonical rosetta readme and ideally, we can format it to have distinct sections for berkeley vs. mainnet but I wouldn't overwrite all of the valid mainnet/devnet instructions

**Comment by kaozenn** [comment]
it is a good point @lk86 . I will only include the docker-berkeley-start.sh to this PR, and we will create a separate ticket for the rest once 2.0 is live

**Comment by kaozenn** [comment]
!ci-build-me

**Review by lk86 — APPROVED** [review]

**Pull request merged**
