### PR TITLE
Remove unused genesis ledgers

### PR DESCRIPTION
**Pull request by mrmr1993**

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
Nightly here: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2321

**Review by nholland94 — APPROVED** [review]

**Comment by svv232** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
Taking care of merging compatible and rerun CI after https://github.com/MinaProtocol/mina/pull/15919 is meged

**Comment by dannywillems** [comment]
!ci-build-me

**Pull request merged**
