### PR TITLE
CI: Remove build of libp2p_helper that we never use

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR removes the job to build the `libp2p_helper` separately from the daemon. This uploads an artifact that we never use, so this is just wasting compute and storage resources.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by dkijania** [comment]
I've found some old TODO which states that we should use previously uploaded libp2p helper to avoid multiple rebuilding:

https://github.com/MinaProtocol/mina/blob/master/buildkite/scripts/build-artifact.sh#L20

I would propose to remove this comment as well if we decide not to use cache at all. On the other hand Andrew proposed it for some reason, right? There is a possibility to properly implement downloading libp2p helper and avoid rebuilding it. It was 4 years ago, so maybe the need for cache is no longer valid ?

After last discussion with @SanabriaRusso, looks like we are suffering to excessive number of IO ops against gcloud. Additionally  it is "only" 48 mb and 30 sec to build libp2p helper. If this is well known and we don't want to use cache just for those reasons then I'm ok with it.

**Comment by mrmr1993** [comment]
> On the other hand Andrew proposed it for some reason, right? There is a possibility to properly implement downloading libp2p helper and avoid rebuilding it. It was 4 years ago, so maybe the need for cache is no longer valid ?

Andrew wanted to cache the libp2p_helper in dockerfiles, using a layered docker image approach. We never did this, so we've just wasted resources running the job for 4 years.

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by dkijania** [comment]
Thanks, in that case I'm really happy to see that job to be retired

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by georgeee — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
Stale, closing.

**Pull request closed without merging**
