### PR TITLE
Configure chain quality grace period for berkeley release

### PR DESCRIPTION
**Pull request by nholland94**
This PR configures berkeley's grace period to 4.5 days, and ensures that the grace period works in hard forks.

The original code was hard coding the grace period in terms of a number of days, which would make the grace period unsafe under some network configurations. I exposed the grace period constant as a configuration in terms of slots, and ensured that the grace period end is accounting for enough slots in order to have a fresh sub window samples of the chain density. I also assert that the specified grace period is safe.

I also fixed a bug in the grace period logic where we weren't accounting for hard forks correctly. We were comparing the global slot since hard fork against a global slot since genesis when testing for the grace period. I fixed this and improved the types to add clarity.

I've confirmed the behavior manually by running a local network with 1/3rd of the stake online. The grace period end was computed as expected and the density only dropped after it was expected to.

### CODE REVIEW

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by sebastiencs** [comment]
@nholland94 That new `grace_period_slots` is ignored in `Protocol_constants_checked.to_input`, is that expected ?

If 2 `Protocol_state.Body` have a different value of `grace_period_slots`, they will still get the same hash (when calling `Protocol_state.Body.hash`)

https://github.com/MinaProtocol/mina/blob/d6cc26fd9466300833e3cc2d05a2921984e4254e/src/lib/mina_base/protocol_constants_checked.ml#L69-L76

**Comment by nholland94** [comment]
@sebastiencs That's a mistake, thanks for catching it! The `to_input` function should be destructuring it's input in order to avoid these kind of bugs. I'll put in a fix soon.

**Pull request merged**
