### PR TITLE
Update and repair broken links

### PR DESCRIPTION
**Pull request by Danyylka**
I hope my corrections will help you. Thank you for your work.

### CODE REVIEW

**Comment by dannywillems** [comment]
Thanks.
Can you do against the branch `compatible` please?

**Comment by Danyylka** [comment]
done

**Comment by Danyylka** [comment]
@dannywillems Could you please review my corrections?

I hope I was able to help in some way. Thank you for your work.

**Comment by dannywillems** [comment]
There are too many changes. You have to cherry-pick only your commit.

**Pull request closed without merging**
