### PR TITLE
Port lightnet suffix fix from develop to compatible

### PR DESCRIPTION
**Pull request by dkijania**
Port lightnet suffix fix from develop which was not merged to compatible

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
