### PR TITLE
prealfalfa ("3.0.0-RC1")

### PR DESCRIPTION
**Pull request by emberian**
This represents the prefinal integration of all outstanding berkeley-bound PRs, and includes what I need to release the tools to the node working group. "Prefinal" because internal devnet/mainnet UMT may reveal further tweaks necessary.

The only remaining thing to do, besides getting nightly green on this PR and performing a successful HF dry run or two, is to cut a build of compatible with the stop slots set for mainnet hardfork, once anyone can figure out when we'll be doing this. I leave this to the adults ;)

Closes https://github.com/MinaProtocol/mina/pull/15425 

Rolls up https://github.com/MinaProtocol/mina/pull/15421 and https://github.com/MinaProtocol/mina/pull/15408 and https://github.com/MinaProtocol/mina/pull/15425

### CODE REVIEW

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by dkijania** [comment]
Let's see if Ci is happy. prealfalfa is not a very fortunate name. I would prefer something more serious tbh 😂

**Comment by emberian** [comment]
Poor prealfalfa :( maybe something like prerelease?

**Comment by emberian** [comment]
Methodology for d2931ed:

 it removes the string "prealfalfa" from the codebase. instead, everywhere i found checks against release* or release/*, i added release-automation-testing.
additionally, instead of every untagged PR sharing the same unstable channel, now there is one channel per git short hash. 7 hex is a lot to conflict. it happens anyway because our repo is huge, but hopefully it's rare enough that this gets rid of deb-s3 issues forever.
then, the only thing is that we need to promote from these PR channels into unstable channel before we want to do releases of those types of things.

**Comment by emberian** [comment]
!ci-nightly-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-build-me

**Comment by emberian** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
