### PR TITLE
Merge berkeley with o1js-main

### PR DESCRIPTION
**Pull request by mitschabaude**
makes o1js compatible with berkeley

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-toolchain-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by shimkiv — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Review by querolita — APPROVED** [review]
crypto stamp here

**Comment by shimkiv** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]

**Pull request merged**
