### PR TITLE
12318 - Specify OFFLINE in rosetta docker-standalone-start.sh

### PR DESCRIPTION
**Pull request by kaozenn**

### CODE REVIEW

**Comment by kaozenn** [comment]
!ci-build-me

**Comment by kaozenn** [comment]
!ci-build-me

**Review by ylecornec — APPROVED** [review]

**Review by lk86 — APPROVED** [review]
The change is simple enough but I don't really understand the motivation, and it is a breaking change

**Comment by kaozenn** [comment]
It is not really needed but since Rosetta uses online and offline port, I thought it would be better to explicitly define them.
If it is a breaking change, we can just close this PR.

**Pull request closed without merging**
