### PR TITLE
Merge berkeley into main

### PR DESCRIPTION
**Pull request by mitschabaude**
o1js: https://github.com/o1-labs/o1js/pull/1405

### CODE REVIEW

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by shimkiv — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Review by nholland94 — APPROVED** [review]

**Comment by MartinMinkov** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by shimkiv** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by mitschabaude** [comment]
!ci-build-me

**Pull request merged**
