### PR TITLE
Remove unused frontier extensions

### PR DESCRIPTION
**Pull request by georgeee**
Explain your changes:
* Remove dead code extensions `Ledger_table` and `Identity`

Explain how you tested your changes:
* Tested on a private cluster
* Removing the code didn't cause a compilation error

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? Closes #13536

### CODE REVIEW

**Review by nholland94 — APPROVED** [review]
:skull_and_crossbones:

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
Redirected towards develop.

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
