### PR TITLE
OPAM packages in dune-project

### LINKED ISSUE #12928: .opam files, begone!
if you remove all the .opam files, and put a dune-project file in src, like this:
```
(lang dune 3.1)

(package (name allocation_functor))
(package (name archive_blocks))
(package (name base58_check))
(package (name bash_colors))
...
```
make build essentially succeeds. There's one compile error, presumably fixable.

### PR DESCRIPTION
**Pull request by psteckler**
Remove `.opam` in `src/`, and list OPAM packages in `src/dune-project`.

Closes #12928.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]
:confetti_ball:

**Comment by psteckler** [comment]
> I fail to see a `src/dune-project` file modified in the commits. Am I wrong?

https://github.com/MinaProtocol/mina/pull/12930/files#diff-91c11ff6d2b2e272d247eadb73cf15c633b33d10ae6915b536ca72265734f1d0

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
> I guess we need to add `(generate_opam_files true)` and it might generate the `opam.export`.

I tried adding that clause. If I then run `make build`, I don't see any files generated. If I run `dune build` in `src/`, it generates the `.opam` files that this PR deletes.

**Comment by psteckler** [comment]
CI passed here: https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/27600

**Review by rbonichon — APPROVED** [review]

**Pull request merged**
