### PR TITLE
Set delegate in new accounts

### PR DESCRIPTION
**Pull request by psteckler**
For new accounts created by zkApps, set the delegate to be the public key, if the account token is the default. That matches the strategy used when creating new accounts out-of-SNARK.

We were seeing SNARK failures for new accounts with delegate preconditions, because the delegate had not been set.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
