### PR TITLE
Cumulative nonce map in archive processor

### LINKED ISSUE #13401: Replayer should not use `mod` to calculate when next checkpoint should be written
Many slots do not contain blocks, so using `mod` can skip checkpoints.

Instead, have a current slot target, and when the target is met or exceeded, write the checkpoint, and reset the target.

### PR DESCRIPTION
**Pull request by psteckler**
When processing transactions in a block, the archive processor would update the initial nonce map, instead of cumulatively updating the nonce map passed through the fold accumulator. That meant if a fee payer was involved in more than one transaction in a block, the nonce would be wrong. If a transaction involved a public key not in the initial nonce map, the nonce would be missing.

In the replayer, instead of looking for `slot % interval = 0`, which often fails because not all slots have blocks, set a target slot. Issue a checkpoint file if the target is exceeded, and reset the target. Tested that feature by running the replayer on the mainnet db.

Also, remove warning flags from dune which hid some unused types and variables. Remove those unused items.

Closes #13401.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Review by bkase — APPROVED** [review]
Interesting, I'm surprised we managed to go this far with this bug

**Review by ymekuria — APPROVED** [review]

**Comment by jrwashburn** [comment]
After this fix, does the replayer need to be run across the entire db to get corrected nonces?

**Comment by psteckler** [comment]
> After this fix, does the replayer need to be run across the entire db to get corrected nonces?

@jrwashburn The nonces need to be repaired starting at the point where the bug was introduced. I don't know offhand when that was. Note that the invalid nonces don't affect the data migration for the berkeley hard fork, because the migrated db stores nonces differently.

**Pull request merged**
