### PR TITLE
Merge back to compatible

### PR DESCRIPTION
**Pull request by mrmr1993**

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Review by dkijania — CHANGES_REQUESTED** [review]
Apologies for hold this  PR, but i think we should fix master first before merging it to compatible. Especially scripts/debian/publish.sh can be problematic due to buster and mina-side car issues which i'm trying to fix in https://github.com/MinaProtocol/mina/pull/16246

**Comment by mrmr1993** [comment]
Stale, superseded. Closing.

**Pull request closed without merging**
