### PR TITLE
Kimchi_backend: extract the finalization of the lookup tables and add tests for Pickles.Fix_domains.domains

### LINKED ISSUE #14019: The cs must be finalized before computing the length of the fixed lookup tables in Pickles
With [14004](https://github.com/MinaProtocol/mina/pull/14004) merged, we can not use lookup tables in Pickles at the moment because the cs must be finalized before getting the fixed tables to compute the length.

Write also a test checking the computation is correct and domains can be called.

### PR DESCRIPTION
**Pull request by dannywillems**
Explain your changes:
* Fix #14019
* See comment of the git commit [Kimchi_backend: split the finalization](https://github.com/MinaProtocol/mina/pull/14022/commits/ee3d62eca35713117b68efc57c2d687c5796b5f4)

Explain how you tested your changes:
*

Previous ideas:
- Idea 1:
  - Call finalize before getting fixed and runtime table cfg: 171d4b7ae90f03d022b345e0a0be9aa9434845e9
  - Expose finalize in Kimchi_backend_common interface: fa4ce51d096bc58440d267f2b76e567132936cf3
  - The previous commit implies to put `finalize` and `finalize_and_get_gates` outside of the functor. We can do that using firs class modules.
  - The problem with finalizing might be it introduces a small overhead as it might not need to be finalized normally? Is finalize a heavy computation?

  Nop, doesn't work. It requires moving more things outside of the functor, like add_row.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Pull request merged**
