### PR TITLE
Bump ledger depth

### PR DESCRIPTION
**Pull request by mrmr1993**

### CODE REVIEW

**Comment by psteckler** [comment]
That's a huge difference, allowing 34 billion accounts. Is it needed?

**Review by bkase — APPROVED** [review]
We chatted about this and it seems like it adds a negligible amount of overhead and it is possible that this hardfork is the last time we can _ever_ change it without really big disruptions down the line.

**Review by nholland94 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
