### PR TITLE
[CI] Remove not important jobs from stable pipeline

### PR DESCRIPTION
**Pull request by dkijania**
Removing jobs which are not crucial and can fail a lot (like merges which are usually red on release branches) in stable run by adding `PipelineTag.Type.Stable` tag to all needed jobs

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
