### PR TITLE
Speed up ring sig test

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR tweaks the ring signature unit test so that it uses a faster pickles configuration for proving.

### CODE REVIEW

**Review by georgeee — APPROVED** [review]

**Comment by georgeee** [comment]
Test doesn't compile @mrmr1993

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
