### PR TITLE
Remove bad proof systems PR

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR
* reverts the breaking PR #14549,
* brings forward `proof-systems` to the PR before that, which works as intended
* brings in the remaining `proof-systems` PRs in `develop`, except for the broken https://github.com/o1-labs/proof-systems/pull/1263 (via https://github.com/o1-labs/proof-systems/pull/1378).

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by dannywillems** [comment]
Closing https://github.com/MinaProtocol/mina/pull/14655 as it was fixing Pickles with the change of the reverted PR.

**Review by dannywillems — APPROVED** [review]
Approving. I'll revert the changes in snarkyjs and snarkyjs-bindings.

**Comment by dannywillems** [comment]
I do confirm it solves the issue https://github.com/MinaProtocol/mina/issues/14657

**Pull request merged**
