### PR TITLE
Add sign coefficient in FFdd

### PR DESCRIPTION
**Pull request by querolita**
This PR adds a missing sign coefficient in the FFAdd gate.

### CODE REVIEW

**Comment by querolita** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by querolita** [comment]
!ci-build-me

**Review by jspada — APPROVED** [review]
lgtm

**Comment by querolita** [comment]
!ci-build-me

**Comment by jspada** [comment]
!ci-build-me

**Pull request merged**
