### PR TITLE
port compatible berkeley removal to dev

### PR DESCRIPTION
**Pull request by dkijania**
Port https://github.com/MinaProtocol/mina/pull/15951 to develop

### CODE REVIEW

**Review by dannywillems — APPROVED** [review]
LGTM for crypto-eng. Mostly arkworks and pickles PRs.

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by Trivo25 — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Pull request merged**
