### PR TITLE
Ignore git-ignored files when running pre-commit hooks

### LINKED ISSUE #9046: Pre-commit hooks check ignored files
Pre-commit hooks should not affect files that are ignored in `.gitignore` or `.git/info/exclude`.

### PR DESCRIPTION
**Pull request by A-Manning**
Closes #9046

### CODE REVIEW

**Comment by mimoo** [comment]
BTW I think we should get rid of the reformat package, similarly to this PR in the snarky repo: https://github.com/o1-labs/snarky/pull/589

**Comment by A-Manning** [comment]
> BTW I think we should get rid of the reformat package, similarly to this PR in the snarky repo: [o1-labs/snarky#589](https://github.com/o1-labs/snarky/pull/589)

Agreed.
Also, many of the remaining ignored paths should really be local, and not committed, much like `.git/info/exclude`.
If this is to be deprecated, there should be an ocamlformat equivalent for local exclusion.
Otherwise, I'd suggest that we transition to local git exclude lists, instead of polluting the codebase with unnecessary excludes.

**Comment by mimoo** [comment]
What do you mean by local excludes?

**Comment by A-Manning** [comment]
> What do you mean by local excludes?
One might specify files to be excluded from git in their `.git/info/exclude`, which is by default ignored by git.
This allows one to maintain custom files that are tracked, without needing to modify the `.gitignore`.

see https://git-scm.com/docs/gitignore

**Review by lk86 — APPROVED** [review]

**Comment by mrmr1993** [comment]
Old and stale, closing.

**Pull request closed without merging**
