### PR TITLE
updated brew lock file

### PR DESCRIPTION
**Pull request by Kida007**
Explain your changes here.
- updates brew lock file

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
@lk86 @mrmr1993 do ya'll see any problems with updating the lockfile?

**Comment by mrmr1993** [comment]
From Homebrew/homebrew-bundle#552:
> Starting with a caveat: we will never have a "proper" lockfile in Homebrew/homebrew-bundle that installs all your dependencies at exactly the versions you want because Homebrew doesn't work that way (and never will because e.g. pinning OpenSSL at the same version forever is a bad idea).
>
> [...] at a high-level this lockfile does is say "on this given configuration Homebrew/homebrew-bundle installed these versions of packages successfully". [...]

From what I can tell, it's not really a 'lockfile', as in it doesn't lock the dependencies to the ones we want. As such I don't think this changes anything -- other than us not having an untracked file in tree after running brew commands -- so I have no reason to oppose merging this.

If there's a reproducible package manager that we can use for our Mac CI, we should switch to that instead. This brew ideological stance keeps wasting time and resources by constantly breaking mac builds.

----------

(@bkase It seems like Mac CI is failing, albeit not related to this. This message is likely relevant:
Screenshot from 2020-12-20 23-47-32
)

**Comment by mrmr1993** [comment]
From Homebrew/homebrew-bundle#552:
> Starting with a caveat: we will never have a "proper" lockfile in Homebrew/homebrew-bundle that installs all your dependencies at exactly the versions you want because Homebrew doesn't work that way (and never will because e.g. pinning OpenSSL at the same version forever is a bad idea).
>
> [...] at a high-level this lockfile does is say "on this given configuration Homebrew/homebrew-bundle installed these versions of packages successfully". [...]

From what I can tell, it's not really a 'lockfile', as in it doesn't lock the dependencies to the ones we want. As such I don't think this changes anything -- other than us not having an untracked file in tree after running brew commands -- so I have no reason to oppose merging this.

If there's a reproducible package manager that we can use for our Mac CI, we should switch to that instead. This brew ideological stance keeps wasting time and resources by constantly breaking mac builds.

----------

(@bkase It seems like Mac CI is failing, albeit not related to this. This message is likely relevant:
Screenshot from 2020-12-20 23-47-32
)

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
