### PR TITLE
Merge "Hardfork package generation automation" into develop

### PR DESCRIPTION
**Pull request by nholland94**
Merges https://github.com/MinaProtocol/mina/pull/15082 into develop.

### CODE REVIEW

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Pull request merged**
