### PR TITLE
Rosetta CI fix

### PR DESCRIPTION
**Pull request by joaosreis**
Fixes Rosetta CI integration test.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-nightly-me

**Comment by joaosreis** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2609#019232bb-4920-41a9-b478-d011a5bb73f0

**Review by mrmr1993 — APPROVED** [review]

**Review by dkijania — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
