### PR TITLE
Merge master to berkeley

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR merges master to berkeley, the final step before landing the `berkeley` branch as `master` for the berkeley upgrade.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by mrmr1993** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2102

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
