### PR TITLE
Remove old version linter

### PR DESCRIPTION
**Pull request by psteckler**
The new linter is already merged to `berkeley`, so running the old one is redundant.

The old linter relied on printed representations of types, while the new one relies on the serialization formats of types. The new linter is in `scripts/version-linter.py`. It downloads type shape files associated with commits and compares shapes in the PR, base branch, and a release branch.

See RFC 0047.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]
Could you add some description on PR: what was the old linter doing, where is the new linter located and why wouldn't this merge disrupt anything?

**Comment by psteckler** [comment]
!ci-build-me

**Pull request merged**
