### PR TITLE
[Dev] Fix nightly + Port Promotion entrypoint fix

### PR DESCRIPTION
**Pull request by dkijania**
Port https://github.com/MinaProtocol/mina/pull/16085 to develop. Additionally while porting branch:

- Compatible is merged to develop
- Fixed Test develop compatibility

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by SanabriaRusso — APPROVED** [review]

**Review by dannywillems — APPROVED** [review]
Approving changes in lib/crypto for @MinaProtocol/crypto-eng-reviewers. It contains the changes from https://github.com/MinaProtocol/mina/pull/16091/

**Review by svv232 — APPROVED** [review]

**Comment by dkijania** [comment]
Bypassing branch protection as @svv232 already approved but his permissions are not allowing to pass review

**Pull request merged**
