### PR TITLE
Merge genesis_slot renaming into compatible

### PR DESCRIPTION
**Pull request by Sventimir**
Explain your changes:
* Resolve conflicts stopping merging of https://github.com/MinaProtocol/mina/pull/14263.

Explain how you tested your changes:
* It doesn't really make any changes, just makes makes merging of another PR possible.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes https://github.com/MinaFoundation/mina/issues/95

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by bkase** [comment]
!allowed-for-mainnet

**Comment by bkase** [comment]
!approved-for-mainnet

**Pull request merged**
