### PR TITLE
[Compatible][CI][Nightly] Making compatible green again

### PR DESCRIPTION
**Pull request by dkijania**
Introduced two changes which should make develop nightly green again:

- soft fail to hf test (while fixing is in progress)
- moving all integration tests to docker
- fixing terraform test

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-nightly

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
develop branch was merged to compatible so this PR is not needed

**Pull request closed without merging**
