### PR TITLE
Release/3.0.1

### PR DESCRIPTION
**Pull request by dkijania**
Merge release 3.0.1 to master

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by shimkiv — APPROVED** [review]

**Review by mrmr1993 — APPROVED** [review]

**Review by Trivo25 — APPROVED** [review]

**Pull request merged**
