### PR TITLE
Merge develop into o1js-main

### LINKED ISSUE #15444: Merge mina/develop into o1js-main without introducing incompatibiliy
~~Prerequisite for fixing https://github.com/o1-labs/o1js/issues/1374~~

EDIT: the issue above was resolved without merging develop, but merging develop is still important

### PR DESCRIPTION
**Pull request by mitschabaude**
proof systems: https://github.com/o1-labs/proof-systems/pull/2066

closes #15444

### CODE REVIEW

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-toolchain-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by shimkiv — APPROVED** [review]

**Comment by rbonichon** [comment]
@mitschabaude Unit tests are failing atm. Do you understand why?

**Comment by mitschabaude** [comment]
@rbonichon yes, last commit fixed it

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Review by rbonichon — APPROVED** [review]

**Pull request merged**
