### PR TITLE
Package batch zkapp txn tool [release/2.0.0]

### LINKED ISSUE #10963: cron job for generating burst of valid and invalid zkapp transactions

### PR DESCRIPTION
**Pull request by deepthiskumar**
-Package batch_zkapp_txn_tool.exe
-revive the cron job for the same from #11289 by @ghost-not-in-the-shell 

Created an issue for the todo #12067 

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #10963

### CODE REVIEW

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by lk86** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Pull request merged**
