### PR TITLE
[develop] Fix LFS errors + berkeley merge

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR fixes the diff errors against develop PRs by checking the relevant files into git LFS. This is the develop version of https://github.com/MinaProtocol/mina/pull/15284

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by emberian — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
