### PR TITLE
Build rosetta mainnet/devnet docker

### PR DESCRIPTION
**Pull request by dkijania**
Builds two versions of rosetta docker for mainnet and devnet networks (previously was build only for berkeley network)

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by SanabriaRusso — APPROVED** [review]
I guess you can relaunch the failing tests after merging the companion PR into `develop`.

Rest, lgtm

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Pull request merged**
