### PR TITLE
use explict field to differentiate slot_since_genesis slot_since_hard_fork

### LINKED ISSUE #14293: Address json serialization for global slots not differentiating between Since_genesis and Since_hard_fork

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR changes the field `curr_global_slot` to `curr_global_slot_since_hard_fork` in `consensus_state`. The purpose is to make it more clear that which kind of slot (since_genesis vs. since_hard_fork) is being used. It should not affect the usage of mainnet config.

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #14293

### CODE REVIEW

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by georgeee** [comment]
Lints job failed -- needs to be fixed

This fix might break compatibility of `berkeley` with ITN, but this is probably fine.

**Review by georgeee — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Pull request merged**
