### PR TITLE
[berkeley] Relax certain replayer checks at some slots

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR is #15254 merged into berkeley.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
Force-push: I had the wrong branch checked out locally

**Review by emberian — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
