### PR TITLE
Resurrecting lookup PR: Fix lookup has_zero_entry bug

### PR DESCRIPTION
**Pull request by volhovm**
Updating `proof-systems` to contain this bugfix:
- `proof-systems` PR: https://github.com/o1-labs/proof-systems/pull/1567

### CODE REVIEW

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
OK, so it contains a bug that CI doesn't catch! Will look into it.
```
======================================================================
TEST_MODULE at file "src/lib/pickles/wrap.ml", line 541, characters 4-358: lookup threw
(Failure
  "called `Result::unwrap()` on an `Err` value: ConstraintSystem(\"The table with id 0 must have an entry of all zeros\")").
  Raised at Base__Exn.protectx in file "src/exn.ml", line 71, characters 4-114
  Called from Ppx_inline_test_lib__Runtime.Module_context.with_ in file "runtime-lib/runtime.ml", line 165, characters 6-10
  Re-raised at Ppx_inline_test_lib__Runtime.Module_context.with_ in file "runtime-lib/runtime.ml", line 169, characters 6-13
  Called from Ppx_inline_test_lib__Runtime.test_module in file "runtime-lib/runtime.ml", line 527, characters 12-677
  in TEST_MODULE at file "src/lib/pickles/wrap.ml", line 286, characters 0-14270: gate finalization
```

**Comment by volhovm** [comment]
I confirm the tests passing locally in addition to the CI.

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
Note: https://github.com/MinaProtocol/mina/pull/14637 moves to alcotest and will conflict with this PR.

**Review by dannywillems — APPROVED** [review]

**Pull request merged**
