### PR TITLE
Imposing hard timeout of Rosetta integration test

### PR DESCRIPTION
**Pull request by SanabriaRusso**
Explain your changes:
* Proposed an initial timeout to Rosetta local integration tests.
  * While the flakiness of the test is being studied, this prevents the pipeline from getting stuck for the default timeout (`6h`), freeing up the allocated agent.

Explain how you tested your changes:
* Running nightly.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by SanabriaRusso** [comment]
[Nightly](https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2728)

**Review by dkijania — APPROVED** [review]

**Comment by SanabriaRusso** [comment]
!ci-build-me

**Comment by SanabriaRusso** [comment]
!ci-build-me

**Comment by SanabriaRusso** [comment]
!ci-build-me

**Comment by SanabriaRusso** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
