### PR TITLE
[DEVELOP] Explicitly declare missing daemon runtime configuration

### PR DESCRIPTION
**Pull request by martyall**
port of #16163 to develop to fix `merges cleanly` check

### CODE REVIEW

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-nightly-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by martyall** [comment]
!ci-build-me

**Pull request merged**
