### PR TITLE
Add vesting accounts to hard fork test

### LINKED ISSUE #13811: Hard fork test- test vesting schedules from previous chain

### PR DESCRIPTION
**Pull request by psteckler**
Add vesting accounts to hard fork integration test.

- timed1 fully vests before the hard fork
- timed2 has cliff before the hard fork
- timed3 has cliff at hard fork

Check that total, locked, liquid balances all comport with the vesting schedule.

The hard fork test is not part of PR CI, it's in the nightly CI. Here's a successful run from an earlier draft PR: https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/30221#018a6660-58c9-440c-9638-6b89876c96ce

Closes #13811.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
