### PR TITLE
Removing Delegation Backend unit test and reference to container image

### PR DESCRIPTION
**Pull request by SanabriaRusso**
Explain your changes:
* Removed non required test's Dhall and container reference from Buildkite's Constants.
* The Container image was removed from the registry.

Explain how you tested your changes:
*A successful CI run is expected

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by dkijania** [comment]
i think this pr is no longer needed

**Pull request closed without merging**
