### PR TITLE
Add indexer feature to Rosetta

### PR DESCRIPTION
**Pull request by joaosreis**
This PR implements Rosetta indexer feature. This endpoint (`/search/transactions`) allows searching for transactions matching certain conditions. The specification can be found [here](https://docs.cloud.coinbase.com/rosetta/reference/searchtransactions). Some existing logic was moved around to allow it to be reused by different endpoints. 
This has been tested by manually calling the endpoint and comparing the response with the expected result. This PR also includes a property-based test executable that takes a postgres URI to an archive DB and checks this implementation against the defined properties.

### CODE REVIEW

**Review by joaosreis — COMMENTED** [review]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-toolchain-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Review by Sventimir — APPROVED** [review]
Looks okay to me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by dkijania** [comment]
Hey @joaosreis.  Is indexer_test app used in CI ? from description looks like it need archive_uri so i guess it is component test on real postgres data. Where i can see it run?

**Comment by joaosreis** [comment]
@dkijania it's not used in CI for that specific reason, it needs to connect to an archive DB. Locally, I've ran it against `qanet` and `devnet` archive DBs.

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
Adding the indexer test to CI will be worked on #15641

**Review by dkijania — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
