### PR TITLE
Remove mina-sidecar from repo

### PR DESCRIPTION
**Pull request by dkijania**
Removing stale app mina-sidecar from repository

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
