### PR TITLE
Remove TestnetAlerts and new VersionLint logic to check against each mainline branch

### PR DESCRIPTION
**Pull request by dkijania**
Removing testnet alerts jobs since it is not used and occasionally failing. Modifies Version lint logic to check against each mainline branch

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
