### PR TITLE
[berkeley] Remove test directory in kimchi/js

### PR DESCRIPTION
**Pull request by dannywillems**
Explain your changes:
* Berkeley counterpart of https://github.com/MinaProtocol/mina/pull/13772. See issue https://github.com/MinaProtocol/mina/issues/13771. Depends on https://github.com/o1-labs/snarkyjs/pull/1055 and https://github.com/o1-labs/snarkyjs-bindings/pull/99

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by dannywillems** [comment]
!ci-build-me

**Review by jspada — APPROVED** [review]
seems fine

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
Closing, see https://github.com/MinaProtocol/mina/issues/13771#issuecomment-1731186314

**Pull request closed without merging**
