### PR TITLE
Fix debian branch name logic dev

### PR DESCRIPTION
**Pull request by dkijania**
We made an mistake in logic of branch name setting which slip through review. Fixing it now

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
