### PR TITLE
Property-Based Tests for functions target_nonce_on_success, nonce_increments and check_authorization

### LINKED ISSUE #12849: [zkapp_command] Tests for target_nonce_on_success and nonce_increments  and check_authorization functions
Tests for `target_nonce_on_success` , `nonce_increments` and `check_authorization` functions.

### PR DESCRIPTION
**Pull request by ejMina226**
Property-Based Tests for functions `target_nonce_on_success`, `nonce_increments` and `check_authorization` in `zkapp_command.ml`

* Closes #12849

### CODE REVIEW

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
Decided not to add a PBT for `check_authorization` as there were no invariants to consider.

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by ejMina226** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by ejMina226** [comment]
!ci-build-me

**Comment by ejMina226** [comment]
@georgeee Should this go into develop or berkeley? Thanks.

**Pull request merged**
