### PR TITLE
Update the generated code.

### PR DESCRIPTION
**Pull request by Sventimir**
This PR just commits changes done automatically by the compilation process.

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by mimoo** [comment]
weird, it looks like this is because the ocaml-gen version was reverted?

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by mimoo** [comment]
I still don't understand this change btw, I'm reverting it here: https://github.com/MinaProtocol/mina/pull/12211 because now the wrong generated files are in the repo

**Pull request merged**
