### PR TITLE
Port local debian build dev

### PR DESCRIPTION
**Pull request by dkijania**
port https://github.com/MinaProtocol/mina/pull/15899 to develop

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by dkijania** [comment]
after merge from compatible to develop, it is no longer needed

**Pull request closed without merging**
