### PR TITLE
Change node imports for builtin modules that use an absolute URL

### PR DESCRIPTION
**Pull request by MartinMinkov**
Changes the import URL for imports that use an absolute URL for node builtins. 

Currently, the absolute URL for node builtins causes errors with JavaScript bundling tools like Webpack, which was noted particularly by Auro wallet. This PR simply removes the absolute `node` reference in the import URL.

### CODE REVIEW

**Review by mitschabaude — APPROVED** [review]

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by MartinMinkov** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Pull request merged**
