### PR TITLE
zkapp update timing command  in test_zkapp_transaction (berkeley)

### PR DESCRIPTION
**Pull request by dkijania**
Same as #13318

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
