### PR TITLE
[Dev] Update logo and description for README.md

### PR DESCRIPTION
**Pull request by dkijania**
Port https://github.com/MinaProtocol/mina/pull/15891 to develop

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by MartinMinkov — APPROVED** [review]

**Pull request merged**
