### PR TITLE
Heap usage app

### PR DESCRIPTION
**Pull request by psteckler**
App to print heap sizes of some types of interest in the Mina codebase.

Sample output: 
```Data of type Account.t (w/ zkapp)                 uses    213 heap words =    13632 bytes
Data of type Zkapp_command.t                      uses  52739 heap words =  3375296 bytes
Data of type Ledger.Db.path.t                     uses    122 heap words =     7808 bytes
Data of type Protocol_state.t                     uses    337 heap words =    21568 bytes
Data of type Pending_coinbase.t                   uses    307 heap words =    19648 bytes
Data of type Staged_ledger_diff.t (payments)      uses    730 heap words =    46720 bytes
Data of type Parallel_scan.Base.t (coinbase)      uses    530 heap words =    33920 bytes
Data of type Parallel_scan.Base.t (payment)       uses    688 heap words =    44032 bytes
Data of type Parallel_scan.Base.t (zkApp)         uses  54304 heap words =  3475456 bytes
Data of type Parallel_scan.Merge.t                uses   8067 heap words =   516288 bytes
```

Moved the transaction generation code from `Transaction_snark_profiler` to a library, `Snark_profiler_lib`. The function `create_ledger_and_zkapps` now takes an optional `num_proof_updates`, default 0.

This app could be run in CI, and we could see the effect that changes to these types would have on memory usage.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]
Nice!

**Pull request merged**
