### PR TITLE
Remove some submodules in favour of opam pins

### PR DESCRIPTION
**Pull request by balsoft**
Get rid of three submodules, replacing them with opam pins.

Submodules slow down the checkout, and are often annoying when switching branches. Replace them with opam pins.

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by psteckler** [comment]
We had `async_kernel` and `rpc_parallel` pinned because we had local changes to those libraries.

If we're using stock versions of those libraries, we don't need to pin them, just as we don't pin most other OPAM packages.

Are we discarding those local changes?

**Comment by mrmr1993** [comment]
> If we're using stock versions of those libraries, we don't need to pin them, just as we don't pin most other OPAM packages.
> 
> Are we discarding those local changes?

They're being pinned from our github repos rather than submodules: https://github.com/MinaProtocol/mina/pull/11220/files#diff-4e59d97a11c5f0a15ddcb8dac12467e33c0a2730c176efe8969358b7fd566a28R376.

It makes them more annoying to update, but should reduce friction for everyone else when there are updates (since it's just an `opam switch import` with no submodule pins).

**Comment by psteckler** [comment]
> They're being pinned from our github repos rather than submodules: [#11220 (files)](https://github.com/MinaProtocol/mina/pull/11220/files#diff-4e59d97a11c5f0a15ddcb8dac12467e33c0a2730c176efe8969358b7fd566a28R376).

Ah, thanks for clarifying.

**Comment by robinbb** [comment]
No changes in 14 days, @balsoft ? Does this mean that you are not working on this PR? Perhaps it should be marked as a draft, if so.

**Comment by yorickvP** [comment]
Companion: #11388

**Pull request merged**
