### PR TITLE
Rosetta artifact and documentation update + cleanup

### PR DESCRIPTION
**Pull request by joaosreis**
This pull request includes several commits related to Rosetta. Summary of changes:

 * Decomission network-specific scripts.
 * Fix issues with Docker entrypoint and download missing blocks scripts.
 * Remove unused files from Rosetta dir and move scripts into a subdir.
 * Update README.
 * Update genesis ledger for devnet.
 * Add example .env files for public networks.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-nightly-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-nightly-me

**Comment by joaosreis** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1852

**Comment by joaosreis** [comment]
I forgot one last commit, had to retrigger build

**Review by Sventimir — COMMENTED** [review]
Nothing suspicious that I could spot, but I'd be more comfortable if someone else approved it.

**Comment by joaosreis** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by kaozenn** [comment]
Adding berkeley.env, mainnet.env and refactoring devnet.env with latest URLs

**Comment by kaozenn** [comment]
@joaosreis the Rosetta artefact script used to have 2 different daemon , with 2 profiles (`mina` and `mina-dev`)
where `-dev` was handled by an ENV_VAR `MINA_SUFFIX`
It looks that it is no longer required. Would the same rosetta / mina daemon work on both mainnet and devnet/berkeley ?

**Comment by joaosreis** [comment]
@kaozenn current images seem not to have this `mina-dev` binary anymore. The node should be able to connect to berkeley/devnet, but this version is incompatible with mainnet until hard fork.

**Comment by kaozenn** [comment]
Understood. Out of curiosity, does it means the devnet/mainnet profiles are no longer used anymore? Or only one of them is used?

**Comment by kaozenn** [comment]
I have tested against Berkeley. Although there are currently some issues with the Berkeley SQL Dumps. The Rosetta image performs as expected

**Review by kaozenn — APPROVED** [review]

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
