### PR TITLE
Move merges cleanly check from berkeley do master

### PR DESCRIPTION
**Pull request by dkijania**
Since we are not using actively berkeley branch and we are fallback to having develop,compatible,master branches, we need to also convert merges cleanly check from berkeley to master

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
Hello, @dkijania 1 new  created to help you port this change to master. Please follow steps to resolve conflict for each mainline branch. PRs will be created automatically after you push merge to porting branches

  
## develop 

```
git fetch
git checkout port_ci/master/move_merges_cleanly_check_from_berk_to_master_to_develop
git merge ci/master/move_merges_cleanly_check_from_berk_to_master
(Resolve conflict)
git push
```

**Comment by dkijania** [comment]
Porting branch #15764 to resolve conflict with develop created. Please merge it in order to solve conflict between head of this PR and develop

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
Porting branch #15765 to resolve conflict with develop created. Please merge it in order to solve conflict between head of this PR and develop

**Review by SanabriaRusso — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
