### PR TITLE
Fix bootstrap long async cycle

### PR DESCRIPTION
**Pull request by nholland94**
When nodes go through Bootstrap, they synchronize two ledgers. After each of these two ledgers is synced, some processing is being executed. On large ledger network (~140k accounts) this processing produced long async jobs of 5-7 minutes.

This issue fixes another part of #13783.

Explain your changes:
* Rewrite after-bootstrap processing to remove expensive processing of entire ledger

Explain how you tested your changes:

Tested on a private cluster with ~140k accounts in ledger.

Before the fix long async job was present each time node was restarted with `.mina-config` wipe-out. After the fix, this long async job was no more detected.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None, only partially addresses one

### CODE REVIEW

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
I created this issue if https://github.com/MinaProtocol/mina/issues/13908 is merged.

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by nholland94** [comment]
@ghost-not-in-the-shell 
> Is the snarkyjs changes intended?
Yes, the change to the ledger interface here broke the snarkyjs tests.

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!approved-for-mainnet

**Pull request merged**
