### PR TITLE
Make internal_tracing.context_logger a public lib

### PR DESCRIPTION
**Pull request by georgeee**
This resolves a circular package-to-package dependency between mina_base and internal_tracing.

_Clarification_

It's package-to-package circular dependency, not libray-to-library.
Dune handles it well.
But dependency diagram becomes way less readable, also it makes packages incompatible with findlib-based installation approach (because one can't install packages one by one, they depend on one other).

Explain how you tested your changes:
* Mina compiles

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Review by rbonichon — APPROVED** [review]
I think this change is okay. Approving

**Comment by georgeee** [comment]
!ci-build-me

**Review by mrmr1993 — COMMENTED** [review]
This direction of travel feels wrong. When would anybody ever install `internal_tracing_context_logger` in opam? We should probably hang everything under a very small list of public libraries (`mina_base`, `mina_lib`, `pickles`, etc.) instead of spewing more of our libraries' guts into public.

**Comment by georgeee** [comment]
@mrmr1993 I am also not happy about a great zoo of libraries we currently have.

This PR's purpose isn't to introduce a library per se, but to break a package dependency cycle:

1. `internal_trace` depends on `mina_base` (namely `State_hash` module is used)
2. `mina_base` depends on `pickles`
3. `pickles` depends on `internal_trace.context_logger`

So on private library level there is no dependency conflict, however on Ocaml package level there is a cycle `internal-trace` -> `mina_base` -> `pickles` -> `internal_trace`.

This is the last conflict of such type in our codebase (I removed a number of other such conflicts in previous PRs).

While it could be possible that we change code of `internal_trace` library so that it doesn't use `mina_base` or any other package with dependency on anything from `internal_trace` package, I decided to avoid seeking such a code change and take a compromise of making one more library public.

I agree that we do have far too many public packages, but any refactoring that will attempt to reduce their number should stick to the rule that there are now private-library cross-dependencies between packages. I'm not attempting such a refactoring at the moment, but I want to establish that there are no package-to-package dependency cycles anymore.

**Comment by georgeee** [comment]
!ci-build-me

**Pull request closed without merging**
