### PR TITLE
Function to preserve sign for 0

### LINKED ISSUE #14452: Load_data reads negative 0 as 0
This causes replayer to fail.

### PR DESCRIPTION
**Pull request by psteckler**
Add `Amount.Sign.create_preserve_zero_sign`, to allow replayer to load negative zero from database.

This approach allowed replayer to succeed on ITN database.

Closes #14452.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Review by georgeee — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Pull request merged**
