### PR TITLE
Standardise variable names in pickles

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR renames some of the variables in pickles, to improve the confusing terminology around `branches` vs `branchings`, `widths` vs `heights` etc. The changes are
* `choices` becomes `rules`
* `branches` becomes `num_rules`
* `branchings` becomes `num_parents`
* `width` becomes `num_parents`
  - `widths` becomes `prev_num_parentss` etc.
* `height` becomes `num_rules`
  - `heights` becomes `prev_num_ruless` etc.
* `local_signature` becomes `prev_max_num_parentss`

with a few other related changes. For me, this makes it significantly easier to reason about the code.

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by imeckler** [comment]
I like this except -- and I feel funny typing this -- maybe "parents" should be "children"? Because in the tree of proofs they really are the children... Or maybe predecessors?

**Comment by mrmr1993** [comment]
> maybe "parents" should be "children"

I had in mind that they exist first, and the next proof 'up' can't be 'born' without them (to stretch the analogy). Predecessors is closer to it, but it feels a bit unweildy.

Perhaps it makes sense to just be explicit; how do you feel about `input_proofs` (so `num_input_proofs`, `num_input_proofss` etc.)?

**Comment by mrmr1993** [comment]
> Perhaps it makes sense to just be explicit; how do you feel about `input_proofs` (so `num_input_proofs`, `num_input_proofss` etc.)?

This is now done.

**Comment by mrmr1993** [comment]
We should very much still do this, but this is stale. Converting to draft.

**Comment by mrmr1993** [comment]
This will need to be re-done from scratch. Closing.

**Comment by glyh** [comment]
Is `proofss` typo or intentional?

**Pull request closed without merging**
