### PR TITLE
PR mainnet gating for build-me-bot

### PR DESCRIPTION
**Pull request by bkase**
Adds a new pipeline and soon a status-check for mainnet gating of PRs into the ci-build-me-bot.

I'll use this PR to test the logic of the bot.

### CODE REVIEW

**Comment by es92** [comment]
!approved-for-mainnet

**Comment by bkase** [comment]
@es92 's approval confirms it works 👍 

Screen Shot 2021-01-28 at 1 22 29 PM


(also see https://buildkite.com/o-1-labs-2/mina-pr-gating/builds/1#7d4f40ae-531c-423c-aa33-0dbd29e8385f )

**Comment by bkase** [comment]
!ci-build-me

**Review by es92 — APPROVED** [review]

**Review by mrmr1993 — APPROVED** [review]
Bot changes lgtm

**Pull request merged**
