### PR TITLE
Update Rosetta models and code for 1.4.7

### PR DESCRIPTION
**Pull request by omerzach**
- Update `rosetta_models` to version 1.4.7 using code generator and undo
      any undesired changes (like removal of annotations)    - Remove `coins` field from `AccountBalanceResponse`
    - Make `status` field on `Operation` optional (essentially wrap in
      `Some` throughout and wrap certain `String.equal` calls with
      `Option.equal`)
    - Make `ConstructionMetadataRequest` `options` field optional (but just
      error out if it's not set)
    - Add `description` to `Errors` (initially set to the same thing as
      `message`, but Rosetta allows `description` to be modified whenever
      we choose)
    - Set values for new `historical_balance_lookup`, `call_methods`,
      `balance_exemptions`, and `mempool_coins` fields in network options
    - Set temporary value for new `timestamp_start_index` field in network
      options along with TODO+issue describing how to implement it correctly
      in the future

Tested changes using the Rosetta test runner.

Checklist:

- [x] Document code purpose, how to use it
- [x] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them:

### CODE REVIEW

**Comment by psteckler** [comment]
Note that #6760, not yet merged, makes some changes to the Rosetta code.

**Review by bkase — APPROVED** [review]

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!ci-build-me

**Review by bkase — APPROVED** [review]

**Pull request merged**
