### PR TITLE
Public keys only when default token implicit

### PR DESCRIPTION
**Pull request by psteckler**
In archive db schema, revert uses of account identifiers where the token is implicitly the default; use just the public key. Using account identifiers introduces the possibility of error, and increases friction between the OCaml code and the archive database -- the default token has to be manually added.

Leave account identifiers where there is the possibility of a custom token, such as in the `accounts_accessed` table.

### CODE REVIEW

**Review by deepthiskumar — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Pull request merged**
