### PR TITLE
[Rosetta] Add user transactions nonce to metadata response

### PR DESCRIPTION
**Pull request by joaosreis**
This pull request adds the user transactions nonce to Rosetta's metadata response.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-docker-me

**Comment by joaosreis** [comment]
!ci-build-me

**Review by piotr-iohk — APPROVED** [review]
LGTM.

**Pull request merged**
