### PR TITLE
Fail the build on error match in output

### PR DESCRIPTION
**Pull request by dkijania**
Applied fix from https://github.com/MinaProtocol/mina/pull/16170 + fixed snark profiler test to detect any errors occurence in log and fail the build. This change goes with porting to master as all CI fixes should be applied to master as well

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
related to: https://github.com/MinaProtocol/mina/pull/16165

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Pull request merged**
