### PR TITLE
[Berkeley] Handle 'unused' non-optional gates correctly in pickles

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR bumps proof-systems to include the fix in https://github.com/o1-labs/proof-systems/pull/1107. This builds upon https://github.com/MinaProtocol/mina/pull/13530, which makes this fix possible.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by rbonichon — APPROVED** [review]

**Review by querolita — APPROVED** [review]

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build0-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
Force-pushed to remove a bunch of rebase junk that crept in.

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
Merging through script with missing edge-case. The fix is in https://github.com/MinaProtocol/mina/pull/13670, but blocked by requested changes.

**Pull request merged**
