### PR TITLE
[berkeley] Filtered logs to berkeley

### PR DESCRIPTION
**Pull request by SanabriaRusso**
Importing PR #15229 to Berkeley

This was causing errors while running integration tests for the release of toolchains: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1742#018e9b48-4eb3-4feb-ac8d-5260dfa21064/52-196

### CODE REVIEW

**Comment by SanabriaRusso** [comment]
Associated nightly run: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1748#018e9dd8-479f-43fc-80be-1eafd7a16d83

**Comment by SanabriaRusso** [comment]
!ci-build-me

**Comment by SanabriaRusso** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by emberian** [comment]
!ci-build-me

**Pull request closed without merging**
