### PR TITLE
Upgrade libp2p (redo)

### PR DESCRIPTION
**Pull request by nholland94**

### CODE REVIEW

**Comment by nholland94** [comment]
!ci-build-me

**Comment by georgeee** [comment]
@nholland94 are you going to include commit that relaxes the `all_ipc.ml` test?

Also, may I suggest (for clear look) to cherry-pick commits instead of reverting the reverts?

**Comment by nholland94** [comment]
@georgeee I'll redo the history. The changes to relax the test are already in, but the history makes it confusing.

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
