### PR TITLE
Consolidate the MLH files

### PR DESCRIPTION
**Pull request by martyall**
## Changes

We are working toward removing the compile time configuration. It is currently difficult to tell what precise configuration is being used for a given profile — the style of imports and undefs are contributing to this. As an intermediate step I consolidated all of the configuration into one file per build profile, ultimately to be replaced by a standard yaml/json file. It’s now safe to delete the old files as wel.

For fields that were previously imported, I converted them to blocks with comments to identify the original location, e.g

```
(*BEGIN src/config/txpool_size.mlh*)
(* Note this value needs to be consistent across nodes to prevent spurious bans.
   see comment in transaction_pool.ml for more details. *)
[%%define pool_max_size 3000]
[%%undef zkapp_cmd_limit]
(*END src/config/txpool_size.mlh*)

```

# NOTE
It would have been insane to try to do this by hand. [I wrote a little Purescript script](https://github.com/martyall/mlh-consolidator) to accomplish this task, it is easier to audit that than to try to cross reference the values with the original files (though feel free to do that if you have the energy).

### CODE REVIEW

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Review by rbonichon — APPROVED** [review]
Love it!

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by georgeee** [comment]
Awesome work!

**Review by georgeee — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Review by nholland94 — APPROVED** [review]

**Comment by martyall** [comment]
!ci-build-me

**Pull request merged**
