### PR TITLE
[Develop] Port Replayer: convert global slots to avoid to hashes in order to support devnet

### PR DESCRIPTION
**Pull request by dkijania**
Porting to develop https://github.com/MinaProtocol/mina/pull/15302

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
On the other hand why we need to avoid current mainnet and devnet block in berkeley replayer?

**Pull request merged**
