### PR TITLE
Fix Wasm build

### PR DESCRIPTION
**Pull request by mitschabaude**
snarkyjs: https://github.com/o1-labs/snarkyjs/pull/946
bindings: https://github.com/o1-labs/snarkyjs-bindings/pull/31

### CODE REVIEW

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Pull request merged**
