### PR TITLE
Use the correct values for the fork config

### PR DESCRIPTION
**Pull request by mrmr1993**
In particular:
* we want to use the best tip's hash
* the genesis block already has blockchain length set to the fork's blockchain length, so we're double counting if we manually attempt to do it here.

This change makes these so. It works out actually simpler than the code that was written.

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
The scope of this is now reduced after the merge of #15079. Between the 2 PRs, this fixes
* the state hash, which is now for the given block instead of its parent,
* the blockchain length, where the offset calculation doubles up the calculation done in the [genesis ledger setup](https://github.com/MinaProtocol/mina/blob/a6745833668b5d704d18ff1f50a7d0f8af71dfa4/src/lib/consensus/proof_of_stake.ml#L2071),
* the export of the genesis configuration, where we actually want to use the configuration specified by the mainnet or devnet compile configurations, and so we remove it entirely.

**Review by emberian — APPROVED** [review]

**Comment by mrmr1993** [comment]
This PR now represents the merge-back of https://github.com/MinaProtocol/mina/pull/15109.

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
