### PR TITLE
K8s preemption change dev

### PR DESCRIPTION
**Pull request by QuiteStochastic**
https://github.com/MinaProtocol/mina/pull/13766

### CODE REVIEW

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Pull request merged**
