### PR TITLE
[Rosetta] add test for  mina-indexer 

### PR DESCRIPTION
**Pull request by dkijania**
This PR adds automated test for Rosetta indexer.

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-toolchain-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
