### PR TITLE
Child_processes: ensure stderr/stdout get flushed

### PR DESCRIPTION
**Pull request by emberian**
This ensures that libp2p_helper output does not get lost when the process crashes. Tested by adding a variable-length sleep+panic to the helper and never losing the stderr output over a few runs.

Follow up to #14397  I believe?

### CODE REVIEW

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Review by nholland94 — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Review by deepthiskumar — CHANGES_REQUESTED** [review]
Waiting for rampup8 release

**Comment by emberian** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
@emberian please raise if any of the integration test triggered by `ci-nightly-me` fails https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1083

**Pull request merged**
