### PR TITLE
Remove buster support

### PR DESCRIPTION
**Pull request by dkijania**
Since buster is EOL: https://endoflife.date/debian. We are removing support for it in CI

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by georgeee** [comment]
We need this change. It currently blocks building toolchain containers.

**Review by georgeee — APPROVED** [review]

**Comment by georgeee** [comment]
P.S. some dhall lints are due (see nightly CI) @dkijania

**Comment by dkijania** [comment]
@georgeee fixed and rerun nightly directly from buildkite:

https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2410

Linta are green

**Comment by georgeee** [comment]
@dkijania is "Rosetta integration tests Bullseye Long" something that is broken in nightly disregard to this PR?

**Comment by dkijania** [comment]
Yes ! That's why I have another PR for making it soft fail

**Pull request merged**
