### PR TITLE
Fix/merge 13654 to develop

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
allow clean merge of #13654 to develop

### CODE REVIEW

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]

**Comment by nholland94** [comment]
!approved-for-mainnet

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by nholland94** [comment]
These changes are already in develop in a separate cherry-picked commit, so I am closing this 0 diff PR.

**Comment by nholland94** [comment]
It turns out that this merge was required even though it's a 0 line diff.

**Pull request merged**
