### PR TITLE
Remove trust system

### LINKED ISSUE #11723: Remove trust system from daemon
The trust system in the daemon is a full subsystem for trust scoring, handling peer actions, persisting scores, and banning peers. However, we have been moving away from it over time as our main source of granular peer scoring logic. Right now, we only trigger insta-bans through it, and everything else is a noop. It creates a lot of noisy logs, some of which are meaningless, and most of which are misleading. We also have had some occasional issues with it, so it doesn't make sense to continue maintaining such code.

We should just rip out from the daemon given the fact that we are transferring trust scoring responsibilities to the libp2p_helper over time. The module can just be deleted, and all the call sites into can be replaced with either logs or calls to the networking library to enact bans.

### PR DESCRIPTION
**Pull request by psteckler**
Rip out the `Trust_system` library. 

Add code to ban peers (in `Gossip_net`, `Mina_net2`, and `Mina_networking`) and, in almost all cases where the trust system performed "instabans", ban misbehaving peers. Whenever a peer is banned, it is un-banned one day later. Banned peers received a notification via the `Ban_notify` RPC.

`V1` and `V2` of the `Get_node_status` RPC have been removed, because they contained ban statuses from the trust system. The new `V3` contains a list of banned peers and their ban expirations.

Closes #11723.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
Very stale, closing.

**Pull request closed without merging**
