### PR TITLE
[COMP] Removed Test executive dockers and buster debian

### PR DESCRIPTION
**Pull request by dkijania**
Port https://github.com/MinaProtocol/mina/pull/15908 to compatible

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by svv232 — APPROVED** [review]

**Review by georgeee — APPROVED** [review]

**Review by amc-ie — APPROVED** [review]
Thanks Dariusz!

**Pull request merged**
