### PR TITLE
Zkapp generator improvements

### LINKED ISSUE #14168: Insufficient amounts in experiment
```
[2023-9-20 06:27:37.713239]Mina_graphql__Itn_zkapps: Error $error creating zkapp transaction,
stopping handle 027d8799-91da-4fe9-4996-c21684c533f1
$error = {"commit_id":"668f8ed87ca0be865497f46ca291d3b809629c3d","exn_name":"Failure","exn":
["Failure","add_balance_and_balance_change: underflow for difference"]}

{"data":"7mXNYjwGzwzut2mc8g9LcGxXAQZKEKtQBU1tgPp7GUc2XwzVbWcJHXeUSXGHVjLsdMVdz7DJVN35VBd6WirYMdbix777TdLz",
"status":["Failed",[[["Amount_insufficient_to_create_account"]]]]}

```

### PR DESCRIPTION
**Pull request by georgeee**
Explain your changes:
* Fix some inconsistencies in zkapp generator
* Update balance allocation and add a unit test for the generator
* Support assigning different fee parameters to payments and zkapps

Together, this changes enabled a successful 72-hour test on the large cluster.

Explain how you tested your changes:
* Tested on a cluster of 200 nodes, results [here](https://docs.google.com/spreadsheets/d/1QhYJTHLOs0rGuMzIztd_mYSBXxkfHrecJisp9PMWMbU/edit#gid=1589233045)

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues?

* Closes #14168

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Review by MartinMinkov — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
