### PR TITLE
Reduce the timeout for the Nodes_to_synchronize wait condition

### PR DESCRIPTION
**Pull request by mrmr1993**
This wait condition usually runs very quickly, and we only see the timeout being hit when the test infrastructure has failed. With the previous timeout of 48 slots, this takes 1.6 hours. Reducing this significantly should help with long-running failed tests.

The numbers here are chosen arbitrarily. Really, the time it takes should depend on the known state of the nodes entering the wait condition, accounting for the number of blocks to be bootstrapped / caught-up to, but I don't want to do that in this first pass.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by QuiteStochastic — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
Nightly run: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/563

**Comment by mrmr1993** [comment]
This merged by another route, and this PR is now empty. Closing.

**Pull request closed without merging**
