### PR TITLE
Archive script needed for emergency hardfork

### PR DESCRIPTION
**Pull request by dkijania**
Archive script for emergency hf which converts all pending blocks which are ancestors of fork point block. All the other pending blocks should be converted to orphaned

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
For the migrated database we should keep the blocks from previous chain (blocks with protocol_version = 2 in this emergency hard fork for example) to be still canonical. Is this the case for your script?

**Comment by dkijania** [comment]
@ghost-not-in-the-shell I think this is covered by this test case:

https://github.com/MinaProtocol/mina/pull/15622/files#diff-6612dcb6e27729a52fe9ac1654b373ea18c13b28245a21e0f426ce1e6ce0d024R20

**Review by SanabriaRusso — APPROVED** [review]
Just relaunched a nightly to be extra sure: https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/33878

From infra standpoint looks ok.

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
