### PR TITLE
Retire Fuzzy zkapp tests in CI

### PR DESCRIPTION
**Pull request by dkijania**
Fuzzy tests gave us too many false failures. Those tests are also long and blocks releases. We tried to maintain them and expand timeouts (individual and total). Therefore we decided to remove them from CI.

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by amc-ie — APPROVED** [review]

**Comment by deepthiskumar** [comment]
Delete `buildkite/src/Command/FuzzyZkappTest.dhall` as well?

**Comment by dkijania** [comment]
@deepthiskumar Maybe i'm blind :( but i don't see https://github.com/MinaProtocol/mina/tree/dkijania/remove_fuzzy_zkapp_unit_tests_from_ci/buildkite/src/Command/FuzzyZkappTest.dhall. I target my branch to master which hasn't got src/Command/FuzzyZkappTests.dhall file (in contrary to develop and compatible)

**Comment by deepthiskumar** [comment]
Weird that it is not in master

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Pull request merged**
