### PR TITLE
Remove delegation integration test

### PR DESCRIPTION
**Pull request by mrmr1993**
This removes the delegation integration test. It isn't testing anything that requires an integration test.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by nholland94** [comment]
I'm all for this change, since the test isn't checking anything about the delegation txn other than it is accepted. Do we have an equivalent unit test for this?

**Comment by mrmr1993** [comment]
> Do we have an equivalent unit test for this?

Doesn't look like it; I've added the test logic to the payment test.

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-nightly-me

**Comment by mrmr1993** [comment]
Nightly run: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/564

**Comment by deepthiskumar** [comment]
!ci-build-me

**Pull request merged**
