### PR TITLE
Rosetta construction tests

### PR DESCRIPTION
**Pull request by ylecornec**
This PR:
- Updates the `rosetta-cli` configuration files to add tests for the construction API.
- Updates the `rosetta-integration-tests.sh` script to run these tests in the CI.

Changes:
- The `mina.ros` file describe the construction api tests and is updated to create accounts and generate payment transactions.
- The `rosetta-cli` configuration files now contain some placeholder that must be replaced after the sandbox is generated.
- Tests are run against `mina-dev` because `rosetta-cli` assumes we are using a `testnet` (See [here](https://github.com/coinbase/rosetta-sdk-go/blob/master/keys/signer_pallas.go#L22)).

Tests:
- The CI job may still fails at a later step (it is left optional) but we can see that the construction tests are successful [here](https://buildkite.com/o-1-labs-2/mina/builds/26189#0184ecae-90fe-4d3e-b1c2-f82c9f3045c1/64-1752).

### CODE REVIEW

**Comment by ylecornec** [comment]
!ci-build-me

**Comment by ylecornec** [comment]
!ci-build-me

**Comment by ylecornec** [comment]
!ci-build-me

**Comment by ylecornec** [comment]
!ci-build-me

**Review by kaozenn — APPROVED** [review]

**Review by lk86 — APPROVED** [review]

**Pull request merged**
