### PR TITLE
Remove token permissions, simplify transaction union tag and old snark logic

### LINKED ISSUE #11957: Rip out token permissions and `isTokenOwned`
Token ownership given by an owning account id, rather than supplemental information in an account.

Remove token permissions in accounts, and the associated type `Token_permissions`.

`isTokenOwned` in GraphQL responses should always be `false`, so that can be removed.

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR removes some code that is no longer triggered by any user commands.

This also results in a small improvement in the old transaction snark circuit.

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them
Closes #11957

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by Trivo25 — APPROVED** [review]

**Review by deepthiskumar — APPROVED** [review]
Some minor comments but otherwise looks good!

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
