### PR TITLE
New protocol version

### LINKED ISSUE #14143: Implement protocol versioning RFC

### PR DESCRIPTION
**Pull request by psteckler**
Implementation of RFC 0049 (in #13993).

Some ancillary changes:
- the `current-protocol-version` daemon CLI flag is removed (the current version is hard-coded)
- the ability to set the current protocol version is likewise removed
- the chain id, instead of using the old major version, uses both the transaction and network components of the protocol version (the implementation is not used)
- the `protocol_versions` table in the archive db is updated

The protocol version type gets bumped to `V2`, but that did not require bumping any other versioned types, which are all  types not in mainnet.

The implementation version is kept as a separate type, so that the proposed protocol version doesn't have to mention the implementation.

The config has separate items for the protocol version and implementation version. I put some numbers there: reviewer, please suggest better ones, if appropriate.

New daemon log: 
```
2023-09-27 20:50:45 UTC [Info] Daemon running protocol version 3.0, with implementation version 2.0
```

Tested `advanced chain-id-inputs` with a local seed daemon:
```
Genesis state hash: 3NKiigEqgn8ZCsT6q3gVeReVdPu3XiBD6XmqnuvUUQzJ9MLWWKi3
Genesis_constants:
  Protocol:          `Assoc ([("k", `Int (290));
                               ("slots_per_epoch", `Int (7140));
                               ("slots_per_sub_window", `Int (7));
                               ("delta", `Int (0));
                               ("genesis_state_timestamp",
                                `String ("2020-09-16 10:15:00.000000Z"))
                               ])
  Txn pool max size: 3000
  Num accounts:      None

Snark keys:
  b8879f677f622a1d86648030701f43e1
  de7b52316bf9a5feaef2bf4295294ee9
  86b438a7a0876894739663a91c0d3c79
Protocol transaction version: 3
Protocol network version: 2
```

The version linter failures are expected.

Closes #14143.

### CODE REVIEW

**Review by MartinMinkov — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Review by nholland94 — CHANGES_REQUESTED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]

**Comment by nholland94** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
