### PR TITLE
Use multi generic agents

### PR DESCRIPTION
**Pull request by dkijania**
Make use of multi generic agents which optimizes usage of agent resources allowing to run n jobs in parallel

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]
Nice!

The companion PR: https://github.com/o1-labs/gitops-infrastructure/pull/99 already provisions some agents in `hetzner-rivendell-1`

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Pull request closed without merging**
