### PR TITLE
Remove last vrf output

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR remove last_vrf_output from preconditions.

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Review by ejMina226 — APPROVED** [review]

**Review by deepthiskumar — CHANGES_REQUESTED** [review]
Remove

**Review by jdsteinhauser — APPROVED** [review]

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
@ghost-not-in-the-shell Just a nit, for future- Do you mind adding commit messages related to the change in the commit? `
address deepthi's comment` doesn't help at all when someone's looking at commit history.

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
Version linter failures are on V1 types for berkeley

**Pull request merged**
