### PR TITLE
removing devnet config and adding testnet overrides for devnet profile

### PR DESCRIPTION
**Pull request by svv232**

### CODE REVIEW

**Comment by svv232** [comment]
!ci-nightly-me

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-nightly-me

**Comment by svv232** [comment]
!ci-nightly-me

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-nightly-me

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Review by dkijania — APPROVED** [review]

**Pull request merged**
