### PR TITLE
SnarkyJS: support zkApp URI

### PR DESCRIPTION
**Pull request by mitschabaude**
companion of https://github.com/o1-labs/snarkyjs/pull/643

### CODE REVIEW

**Review by Trivo25 — APPROVED** [review]

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by bkase — APPROVED** [review]
!approved-for-mainnet

**Comment by mitschabaude** [comment]
!ci-build-me

**Pull request merged**
