### PR TITLE
Toolset for experiment 2

### LINKED ISSUE #12829: Control connection gating config
Contol configuration of direct peers, banned peers, trusted peers, isolation on/off via Control GraphQL introduced in #12811.

### LINKED ISSUE #12843: Orchestrator for experiment 2

### PR DESCRIPTION
**Pull request by georgeee**
This PR updates ITN toolset with the following commands:

- `slots-won`: to query slots won by a node
- `reset-gating`: to reset gating config of a node
- `isolate`: to isolate a set of nodes to form an isolated cluster
- `allocate-slots`: to split block producers into distinct groups of nodes with roughly equal occupation of slot per group (or a desired proportion)

Explain how you tested your changes:
* Slot allocation algorithm is covered with test
* Tooling was tested manually on a private cluster

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes #12829
* Closes #12843

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-build-me

**Review by psteckler — COMMENTED** [review]
OCaml and GraphQL changes are fine.

I'm not able to meaningfully review the Go code.

**Review by psteckler — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Review by mitschabaude — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
