### PR TITLE
Adapt Rosetta API to newest changes in the Archive. 

### PR DESCRIPTION
**Pull request by Sventimir**
Explain your changes:
* Recent changes to the daemon and the archive, esp. to the archive database broke Rosetta API. This PR is to make them compatible again.

Explain how you tested your changes:
* Run [Rosetta CLI](https://www.rosetta-api.org/docs/rosetta_cli.html) tool against a sandboxed berkeley node. Some tests still fail, because there's more to fix. However, other fixes require changes to the daemon itself, so will be fixed in a separate PR.

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* It's a step towards fixing [#52](https://github.com/MinaFoundation/mina/issues/52)

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]

**Pull request merged**
