### PR TITLE
Verification key nullable; topo sort tokens used

### PR DESCRIPTION
**Pull request by psteckler**
Same as #12363, but against `develop`.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by MartinMinkov — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Review by lk86 — APPROVED** [review]

**Pull request merged**
