### PR TITLE
Reduce snarkyjs loading time - DEVELOP

### PR DESCRIPTION
**Pull request by mitschabaude**
Develop version of https://github.com/MinaProtocol/mina/pull/13878 which is the Mina part of https://github.com/o1-labs/snarkyjs/pull/1073

As a side effect, this merges rampup + berkeley -> develop (that's where the first couple of commits come from), which should be done regularly anyway

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Review by MartinMinkov — APPROVED** [review]

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Comment by mitschabaude** [comment]
!ci-build-me

**Pull request merged**
