### PR TITLE
 Resurrecting lookups PR: Add table ID collision assertions

### PR DESCRIPTION
**Pull request by volhovm**
Explain your changes:
* Updating proof-systems to include additional assertions https://github.com/o1-labs/proof-systems/pull/1652
* (Potentially?) fixing tests that violated this logic.

Explain how you tested your changes:
* `dune test`

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
This PR seems to replicate the bug: https://github.com/MinaProtocol/mina/issues/14657

As far as I can tell, the bug is /literally/ just "rust code that we `external`-use from within ocaml panicked". Panic is caused by `unwrap()` in `bindnings/stubs` tests + new `proof-systems` adding an extra assertion that is violated in tests.

I think the most reasonable way to avoid such annoying bugs is to /not use panic/ unless absolutely necessary... I'm thinking these tests can be easily rewritten to use `Result` instead of panic/unwrap.

**Review by querolita — APPROVED** [review]

**Comment by volhovm** [comment]
To double-check, I ran `src/lib` tests in `dev` mode locally and they passed all nicely.

**Comment by volhovm** [comment]
!ci-build-me

**Pull request merged**
