### PR TITLE
fix snarked ledger to staged ledger transition during bootstrap

### PR DESCRIPTION
**Pull request by deepthiskumar**
Say `T1`, `T2`, `T3`, `T4`,... are scan state trees where the first proofs is emitted from `T1` and say `T0` is already completed and deleted from scan state

1. Generating snarked ledger
* Get snarked ledger `S0` at `T0` (the one emitted before T1)
* Get any incomplete zkapp transactions from `T0` (stored as `previous_incomplete_zkapp_updates` in the scan state). The last block added to `T0` may extend to `T1`. Since we are considering first pass ledger as the snarked ledger, we want to apply the following to get snarked ledger `S1` at `T1`
   a. First pass of first block in `T1`
   b. Second pass of any incomplete zkapp transactions from the last block in `T0`
   c. Second pass of first block in `T1`
   d. First pass and second pass of the intermediate blocks in `T1`
   e. Only First pass of the last block in T1

2. Generating staged ledger from snarked ledger at `T0`
For each tree `Tk` in `T1`....`Tn`
 a. First pass of first block in `Tk`
 b. Second pass of any incomplete zkapp transactions from the last block in `Tk-1`
 c. Second pass of first block in `Tk`
 d. First pass and second pass of the intermediate blocks in `Tk`
 e. First pass of the last block in `Tk`
 d. Second pass of the last block in `Tk` if it doesn't extend to `Tk+1` otherwise do second pass in step b.

Added checks in staged ledger to test both 1 and 2

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]
LGTM. I chatted with @deepthiskumar out-of-band about applying the second pass of the last block in a scan state tree when the last block does not overflow into the next scan state tree, which would effect this logic, but we can discuss this separately after this PR merges.

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!ci-build-me

**Pull request merged**
