### PR TITLE
shared state test plus improvements to integration test framework

### PR DESCRIPTION
**Pull request by QuiteStochastic**
port the shared state old integration test over to the new framework

and a few other integration test improvements

### CODE REVIEW

**Comment by QuiteStochastic** [comment]
~ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Review by deepthiskumar — APPROVED** [review]

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Comment by QuiteStochastic** [comment]
!ci-build-me

**Pull request merged**
