### PR TITLE
[CI/Master] Rename copy_control_file -> create_control_file

### PR DESCRIPTION
**Pull request by dkijania**
Another fix for master CI, looks like after update to newest master and fix for mainnet signature there was another issue lurking in the shadows. If we are using mainnet signatures then we are also building devnet package, but for this we are using non-existing method. This PR fixes it

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!help-merge-me

**Comment by dkijania** [comment]
!help-merge-me

**Review by nholland94 — APPROVED** [review]

**Comment by nholland94** [comment]
!approved-for-mainnet

**Pull request merged**
