### PR TITLE
Move static resources https://github.com/MinaProtocol/mina-resources 

### PR DESCRIPTION
**Pull request by dkijania**
Due to issues with LFS quota, we are moving all static resources like various images  to new repo: 
`https://github.com/MinaProtocol/mina-resources` and moving all references to new repository

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
