### PR TITLE
add generation of max-size zkapp commands

### LINKED ISSUE #12895: Update zkApp generator to support max size transactions
Update the zkApp generator to support max size transactions.

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
Explain your changes:
This PR adds an parameter for the zkApp command generator that allows it to generate max-size zkapp commands.
To get max-size zkapp command, we need to populate as much events and actions as possible. So I made one of account updates to include the max amount of events and actions and other account updates to have 0 of them. I also fixed the number account updates to be 5 which reach the cost limit. But this is not the most expensive zkapp commands. Under the current cost limit, the most expensive zkapp commands would consist of a fee payer + 5 account updates with proof authorization. In current implementation, there would be at most 2 account updates with proof authorization (this is limited by how authorization is handled in the generator itself, we could change that, but it's a little complicated). 

Explain how you tested your changes:
*

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #12895

### CODE REVIEW

**Comment by georgeee** [comment]
Hi @ghost-not-in-the-shell !

Could you document im PR description what will be the structure of zkapps generated (# of account updates, authorizations etc.) and why the structure leads to maximum size transaction.

Also, for clarity I would specifically say whether it's max byte size or max computational resources required to process it

Maybe it would be a good idea to put a doc-comment for `gen_zkapp_command_from` about its `max_size` parameter,

**Comment by georgeee** [comment]
Additionally, I think this PR should include using `max_size` parameter from Control Graphql, when a parameter of zkapp tx generation endpoint is set to a specific value.

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
Based on cost function, the allowed combination for account updates are
```
proofs=0  signed_singles=0  signed_pairs=1: Total account updates: 2 
proofs=0  signed_singles=0  signed_pairs=2: Total account updates: 4 
proofs=0  signed_singles=0  signed_pairs=3: Total account updates: 6 
proofs=0  signed_singles=0  signed_pairs=4: Total account updates: 8 
proofs=0  signed_singles=0  signed_pairs=5: Total account updates: 10 
proofs=0  signed_singles=0  signed_pairs=6: Total account updates: 12 
proofs=0  signed_singles=1  signed_pairs=0: Total account updates: 1 
proofs=0  signed_singles=1  signed_pairs=1: Total account updates: 3 
proofs=0  signed_singles=1  signed_pairs=2: Total account updates: 5 
proofs=0  signed_singles=1  signed_pairs=3: Total account updates: 7 
proofs=0  signed_singles=1  signed_pairs=4: Total account updates: 9 
proofs=0  signed_singles=1  signed_pairs=5: Total account updates: 11 
proofs=0  signed_singles=2  signed_pairs=0: Total account updates: 2 
proofs=0  signed_singles=2  signed_pairs=1: Total account updates: 4 
proofs=0  signed_singles=2  signed_pairs=2: Total account updates: 6 
proofs=0  signed_singles=2  signed_pairs=3: Total account updates: 8 
proofs=0  signed_singles=2  signed_pairs=4: Total account updates: 10 
proofs=0  signed_singles=2  signed_pairs=5: Total account updates: 12 
proofs=0  signed_singles=3  signed_pairs=0: Total account updates: 3 
proofs=0  signed_singles=3  signed_pairs=1: Total account updates: 5 
proofs=0  signed_singles=3  signed_pairs=2: Total account updates: 7 
proofs=0  signed_singles=3  signed_pairs=3: Total account updates: 9 
proofs=0  signed_singles=3  signed_pairs=4: Total account updates: 11 
proofs=0  signed_singles=4  signed_pairs=0: Total account updates: 4 
proofs=0  signed_singles=4  signed_pairs=1: Total account updates: 6 
proofs=0  signed_singles=4  signed_pairs=2: Total account updates: 8 
proofs=0  signed_singles=4  signed_pairs=3: Total account updates: 10 
proofs=0  signed_singles=5  signed_pairs=0: Total account updates: 5 
proofs=0  signed_singles=5  signed_pairs=1: Total account updates: 7 
proofs=0  signed_singles=5  signed_pairs=2: Total account updates: 9 
proofs=0  signed_singles=6  signed_pairs=0: Total account updates: 6 
proofs=0  signed_singles=6  signed_pairs=1: Total account updates: 8 
proofs=0  signed_singles=7  signed_pairs=0: Total account updates: 7 
proofs=1  signed_singles=0  signed_pairs=0: Total account updates: 1 
proofs=1  signed_singles=0  signed_pairs=1: Total account updates: 3 
proofs=1  signed_singles=0  signed_pairs=2: Total account updates: 5 
proofs=1  signed_singles=0  signed_pairs=3: Total account updates: 7 
proofs=1  signed_singles=0  signed_pairs=4: Total account updates: 9 
proofs=1  signed_singles=0  signed_pairs=5: Total account updates: 11 
proofs=1  signed_singles=1  signed_pairs=0: Total account updates: 2 
proofs=1  signed_singles=1  signed_pairs=1: Total account updates: 4 
proofs=1  signed_singles=1  signed_pairs=2: Total account updates: 6 
proofs=1  signed_singles=1  signed_pairs=3: Total account updates: 8 
proofs=1  signed_singles=1  signed_pairs=4: Total account updates: 10 
proofs=1  signed_singles=2  signed_pairs=0: Total account updates: 3 
proofs=1  signed_singles=2  signed_pairs=1: Total account updates: 5 
proofs=1  signed_singles=2  signed_pairs=2: Total account updates: 7 
proofs=1  signed_singles=2  signed_pairs=3: Total account updates: 9 
proofs=1  signed_singles=2  signed_pairs=4: Total account updates: 11 
proofs=1  signed_singles=3  signed_pairs=0: Total account updates: 4 
proofs=1  signed_singles=3  signed_pairs=1: Total account updates: 6 
proofs=1  signed_singles=3  signed_pairs=2: Total account updates: 8 
proofs=1  signed_singles=3  signed_pairs=3: Total account updates: 10 
proofs=1  signed_singles=4  signed_pairs=0: Total account updates: 5 
proofs=1  signed_singles=4  signed_pairs=1: Total account updates: 7 
proofs=1  signed_singles=4  signed_pairs=2: Total account updates: 9 
proofs=1  signed_singles=5  signed_pairs=0: Total account updates: 6 
proofs=1  signed_singles=5  signed_pairs=1: Total account updates: 8 
proofs=1  signed_singles=6  signed_pairs=0: Total account updates: 7 
proofs=2  signed_singles=0  signed_pairs=0: Total account updates: 2 
proofs=2  signed_singles=0  signed_pairs=1: Total account updates: 4 
proofs=2  signed_singles=0  signed_pairs=2: Total account updates: 6 
proofs=2  signed_singles=0  signed_pairs=3: Total account updates: 8 
proofs=2  signed_singles=0  signed_pairs=4: Total account updates: 10 
proofs=2  signed_singles=1  signed_pairs=0: Total account updates: 3 
proofs=2  signed_singles=1  signed_pairs=1: Total account updates: 5 
proofs=2  signed_singles=1  signed_pairs=2: Total account updates: 7 
proofs=2  signed_singles=1  signed_pairs=3: Total account updates: 9 
proofs=2  signed_singles=2  signed_pairs=0: Total account updates: 4 
proofs=2  signed_singles=2  signed_pairs=1: Total account updates: 6 
proofs=2  signed_singles=2  signed_pairs=2: Total account updates: 8 
proofs=2  signed_singles=2  signed_pairs=3: Total account updates: 10 
proofs=2  signed_singles=3  signed_pairs=0: Total account updates: 5 
proofs=2  signed_singles=3  signed_pairs=1: Total account updates: 7 
proofs=2  signed_singles=3  signed_pairs=2: Total account updates: 9 
proofs=2  signed_singles=4  signed_pairs=0: Total account updates: 6 
proofs=2  signed_singles=4  signed_pairs=1: Total account updates: 8 
proofs=2  signed_singles=5  signed_pairs=0: Total account updates: 7 
proofs=3  signed_singles=0  signed_pairs=0: Total account updates: 3 
proofs=3  signed_singles=0  signed_pairs=1: Total account updates: 5 
proofs=3  signed_singles=0  signed_pairs=2: Total account updates: 7 
proofs=3  signed_singles=0  signed_pairs=3: Total account updates: 9 
proofs=3  signed_singles=1  signed_pairs=0: Total account updates: 4 
proofs=3  signed_singles=1  signed_pairs=1: Total account updates: 6 
proofs=3  signed_singles=1  signed_pairs=2: Total account updates: 8 
proofs=3  signed_singles=2  signed_pairs=0: Total account updates: 5 
proofs=3  signed_singles=2  signed_pairs=1: Total account updates: 7 
proofs=3  signed_singles=2  signed_pairs=2: Total account updates: 9 
proofs=3  signed_singles=3  signed_pairs=0: Total account updates: 6 
proofs=3  signed_singles=3  signed_pairs=1: Total account updates: 8 
proofs=3  signed_singles=4  signed_pairs=0: Total account updates: 7 
proofs=4  signed_singles=0  signed_pairs=0: Total account updates: 4 
proofs=4  signed_singles=0  signed_pairs=1: Total account updates: 6 
proofs=4  signed_singles=0  signed_pairs=2: Total account updates: 8 
proofs=4  signed_singles=1  signed_pairs=0: Total account updates: 5 
proofs=4  signed_singles=1  signed_pairs=1: Total account updates: 7 
proofs=4  signed_singles=2  signed_pairs=0: Total account updates: 6 
proofs=4  signed_singles=2  signed_pairs=1: Total account updates: 8 
proofs=4  signed_singles=3  signed_pairs=0: Total account updates: 7 
proofs=5  signed_singles=0  signed_pairs=0: Total account updates: 5 
proofs=5  signed_singles=0  signed_pairs=1: Total account updates: 7 
proofs=5  signed_singles=1  signed_pairs=0: Total account updates: 6 
proofs=6  signed_singles=0  signed_pairs=0: Total account updates: 6 
```
Proofs are ~4 times as big as the verification key. So zkapp transactions having max number of proofs is most expensive in terms of computation and size. So i propose the following combination 
1. 5 proofs updates and a fee payer. 
2. Each update has a verification key update
3. One of the updates has max events (100 field elements)
4. One of the updates has max actions (100 field elements)

**Comment by deepthiskumar** [comment]
I don't think we should use quickcheck generator for this (it is already quite complicated). The spec for max size transaction is fixed and so we can simply generate multiple transactions of the same spec. Maybe you could write a separate function that does this instead of modifying the generator?

**Comment by ghost-not-in-the-shell** [comment]
> imes as big as the verification key. So zkapp transactions having max number of proofs is most expensive in terms of computation and size. So i propose the following combination
> 
>     1. 5 proofs updates and a fee payer.
> 
>     2. Each update has a verification key update
> 
>     3. One of the updates has max events (100 field elements)
> 
>     4. One of the updates has max actions (100 field elements)

1. In the discussion of ITN channel I also admitted that 5 proofs update is the most expensive zkapp command, but there's one invariant of the zkapp command generator that all accounts have signature authorization at the very start. The generation of account updates always comes in pairs under current implementation: the account update could possibly alter the authorization of the account and the second account update would change the authorization back to signature. And the balance account update won't change the authorization at all. This design could be changed if we record the change of authorization in the account state tbl. But this would further increase the dependency of zkapp commands. Another option would be make all accounts by default to have proof authorization that way we can still maintain the current structure of generating account updates in pairs and possibly change the authorization in the first account update and change it back in the second account update.
2. This change would be easy
3/4. The current implementation already has the max number of event/action elements. I wrote a unit to check the limit, if you further increase the number, that unit test would fail I think.

**Pull request closed without merging**
