### PR TITLE
Heap usage app in CI

### PR DESCRIPTION
**Pull request by psteckler**
Add a case for `Transaction_snark.Statement` in the `heap_usage` app. Add a CI job to build and run the app.

Repair some bit-rot in the app.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Review by lk86 — APPROVED** [review]

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
