### PR TITLE
Fix Rosetta SQL queries and improve Rosetta integration test reliance

### PR DESCRIPTION
**Pull request by joaosreis**
A change was missing from #14529. This PR fixes it, by adding the missing ids in Rosetta SQL queries.

Another issue was found in retrieving the balance from an account with multiple tokens, when the last relevant command of the account was related to a custom token. This is fixed here by constraining the queries to retrieve the balance to the default token id.

Rosetta integration test was very flaky, requiring many retries to succeed. This is improved by ignoring broadcast errors in `rosetta-cli` configuration. These errors happen because other parallel transactions are being sent to the network and they invalidate things like the nonce used by the Rosetta Construction API.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-nigthly-me

**Comment by joaosreis** [comment]
!ci-nightly-me

**Comment by joaosreis** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1253

**Comment by joaosreis** [comment]
!ci-nightly-me

**Comment by joaosreis** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1256

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-nightly-me

**Comment by joaosreis** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1257

**Review by emberian — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by Sventimir — APPROVED** [review]

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
