### PR TITLE
[do not merge] Testing CI builds from forks

### PR DESCRIPTION
**Pull request by bkase**
Testing ci builds from forks do not merge

### CODE REVIEW

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!ci-build-me

**Comment by bkase** [comment]
!ci-build-me

**Comment by mobileink** [comment]
!ci-build-me?

**Comment by mobileink** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
This is no longer used. Closing.

**Pull request closed without merging**
