### PR TITLE
Faster ledger export (develop)

### PR DESCRIPTION
**Pull request by psteckler**
Fast ledger export for `develop`.

Merged branch for #13336  (faster ledger export for `berkeley`).

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by MartinMinkov — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Pull request merged**
