### PR TITLE
Introduce separate rosetta debian

### PR DESCRIPTION
**Pull request by dkijania**
Split daemon debian into rosetta and daemon one. Then, used both in mina rosetta docker

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Review by joaosreis — CHANGES_REQUESTED** [review]
Only the path of the config file needs to be changed. Everything else LGTM!

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
