### PR TITLE
Replayer, add parens

### PR DESCRIPTION
**Pull request by psteckler**
In the `berkeley` replayer, there's a comparison between accounts in the database and accounts in the replayer ledger. If they don't match, there's an error log issued.

But the code following, which increments an error count, or exits, was not using that comparison to guard its execution.

Add parentheses so that code uses the account comparison as a guard.

(This bug was discovered when exercising the modified replayer that populates the `accounts...` tables.)

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]

**Comment by nholland94** [comment]
!approved-for-mainnet

**Pull request merged**
