### PR TITLE
Lightweight Network configuration and documentation (berkeley).

### PR DESCRIPTION
**Pull request by dkijania**
- Same as https://github.com/MinaProtocol/mina/pull/13287 with additional fix for missing itn_features macro

All the glory should go to @shimkiv

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by shimkiv — CHANGES_REQUESTED** [review]
Can you please pull the latest changes into this one too.

**Comment by dkijania** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by jdsteinhauser — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Pull request merged**
