### PR TITLE
[Berkeley] Bump proof-systems

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR bumps the proof-systems submodule, as a base to support the incoming rust-side fixes to pickles. This PR builds upon #13519.

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by dannywillems — APPROVED** [review]
Seems to be master of proof-systems. Will accept as I suppose changes have been already reviewed.

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by querolita — APPROVED** [review]

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by rbonichon** [comment]
!approved-for-mainnet

**Comment by rbonichon** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by rbonichon** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
