### PR TITLE
Increase individual timeout for fuzzy Zkapp tests & Refactor 

### PR DESCRIPTION
**Pull request by dkijania**
Increased individual timeout for zkapp fuzzy tests and decreased total timeout to 20 minutes.

I also refactored zkapp dhall Jobs and introduced common Command which then is used depending on context

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by SanabriaRusso** [comment]
`!ci-build-me` test is green on the first try!

**Review by georgeee — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
No longer needed since we retired fuzzy tests

**Pull request closed without merging**
