### PR TITLE
Delete old, stale apps from src/app

### PR DESCRIPTION
**Pull request by mrmr1993**
:)

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by nholland94 — APPROVED** [review]
🪦

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by psteckler** [comment]
@mrmr1993 Could `genesis_ledger_from_tsv`, `delegation_compliance`, and `swap_bad_balances` also be removed?

**Comment by mrmr1993** [comment]
!ci-build-me

**Review by dannywillems — APPROVED** [review]
Approval for crypto

**Comment by georgeee** [comment]
!ci-build-me

**Pull request merged**
