### PR TITLE
Don't timeout if offline or bootstrapping before genesis

### PR DESCRIPTION
**Pull request by psteckler**
If we see an `Offline` online status before genesis, don't  restart libp2p or raise a timeout. Similarly, if the active status is `Bootstrapping` before genesis, don't set the bootstrap timeout.

Also: fixed obsolete comment.

Before this change, verified it was possible to crash the daemon via the `Offline_shutdown` exception, by setting the offline timeout and the `stabilize` interval to small values.

To test the fix, set the low values for the offline timeout and `stabilize` interval, disabled the `is_seed` check, set the genesis timestamp to sometime in 2024, and inverted the `after_genesis` result, so that the offline timeout was checked before genesis. Ran that twice, both times the node crashed with the `offline too long` error after a couple of minutes. Then, ran `after_genesis` normally, so that the offline timeout was *not* checked before genesis, and the node did not crash after running for 10 minutes.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
Could you add to the PR description, how you tested the change?

**Comment by psteckler** [comment]
> Could you add to the PR description, how you tested the change?

Done. / @deepthiskumar

**Review by deepthiskumar — APPROVED** [review]

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Comment by psteckler** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
