### PR TITLE
[berkeley] expose lookup verifier index

### PR DESCRIPTION
**Pull request by dannywillems**
Explain your changes:
* Counterpart of https://github.com/MinaProtocol/mina/pull/13882
* Related to https://github.com/o1-labs/proof-systems/pull/1186, https://github.com/o1-labs/snarkyjs/pull/1084, https://github.com/o1-labs/snarkyjs-bindings/pull/121

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Comment by dannywillems** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Review by mitschabaude — APPROVED** [review]

**Comment by dannywillems** [comment]
Opened follow-up issue [here](https://github.com/MinaProtocol/mina/issues/13944) regarding @rbonichon comments above.

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
