### PR TITLE
[Berkeley] Merge rampup - Add o1js-stub to Mina repo in place of SnarkyJS

### PR DESCRIPTION
**Pull request by MartinMinkov**
Merge https://github.com/MinaProtocol/mina/pull/14788 into `berkeley`

### CODE REVIEW

**Comment by MartinMinkov** [comment]
!ci-build-me

**Comment by MartinMinkov** [comment]
!ci-build-me

**Comment by MartinMinkov** [comment]
!ci-build-me

**Comment by MartinMinkov** [comment]
!ci-build-me

**Comment by MartinMinkov** [comment]
!ci-build-me

**Comment by MartinMinkov** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by MartinMinkov** [comment]
!ci-build-me

**Review by bkase — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Pull request merged**
