### PR TITLE
Introduce checkpoint prefix argument to migration script

### PR DESCRIPTION
**Pull request by dkijania**
Exposing checkpoint-prefix parameter in berkeley migration script. It might be helpful when we have more that one migration on single machine (devnet and mainnet) and for some reason we would like to keep both checkpoints. This is the case for our cron job which is used for more than one network and it need to be aware of checkpoint prefixes

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Pull request merged**
