### PR TITLE
[develop] Script to generate ledger tar from config with accounts

### PR DESCRIPTION
**Pull request by joaosreis**
See #14793.

### CODE REVIEW

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Comment by joaosreis** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Pull request merged**
