### PR TITLE
Remove use of submodules

### PR DESCRIPTION
**Pull request by georgeee**
Explain your changes:
* Remove all submodules and copied-in repositories (except for `ocaml-rocksdb`, which building strategy makes it non-trivial)
 
Explain how you tested your changes:
* [x] `nix build github:MinaProtocol/mina/georgeee/remove-unnecessary-submodules#devnet` to test nix build
* [x] CI passes

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Review by emberian — APPROVED** [review]

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-toolchain-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-nightly-me

**Review by mitschabaude — COMMENTED** [review]
My 2c: this is not a good idea

**Comment by georgeee** [comment]
@mitschabaude and I had a discussion in [Slack](https://o1-labs.slack.com/archives/C0206B5S80Y/p1712814476609219) to discuss pros and cons of this approach.

**Comment by georgeee** [comment]
A caveat of this approach: each `snarky` update would require a rebuild of a toolchain. AFAIU `snarky` is not updated frequently, so this shouldn't be an issue. And `check-opam-switch` will ensure toolchain is updated on a PR changing this dependency.

**Review by mrmr1993 — CHANGES_REQUESTED** [review]
This breaks the flow of the crypto and SDK teams' development. Don't do this

**Comment by georgeee** [comment]
It was decided not to merge this PR at the moment and keep use of submodules between mina-related repositories

**Pull request closed without merging**
