### PR TITLE
adding network id field to the daemon

### PR DESCRIPTION
**Pull request by svv232**
adding network id to the daemon for hard fork testing. the objective is to get the network id graphql call to return based on this result.

### CODE REVIEW

**Comment by svv232** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by svv232** [comment]
!ci-build-me

**Comment by L-as** [comment]
@svv232 There's also supposed to be a signatureKind GQL call, will this affect that too?

**Comment by svv232** [comment]
> @svv232 There's also supposed to be a signatureKind GQL call, will this affect that too?

I don't think so because that seems to correspond with compile time configs in the `mlh` files.

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Pull request closed without merging**
