### PR TITLE
[rampup] Add 'merges cleanly to rampup' CI job

### PR DESCRIPTION
**Pull request by mrmr1993**
This is #14895 against rampup

### CODE REVIEW

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
Looks like there are some changes not related to the CI job in this PR @mrmr1993 Are these needed?

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Comment by mrmr1993** [comment]
> Are these needed?

They come from the merge `compatible -> rampup`. The goal of this PR is to unblock https://github.com/MinaProtocol/mina/pull/14895, which will make PRs like this unnecessary

**Comment by mrmr1993** [comment]
Concretely, this PR is https://github.com/MinaProtocol/mina/pull/14954 and https://github.com/MinaProtocol/mina/pull/14895 combined.

**Comment by deepthiskumar** [comment]
>They come from the merge compatible -> rampup. The goal of this PR is to unblock https://github.com/MinaProtocol/mina/pull/14895, which will make PRs like this unnecessary

Oh ok. I just created a one for merging compatible changes https://github.com/MinaProtocol/mina/pull/14954 and subsequent PRs for berkeley and develop. Once the berkeley and develop ones land you can merge this and I can close #14954

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
