### PR TITLE
Changed inputs to forks and fixed opam-nix change

### PR DESCRIPTION
**Pull request by Smorci**
My formatter changed lots of lines.

The changes made by me were in the inputs of flake.nix, flake.lock and on line 47 in ocaml.nix

### CODE REVIEW

**Review by michal0mina — APPROVED** [review]
looks good; next time please isolate white space changes to separate commit

**Review by simisimis — APPROVED** [review]

**Comment by Smorci** [comment]
!ci-build-me

**Comment by Smorci** [comment]
!ci_build_me

**Comment by Smorci** [comment]
!ci-build-me

**Comment by simisimis** [comment]
!ci-build-me

**Comment by Smorci** [comment]
!ci-build-me

**Review by simisimis — COMMENTED** [review]
the way nix manages dependencies through a lock file I don't see a reason to switch to our forked repos. This adds complexity to maintenance, update procedure and code readability.

The only reason I see for doing so, is to make sure that those external repos will not disappear in the future. But for that we can still fork them and have them as backups. We don't need to also switch to using them and only put effort in switching to them if that disaster actually ever happens.

**Pull request closed without merging**
