### PR TITLE
Fix: Remove batch-payments command from cli

### LINKED ISSUE #4597: remove/update cli command batch-send-payments
With #4553, the internal flow of local transactions changed causing `batch-send-payments` to send keypair over rpc. We either change it such that it uses graphql or delete if no longer in use. Once this is done, we can remove the serialized versions in user_command_input.ml

### PR DESCRIPTION
**Pull request by figitaki**
Closes #4597

### CODE REVIEW

**Comment by aneesharaines** [comment]
!approved-for-mainnet

**Review by deepthiskumar — APPROVED** [review]

**Comment by aneesharaines** [comment]
!approved-for-mainnet

**Comment by aneesharaines** [comment]
!approved-for-mainnet

**Comment by MartinMinkov** [comment]
Note:

This is planned to be added in a hotfix at a later date. When this gets merged, it is important to note that the
 `mina advanced batch-payments` 
command will be deprecated. This will need to be communicated.

**Comment by mrmr1993** [comment]
This change landed independently. Closing.

**Pull request closed without merging**
