### PR TITLE
[Merge Conflict Fix] port '[CI] explicitly select if mainnet should be built' to compatible

### PR DESCRIPTION
**Pull request by dkijania**
This is autogenerated Pull Request for porting #15794 to compatible
@dkijania

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Review by SanabriaRusso — APPROVED** [review]

**Pull request merged**
