### PR TITLE
Auto Promote Nightly Packages

### PR DESCRIPTION
**Pull request by dkijania**
Added new job which should promote nightly (code is open in such way it does not limit to nighlty only) packages to nightly debian channel and assign new docker tag which can track nightly dockers. This feature is mainly for internal use in order to find stable packages more easily as promoting will be done after nightly pipeline is green or manually by specifing particular version of packages residing in unstable channel.

It also have accompanying verify jobs which test promotion process For example below setup can be used to promote manually specified version:

https://buildkite.com/o-1-labs-2/promote-nightly-packages

`FROM_VERSION_MANUAL="3.0.0-compatible-3a12afc"`

pipeline by default  to use HEAD of current compatible

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]
Very useful workflow to have.

**Pull request merged**
