### PR TITLE
use mina missing block guardian script in rosetta

### PR DESCRIPTION
**Pull request by dkijania**
Fix for missing download-missing-block.sh script. It was removed a long time ago and supposed to be replaced by missing-block-guardian.sh script. This pr is replacing usage of download-missing-block.sh with missing-block-guardian.sh.

As a lesson learned, I added two tests for bundled rosetta docker, for each devnet and mainnet network. It runs rosetta agains desired network and try to sync at least 10 blocks from network. Both tests takes up to 15 minutes, so they are setup to run only on nightly. We can debate if not run them only on release pipeline

### CODE REVIEW

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
Nightly: 

https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2974

**Review by SanabriaRusso — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Comment by dkijania** [comment]
!ci-build-me

**Comment by dkijania** [comment]
!ci-nightly-me

**Pull request merged**
