### PR TITLE
Fix verification in dry runs: alternative take

### LINKED ISSUE #15577: Fix HF pipeline for custom testnets

### PR DESCRIPTION
**Pull request by georgeee**
Fix verification of fork package.

Develop version: #15599

Explain how you tested your changes:
* [x] Mainnet (on #15591): https://buildkite.com/o-1-labs-2/hardfork-package-generation/builds/280
* [x] Devnet (on #15591): https://buildkite.com/o-1-labs-2/hardfork-package-generation/builds/281
* [x] Mainnet dry run (on #15591): https://buildkite.com/o-1-labs-2/hardfork-package-generation/builds/282

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes #15577

### CODE REVIEW

**Review by mrmr1993 — APPROVED** [review]

**Comment by mrmr1993** [comment]
!approved-for-mainnet

**Review by dkijania — APPROVED** [review]
Looks good. I will update nightly cron job after this is merged

**Comment by deepthiskumar** [comment]
!ci-build-me

**Comment by georgeee** [comment]
Reviewed change by Jiawei, pushed a tiny fixup to simplify the code

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Pull request merged**
