### PR TITLE
[dev] update mac setup

### PR DESCRIPTION
**Pull request by mimoo**
this fixes `make snarkyjs` on mac

### CODE REVIEW

**Review by mitschabaude — APPROVED** [review]
Nice!

**Review by lk86 — APPROVED** [review]

**Comment by mimoo** [comment]
!ci-build-me

**Review by bkase — APPROVED** [review]
Still doesn't work on my machine, but Nix always does :)

Ideally, we deprecate this (especially the macOS flow which tends to always be brittle), but for now I suppose this is in a better state than it was before

**Comment by mimoo** [comment]
what doesn't work on your machine btw?

**Pull request merged**
