### PR TITLE
update README to remove coda and link to docs2

### PR DESCRIPTION
**Pull request by barriebyron**
Explain your changes:
* update the docs readme to remove coda and link to active docs repository

Explain how you tested your changes:
* text changes and link checks

Checklist:

- [x ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

### CODE REVIEW

**Comment by barriebyron** [comment]
!ci-build-me

**Review by georgeee — APPROVED** [review]

**Comment by barriebyron** [comment]
@georgeee  do I need to submit a PR for other branches? 
can you guide me through the steps to get this PR merged?

**Comment by georgeee** [comment]
!ci-build-me

**Comment by barriebyron** [comment]
@georgeee  thank you for merging, please feel free to do for any PRs that are approved and do not require changes

I appreciate you!

**Pull request merged**
