### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by rex4539** [comment]
@mrmr1993 Could you please review?

**Comment by mrmr1993** [comment]
@rex4539 this PR touches docs, RFCs, code, infrastructure configuration, etc. Naturally, we need to be more cautious about reviewing and testing changes to code and infra than docs and RFCs. Would you mind splitting this up into separate PRs that make each set of changes?

**Comment by rex4539** [comment]
I'm not as fluent in git commands.

If someone can post the exact commands I need to type, I will happily try them.

But I'm afraid if I experiment with the git commands by my own, it's certain that I will mess up my repo.

**Comment by mrmr1993** [comment]
The git docs contain [a tutorial](https://git-scm.com/docs/gittutorial), which you may find useful.

**Comment by mimoo** [comment]
@rex4539 I recommend https://www.sublimemerge.com/

**Pull request closed without merging**
