### PR TITLE
Merge 13460 to berkeley

### PR DESCRIPTION
**Pull request by psteckler**
Allow clean merge of branch in #13460 to `berkeley`.

### CODE REVIEW

**Comment by psteckler** [comment]
!ci-build-me

**Comment by psteckler** [comment]
!ci-build-me

**Review by QuiteStochastic — APPROVED** [review]

**Review by shimkiv — APPROVED** [review]

**Comment by psteckler** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!approved-for-mainnet

**Pull request merged**
