### PR TITLE
[Plugin] OCaml toplevel running inside daemon

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR adds a plugin using the [ocamlnat toplevel library](https://github.com/mrmr1993/ocamlnat/) (which I've extracted from the OCaml main repo). This is ridiculously unsafe and hard to use properly for a variety of reasons, not least of which are
* directories containing the `.cmi` files have to be manually loaded using `#directory` directives
  - These only take absolute paths (i.e. `/path/to/mina/_build/default/src/lib/coda_plugins/examples/toplevel/.plugin_toplevel.eobjs/byte`). I plan to fix this in the `ocamlnat` repo at some point.
  - No directories are loaded by default. `dune-describe` seems to give all of the relevant information, but it's an unstable representation in an undocumented format, and I haven't bothered to write a parser or loader using it yet.
* there is no check that values exist in the executable before running a linked command
  - I plan to investigate whether this is possible to fix, and fix it if it is.
  - Running a command that refers to values that aren't present exits with an exception. This is easily fixed, which I plan to do.
* every evaluation adds to memory use, as it loads a dynamic library that is never unloaded
  - This is mostly a necessity of implementation. It may be possible to do something here by detecting that the compiled code contains no functions/captured closures/etc. and free only those dynlibs, or to do something horrendous with finalisers. I have no intention of doing this any time soon.
* the toplevel is missing some useful directives (`#show_module`/`#show_type`/etc.) that are present in the bytecode toplevel
  - I plan to add these to the `ocamlnat` repo.
* the interaction happens on stdin/stdout, where logging is also happening
  - There are a few cleverer things we could do here, but it's not clear that this will ever get enough use to warrant fixing it.
  - See sample run below for how this manifests.
* the `Obj` functions can be used to hotpatch functions in the executable (if they haven't been inlined)
  - This is super, super dangerous, but also very cool to play with.
* the native toplevel is imported wholesale
  - It should be reasonably easy (if labourious) to library-ise it, but at present it believes that it *is* the toplevel, with all the error handling and exit conditions that entails
* the async yeilding is a hack in the middle of the parse loop, using some lower-level `Async` thread management primitives.
  - This actually seems to work well, but a library-ised toplevel would make this safe and straightforward.
* printing of values is touch-and-go, depending on whether the directories containing the declarations for the types it includes are loaded or not

To try this out (please, please not on a node you care about!),
* install the [`ocamlnat`](https://github.com/mrmr1993/ocamlnat/) package by pinning its github repo
* build the plugin with `dune build src/lib/coda_plugins/examples/toplevel/plugin_toplevel.cmxs`
* start the daemon with the plugin loaded `rlwrap _build/default/src/app/cli/src/coda.exe daemon -seed -load-plugin _build/default/src/lib/coda_plugins/examples/toplevel/plugin_toplevel.cmxs`
  - I recommend `rlwrap` here to make the toplevel's behaviour slightly less unbearable.
* load the (bytecode) directories for the modules you want and start poking around in
  - `#directory "/path/to/mina/_build/default/src/lib/coda_plugins/examples/toplevel/.plugin_toplevel.eobjs/byte";;` is good to have, as it exposes a reference to the `Coda_lib` instance in `Dune__exe__Plugin_toplevel.coda`
  - `#directory "/path/to/mina/_build/default/src/lib/coda_lib/.coda_lib.objs/byte";;` loads `Coda_lib`, making the functions available to poke at the above reference
  - `#directory "/path/to/.opam/4.07.1/lib/core_kernel";;` (as well as `async`, `async_kernel`) are nice to have for quality of life in the toplevel.

Sample run:
```ocaml
$ rlwrap _build/default/src/app/cli/src/coda.exe daemon -seed -load-plugin _build/default/src/lib/coda_plugins/examples/toplevel/plugin_toplevel.cmxs
2020-11-28 18:19:44 UTC [Info] Coda daemon is booting up; built with commit "b5967c18d848fca003006bba95d9983b61575500" on branch "feature/toplevel-plugin"
...
(* SNIP *)
...
2020-11-28 18:19:45 UTC [Info] Coda daemon is connecting
2020-11-28 18:19:45 UTC [Info] Initializing plugins
2020-11-28 18:19:45 UTC [Info] Initializing plugin from $path
        path: "_build/default/src/lib/coda_plugins/examples/toplevel/plugin_toplevel.cmxs"
2020-11-28 18:19:45 UTC [Info] Hi from toplevel plugin!
        OCaml version 4.07.1 - native toplevel

2020-11-28 18:19:45 UTC [Info] Plugin successfully loaded from $path
        path: "_build/default/src/lib/coda_plugins/examples/toplevel/plugin_toplevel.cmxs"
2020-11-28 18:19:45 UTC [Info] Pausing block production while bootstrapping
2020-11-28 18:19:45 UTC [Info] Attempted to turn on snark worker, but snark worker key is set to none
2020-11-28 18:19:45 UTC [Info] Daemon ready. Clients can now connect
2020-11-28 18:19:45 UTC [Info] Created GraphQL server at: http://localhost:3085/graphql
#directory "/home/matthew/source_code/coda/_build/default/src/lib/coda_plugins/examples/toplevel/.plugin_toplevel.eobjs/byte";;
# #directory "/home/matthew/source_code/coda/_build/default/src/lib/coda_lib/.coda_lib.objs/byte";;
# #directory "/home/matthew/.opam/coda/lib/core_kernel";;
# #directory "/home/matthew/.opam/coda/lib/async_kernel";;
# #directory "/home/matthew/.opam/coda/lib/async";;
# open Core_kernel;;
# open Async;;
# let coda = Dune__exe__Plugin_toplevel.coda;;
val coda : Coda_lib.t = <abstr>
# Coda_lib.next_producer_timing coda;;
- : Consensus.Hooks.block_producer_timing option = None
# 2020-11-28 18:20:45 UTC [Info] Will start initialization without connecting with too any peers
2020-11-28 18:20:45 UTC [Info] Fast forward successful
2020-11-28 18:20:45 UTC [Info] Loaded full frontier and extensions
2020-11-28 18:20:45 UTC [Info] Successfully loaded frontier
2020-11-28 18:20:45 UTC [Info] Requesting peers for their best tip to do initialization
2020-11-28 18:20:45 UTC [Info] Successfully loaded frontier, but failed to download best tip from network; starting participation
2020-11-28 18:20:45 UTC [Info] Starting transition frontier controller phase
2020-11-28 18:20:45 UTC [Info] Coda daemon is connecting
2020-11-28 18:20:45 UTC [Info] Updating new available work took 0.00762939453125 ms
2020-11-28 18:20:45 UTC [Info] Determining next slot to produce block
2020-11-28 18:20:45 UTC [Info] No block producers running, skipping check for now.
Coda_lib.next_producer_timing coda;;
- : Consensus.Hooks.block_producer_timing option = Some <abstr>
# #directory "/home/matthew/source_code/coda/_build/default/src/lib/consensus/.consensus.objs/byte";;
# Coda_lib.next_producer_timing coda;;
- : Consensus.Hooks.block_producer_timing option =
Some (`Check_again <abstr>)
# let deferred_peers = Coda_lib.peers coda;;
val deferred_peers : Network_peer.Peer.t list Async_kernel.Deferred.t =
  <abstr>
# Thread_safe.block_on_async_exn (fun () -> deferred_peers);;
Error: The module Thread_safe is an alias for module Async_unix__.Thread_safe, which is missing
# #directory "/home/matthew/.opam/coda/lib/async_unix";;
# Async_unix.Thread_safe.block_on_async_exn (fun () -> deferred_peers);;
- : Network_peer.Peer.t list = []
# #directory "/home/matthew/source_code/coda/_build/default/src/lib/network_pool/.network_pool.objs/byte";;
# let txn_pool = Coda_lib.transaction_pool coda;;
val txn_pool : Network_pool.Transaction_pool.t = <abstr>
# 2020-11-28 18:24:00 UTC [Info] Determining next slot to produce block
2020-11-28 18:24:00 UTC [Info] No block producers running, skipping check for now.
# Network_pool.Transaction_pool.get_all;;
Error: Unbound value Network_pool.Transaction_pool.get_all
# module Txn_pool = struct include Network_pool.Transaction_pool end;;
module Txn_pool :
  sig
...
(* SNIP: This is a cheat I used to check the signature of Transaction_pool. Large signature elided. *)
...
    val resource_pool : t -> Resource_pool.t
    val broadcasts : t -> Diff_versioned.t Pipe_lib.Linear_pipe.Reader.t
    val apply_and_broadcast :
      t ->
      Diff_versioned.verified Network_peer.Envelope.Incoming.t ->
      Broadcast_callback.t -> unit Async_kernel.Deferred.t
  end
# Network_pool.Transaction_pool.(Resource_pool.get_all (resource_pool txn_pool));;
- : Coda_base.Transaction_hash.User_command_with_valid_signature.t list = []
# Obj.reachable_words (Obj.repr txn_pool);;
- : int = 170174
# exit 0
  ;;
2020-11-28 18:28:38 UTC [Info] Running async shutdown handler: "Close transition frontier, if exists"
2020-11-28 18:28:38 UTC [Info] Running async shutdown handler: "Remove daemon lockfile"
- : 'a Async_unix__.Import.Deferred.t = <abstr>
```

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Review by psteckler — APPROVED** [review]
Sure, why not?

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by mrmr1993** [comment]
!ci-build-me

**Pull request merged**
