### PR TITLE
Devnet HF stop slots

### PR DESCRIPTION
**Pull request by deepthiskumar**
Tentative devnet HF stop slots for April 9th 2024 9 am UTC

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

### CODE REVIEW

**Comment by deepthiskumar** [comment]
!ci-build-me

**Review by ghost-not-in-the-shell — APPROVED** [review]
The transaction slot slot is 4/9/2024 9 am UTC

**Review by emberian — APPROVED** [review]

**Comment by emberian** [comment]
I propose we not merge these until we've completed the dry run testing.

**Comment by mrmr1993** [comment]
!ci-build-me

**Comment by deepthiskumar** [comment]
Will create follow-up PRs to fix conflicts with develop and berkeley (and remove the stop slots). Merging this to unblock the devent release

**Pull request merged**
