### PR TITLE
swapping out the s3 bucket link for snark-keys

### PR DESCRIPTION
**Pull request by svv232**
this change mirrors the changes merged in release 3.0.1: https://github.com/MinaProtocol/mina/pull/15824/files

### CODE REVIEW

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Comment by svv232** [comment]
!ci-build-me

**Review by SanabriaRusso — APPROVED** [review]

**Comment by SanabriaRusso** [comment]
Please consider the suggestions made [here](https://o1-labs.slack.com/archives/C0206B5S80Y/p1723743334034929) before merging

**Review by dkijania — APPROVED** [review]

**Pull request merged**
