### PR TITLE
Fix HF unit test after compatible update

### PR DESCRIPTION
**Pull request by georgeee**
Explain your changes:
* One of patches that was applied to `compatible` was merged to `compatible`

Explain how you tested your changes:
* Ran the HF unit test

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-build-me

**Comment by georgeee** [comment]
Launched a CI job to run HF unit test: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1756#018ea376-9eda-42a9-9777-8352d68b969b

**Comment by ghost-not-in-the-shell** [comment]
Are the patches for caqti-upgrade?

**Comment by georgeee** [comment]
> Are the patches for caqti-upgrade?

This PR removes `scripts/hardfork/localnet-patches/compatible-2.patch` that contained what PR #15433 merged.

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Pull request merged**
