### PR TITLE
kill the libp2p helper periodically

### PR DESCRIPTION
**Pull request by imeckler**
This PR kills the libp2p helper every 11 +/- 2.5 minutes.

### CODE REVIEW

**Review by nholland94 — APPROVED** [review]
Code looks good. Did you run a local network to confirm that the libp2p helper is able to successfully reconnect without errors?

**Comment by imeckler** [comment]
> Code looks good. Did you run a local network to confirm that the libp2p helper is able to successfully reconnect without errors?

Nah lemme do that

**Comment by nholland94** [comment]
> Good call, did it and it seems to work! I am seeing a lot of "error bumping delivery tag: no decaying tag registered for topic coda/consensus-messages/0.0.1" messages though.

We are seeing this message a lot on the network atm, so that should be ok I think (@lk86 to confirm).

**Review by lk86 — APPROVED** [review]

**Review by bkase — APPROVED** [review]

**Comment by imeckler** [comment]
added env vars 
- MINA_LIBP2P_HELPER_RESTART_INTERVAL_BASE (default = 7)
- MINA_LIBP2P_HELPER_RESTART_INTERVAL_DELTA (default = 2.5)

**Pull request merged**
